export const FRONTENDNAMES = [
  {key:"MM_ARROW_FIRE", name:"Fire Arrows (MM)"},
  {key:"MM_ARROW_ICE", name:"Ice Arrows (MM)"},
  {key:"MM_ARROW_LIGHT", name:"Light Arrows (MM)"},
  {key:"MM_BOMBCHU", name:"1 Bombchu (MM)"},
  {key:"MM_BOMBCHU_10", name:"10 Bombchu (MM)"},
  {key:"MM_BOMBCHU_5", name:"5 Bombchu (MM)"},
  {key:"MM_BOMBER_NOTEBOOK", name:"Bomber's Notebook"},
  {key:"MM_BOMB_BAG", name:"Bomb Bag (MM)"},
  {key:"MM_BOSS_KEY_GB", name:"Boss Key (Great Bay Temple)"},
  {key:"MM_BOSS_KEY_SH", name:"Boss Key (Snowhead Temple)"},
  {key:"MM_BOSS_KEY_ST", name:"Boss Key (Stone Tower Temple)"},
  {key:"MM_BOSS_KEY_WF", name:"Boss Key (Woodfall Temple)"},
  {key:"MM_BOTTLED_CHATEAU_ROMANI", name:"Bottle - Chateau Romani (MM)"},
  {key:"MM_BOTTLED_GOLD_DUST", name:"Bottle - Gold Dust (MM)"},
  {key:"MM_BOTTLED_MILK", name:"Bottle - Milk (MM)"},
  {key:"MM_BOTTLED_POTION_RED", name:"Bottle - Red Potion (MM)"},
  {key:"MM_BOW", name:"Bow (MM)"},
  {key:"MM_COMPASS_GB", name:"Compass (Great Bay Temple)"},
  {key:"MM_COMPASS_SH", name:"Compass (Snowhead Temple)"},
  {key:"MM_COMPASS_ST", name:"Compass (Stone Tower Temple)"},
  {key:"MM_COMPASS_WF", name:"Compass (Woodfall Temple)"},
  {key:"MM_DEED_LAND", name:"Land Title Deed"},
  {key:"MM_DEED_MOUNTAIN", name:"Mountain Title Deed"},
  {key:"MM_DEED_OCEAN", name:"Ocean Title Deed"},
  {key:"MM_DEED_SWAMP", name:"Swamp Title Deed"},
  {key:"MM_DEFENSE_UPGRADE", name:"Double Defense (MM)"},
  {key:"MM_EMPTY_BOTTLE", name:"Bottle - Empty (MM)"},
  {key:"MM_GREAT_FAIRY_SWORD", name:"Great Fairy Sword"},
  {key:"MM_GS_TOKEN_OCEAN", name:"Ocean Spider Token"},
  {key:"MM_GS_TOKEN_SWAMP", name:"Swamp Spider Token"},
  {key:"MM_HEART_CONTAINER", name:"Heart Container (MM)"},
  {key:"MM_HEART_PIECE", name:"Heart Piece (MM)"},
  {key:"MM_HOOKSHOT", name:"Hookshot (MM)"},
  {key:"MM_LENS", name:"Lens of Truth (MM)"},
  {key:"MM_LETTER_TO_KAFEI", name:"Letter to Kafei"},
  {key:"MM_LETTER_TO_MAMA", name:"Express Mail to Mama"},
  {key:"MM_MAGIC_BEAN", name:"Magic Bean (MM)"},
  {key:"MM_MAGIC_UPGRADE", name:"Magic Upgrade (MM)"},
  {key:"MM_MAP_GB", name:"Map (Great Bay Temple)"},
  {key:"MM_MAP_SH", name:"Map (Snowhead Temple)"},
  {key:"MM_MAP_ST", name:"Map (Stone Tower Temple)"},
  {key:"MM_MAP_WF", name:"Map (Woodfall Temple)"},
  {key:"MM_MASK_ALL_NIGHT", name:"All Night's Mask"},
  {key:"MM_MASK_BLAST", name:"Blast Mask"},
  {key:"MM_MASK_BREMEN", name:"Bremen Mask"},
  {key:"MM_MASK_BUNNY", name:"Bunny Hood (MM)"},
  {key:"MM_MASK_CAPTAIN", name:"Captain's Hat"},
  {key:"MM_MASK_COUPLE", name:"Couple's Mask"},
  {key:"MM_MASK_DEKU", name:"Deku Mask"},
  {key:"MM_MASK_DON_GERO", name:"Don Gero Mask"},
  {key:"MM_MASK_FIERCE_DEITY", name:"Fierce Diety Mask"},
  {key:"MM_MASK_GARO", name:"Garo Mask"},
  {key:"MM_MASK_GIANT", name:"Giant's Mask"},
  {key:"MM_MASK_GIBDO", name:"Gibdo Mask"},
  {key:"MM_MASK_GORON", name:"Goron Mask (MM)"},
  {key:"MM_MASK_GREAT_FAIRY", name:"Great Fairy Mask"},
  {key:"MM_MASK_KAFEI", name:"Kafei's Mask"},
  {key:"MM_MASK_KAMARO", name:"Kamaro Mask"},
  {key:"MM_MASK_KEATON", name:"Keaton Mask"},
  {key:"MM_MASK_POSTMAN", name:"Postman's Hat"},
  {key:"MM_MASK_ROMANI", name:"Romani Mask"},
  {key:"MM_MASK_SCENTS", name:"Mask of Scents"},
  {key:"MM_MASK_STONE", name:"Stone Mask"},
  {key:"MM_MASK_TROUPE_LEADER", name:"Circus Leader's Mask"},
  {key:"MM_MASK_TRUTH", name:"Mask of Truth (MM)"},
  {key:"MM_MASK_ZORA", name:"Zora Mask (MM)"},
  {key:"MM_MOON_TEAR", name:"Moon Tear"},
  {key:"MM_OCARINA", name:"Ocarina (MM)"},
  {key:"MM_PENDANT_OF_MEMORIES", name:"Pendant of Memories"},
  {key:"MM_PICTOGRAPH_BOX", name:"Pictograph Box"},
  {key:"MM_POWDER_KEG", name:"Powder Keg"},
  {key:"MM_REMAINS_GOHT", name:"Goht's Remains"},
  {key:"MM_REMAINS_GYORG", name:"Gyorg's Remains"},
  {key:"MM_REMAINS_ODOLWA", name:"Odolwa's Remains"},
  {key:"MM_REMAINS_TWINMOLD", name:"Twinmold's Remains"},
  {key:"MM_ROOM_KEY", name:"Room Key"},
  {key:"MM_RUPEE_BLUE", name:"Blue Rupee (MM)"},
  {key:"MM_RUPEE_GOLD", name:"Gold Rupee (MM)"},
  {key:"MM_RUPEE_PURPLE", name:"Purple Rupee (MM)"},
  {key:"MM_RUPEE_RED", name:"Red Rupee (MM)"},
  {key:"MM_RUPEE_SILVER", name:"Silver Rupee (MM)"},
  {key:"MM_SHIELD_MIRROR", name:"Mirror Shield (MM)"},
  {key:"MM_SMALL_KEY_GB", name:"Small Key (Great Bay Temple)"},
  {key:"MM_SMALL_KEY_SH", name:"Small Key (Snowhead Temple)"},
  {key:"MM_SMALL_KEY_ST", name:"Small Key (Stone Tower Temple)"},
  {key:"MM_SMALL_KEY_WF", name:"Small Key (Woodfall Temple)"},
  {key:"MM_SONG_AWAKENING", name:"Sonata of Awakening"},
  {key:"MM_SONG_EMPTINESS", name:"Elegy of Emptiness"},
  {key:"MM_SONG_EPONA", name:"Epona's Song (MM)"},
  {key:"MM_SONG_GORON_HALF", name:"Progressive Goron Lullaby"},
  {key:"MM_SONG_HEALING", name:"Song of Healing"},
  {key:"MM_SONG_ORDER", name:"Oath to Order"},
  {key:"MM_SONG_SOARING", name:"Song of Soaring"},
  {key:"MM_SONG_STORMS", name:"Song of Storms (MM)"},
  {key:"MM_SONG_TIME", name:"Song of Time (MM)"},
  {key:"MM_SONG_ZORA", name:"New Wave Bossa Nova"},
  {key:"MM_SPIN_UPGRADE", name:"Spin Attack"},
  {key:"MM_STRAY_FAIRY_GB", name:"Stray Fairy (Great Bay Temple)"},
  {key:"MM_STRAY_FAIRY_SH", name:"Stray Fairy (Snowhead Temple)"},
  {key:"MM_STRAY_FAIRY_ST", name:"Stray Fairy (Stone Tower Temple)"},
  {key:"MM_STRAY_FAIRY_TOWN", name:"Stray Fairy (Clocktown)"},
  {key:"MM_STRAY_FAIRY_WF", name:"Stray Fairy (Woodfall Temple)"},
  {key:"MM_SWORD", name:"Progressive Sword (MM)"},
  {key:"MM_WALLET", name:"Progressive Wallet (MM)"},
  {key:"OOT_ARROWS_10", name:"10 Arrows (OOT)"},
  {key:"OOT_ARROWS_30", name:"30 Arrows (OOT)"},
  {key:"OOT_ARROWS_5", name:"5 Arrows (OOT)"},
  {key:"OOT_ARROW_FIRE", name:"Fire Arrows (OOT)"},
  {key:"OOT_ARROW_ICE", name:"Ice Arrows (OOT)"},
  {key:"OOT_ARROW_LIGHT", name:"Light Arrows (OOT)"},
  {key:"OOT_BOMBCHU_10", name:"10 Bombchu (OOT)"},
  {key:"OOT_BOMBCHU_20", name:"20 Bombchu (OOT)"},
  {key:"OOT_BOMBCHU_5", name:"5 Bombchu (OOT)"},
  {key:"OOT_BOMB_BAG", name:"Bomb Bag (OoT)"},
  {key:"OOT_BOMBS_10", name:"10 Bombs (OOT)"},
  {key:"OOT_BOMBS_20", name:"20 Bombs (OOT)"},
  {key:"OOT_BOMBS_5", name:"5 Bombs (OOT)"},
  {key:"OOT_BOOMERANG", name:"Boomerang"},
  {key:"OOT_BOOTS_HOVER", name:"Hover Boots"},
  {key:"OOT_BOOTS_IRON", name:"Iron Boots"},
  {key:"OOT_BOSS_KEY_FIRE", name:"Boss Key (Fire Temple)"},
  {key:"OOT_BOSS_KEY_FOREST", name:"Boss Key (Forest Temple)"},
  {key:"OOT_BOSS_KEY_SHADOW", name:"Boss Key (Shadow Temple)"},
  {key:"OOT_BOSS_KEY_SPIRIT", name:"Boss Key (Spirit Temple)"},
  {key:"OOT_BOSS_KEY_WATER", name:"Boss Key (Water Temple)"},
  {key:"OOT_BOW", name:"Bow (OOT)"},
  {key:"OOT_BROKEN_GORON_SWORD", name:"Broken Goron Sword"},
  {key:"OOT_CHICKEN", name:"Chicken"},
  {key:"OOT_CLAIM_CHECK", name:"Claim Check"},
  {key:"OOT_COJIRO", name:"Cojiro"},
  {key:"OOT_COMPASS_BOTW", name:"Compass (Bottom of the Well)"},
  {key:"OOT_COMPASS_DC", name:"Compass (Dodongo's Cavern)"},
  {key:"OOT_COMPASS_DT", name:"Compass (Deku Tree)"},
  {key:"OOT_COMPASS_FIRE", name:"Compass (Fire Temple)"},
  {key:"OOT_COMPASS_FOREST", name:"Compass (Forest Temple)"},
  {key:"OOT_COMPASS_IC", name:"Compass (Ice Cavern)"},
  {key:"OOT_COMPASS_JJ", name:"Compass (Jabu Jabu's Belly)"},
  {key:"OOT_COMPASS_SHADOW", name:"Compass (Shadow Temple)"},
  {key:"OOT_COMPASS_SPIRIT", name:"Compass (Spirit Temple)"},
  {key:"OOT_COMPASS_WATER", name:"Compass (Water Temple)"},
  {key:"OOT_DEFENSE_UPGRADE", name:"Double Defense (OOT)"},
  {key:"OOT_EMPTY_BOTTLE", name:"Bottle - Empty (OOT)"},
  {key:"OOT_EYEBALL_FROG", name:"Eyeball Frog"},
  {key:"OOT_EYE_DROPS", name:"Eye Drops"},
  {key:"OOT_GERUDO_CARD", name:"Gerudo Card"},
  {key:"OOT_GS_TOKEN", name:"Golden Skulltula Token"},
  {key:"OOT_HAMMER", name:"Hammer"},
  {key:"OOT_HEART_CONTAINER", name:"Heart Container (OOT)"},
  {key:"OOT_HEART_PIECE", name:"Piece of Heart (OOT)"},
  {key:"OOT_HOOKSHOT", name:"Progressive Hookshot (OOT)"},
  {key:"OOT_ICE_TRAP", name:"Ice Trap (OOT)"},
  {key:"OOT_LENS", name:"Lens of Truth (OOT)"},
  {key:"OOT_MAGIC_BEAN", name:"Magic Beans (OOT)"},
  {key:"OOT_MAGIC_UPGRADE", name:"Magic Upgrade (OOT)"},
  {key:"OOT_MAP_BOTW", name:"Map (Bottom of the Well)"},
  {key:"OOT_MAP_DC", name:"Map (Dodongo's Cavern)"},
  {key:"OOT_MAP_DT", name:"Map (Deku Tree)"},
  {key:"OOT_MAP_FIRE", name:"Map (Fire Temple)"},
  {key:"OOT_MAP_FOREST", name:"Map (Forest Temple)"},
  {key:"OOT_MAP_IC", name:"Map (Ice Cavern)"},
  {key:"OOT_MAP_JJ", name:"Map (Jabu Jabu's Belly)"},
  {key:"OOT_MAP_SHADOW", name:"Map (Shadow Temple)"},
  {key:"OOT_MAP_SPIRIT", name:"Map (Spirit Temple)"},
  {key:"OOT_MAP_WATER", name:"Map (Water Temple)"},
  {key:"OOT_MASK_BUNNY", name:"Bunny Hood (OOT)"},
  {key:"OOT_MASK_GERUDO", name:"Gerudo Mask"},
  {key:"OOT_MASK_GORON", name:"Goron Mask (OOT)"},
  {key:"OOT_MASK_KEATON", name:"Keaton Mask (OOT)"},
  {key:"OOT_MASK_SKULL", name:"Skull Mask"},
  {key:"OOT_MASK_SPOOKY", name:"Spooky Mask"},
  {key:"OOT_MASK_TRUTH", name:"Mask of Truth (OOT)"},
  {key:"OOT_MASK_ZORA", name:"Zora Mask (OOT)"},
  {key:"OOT_MEDALLION_FIRE", name:"Fire Medallion"},
  {key:"OOT_MEDALLION_FOREST", name:"Forest Medallion"},
  {key:"OOT_MEDALLION_LIGHT", name:"Light Medallion"},
  {key:"OOT_MEDALLION_SHADOW", name:"Shadow Medallion"},
  {key:"OOT_MEDALLION_SPIRIT", name:"Spirit Medallion"},
  {key:"OOT_MEDALLION_WATER", name:"Water Medallion"},
  {key:"OOT_MILK_BOTTLE", name:"Bottle - Milk (OOT)"},
  {key:"OOT_NUTS_10", name:"10 Deku Nuts"},
  {key:"OOT_NUT_UPGRADE", name:"Deku Nut Upgrade"},
  {key:"OOT_OCARINA", name:"Progressive Ocarina (OOT)"},
  {key:"OOT_ODD_MUSHROOM", name:"Odd Mushroom"},
  {key:"OOT_ODD_POTION", name:"Odd Potion"},
  {key:"OOT_POACHER_SAW", name:"Poacher's Saw"},
  {key:"OOT_POCKET_CUCCO", name:"Pocket Cucco"},
  {key:"OOT_PRESCRIPTION", name:"Prescription"},
  {key:"OOT_RECOVERY_HEART", name:"Recovery Heart (OOT)"},
  {key:"OOT_RUPEE_BLUE", name:"Blue Rupee (OOT)"},
  {key:"OOT_RUPEE_GREEN", name:"Green Rupee (OOT)"},
  {key:"OOT_RUPEE_HUGE", name:"Gold Rupee (OOT)"},
  {key:"OOT_RUPEE_PURPLE", name:"Purple Rupee (OOT)"},
  {key:"OOT_RUPEE_RED", name:"Red Rupee (OOT)"},
  {key:"OOT_RUTO_LETTER", name:"Ruto's Letter"},
  {key:"OOT_SCALE", name:"Progressive Scale"},
  {key:"OOT_SHIELD_DEKU", name:"Deku Shield"},
  {key:"OOT_SHIELD_HYLIAN", name:"Hylian Shield"},
  {key:"OOT_SHIELD_MIRROR", name:"Mirror Shield"},
  {key:"OOT_SLINGSHOT", name:"Slingshot"},
  {key:"OOT_SMALL_KEY_BOTW", name:"Small Key (Bottom of the Well)"},
  {key:"OOT_SMALL_KEY_FIRE", name:"Small Key (Fire Temple)"},
  {key:"OOT_SMALL_KEY_FOREST", name:"Small Key (Forest Temple)"},
  {key:"OOT_SMALL_KEY_GANON", name:"Small Key (Ganon's Castle)"},
  {key:"OOT_SMALL_KEY_GF", name:"Small Key (Gerudo Fortress)"},
  {key:"OOT_SMALL_KEY_GTG", name:"Small Key (Gerudo Training Ground)"},
  {key:"OOT_SMALL_KEY_SHADOW", name:"Small Key (Shadow Temple)"},
  {key:"OOT_SMALL_KEY_SPIRIT", name:"Small Key (Spirit Temple)"},
  {key:"OOT_SMALL_KEY_WATER", name:"Small Key (Water Temple)"},
  {key:"OOT_SONG_EPONA", name:"Epona's Song (OOT)"},
  {key:"OOT_SONG_SARIA", name:"Saria's Song"},
  {key:"OOT_SONG_STORMS", name:"Song of Storms (OOT)"},
  {key:"OOT_SONG_SUN", name:"Sun's Song"},
  {key:"OOT_SONG_TIME", name:"Song of Time (OOT)"},
  {key:"OOT_SONG_TP_FIRE", name:"Bolero of Fire"},
  {key:"OOT_SONG_TP_FOREST", name:"Minuet of Forest"},
  {key:"OOT_SONG_TP_LIGHT", name:"Prelude of Light"},
  {key:"OOT_SONG_TP_SHADOW", name:"Nocturne of Shadow"},
  {key:"OOT_SONG_TP_SPIRIT", name:"Requiem of Spirit"},
  {key:"OOT_SONG_TP_WATER", name:"Serenade of Water"},
  {key:"OOT_SONG_ZELDA", name:"Zelda's Lullaby"},
  {key:"OOT_SPELL_FIRE", name:"Din's Fire"},
  {key:"OOT_SPELL_LOVE", name:"Nayru's Love"},
  {key:"OOT_SPELL_WIND", name:"Farore's Wind"},
  {key:"OOT_STICK_UPGRADE", name:"Deku Stick Upgrade"},
  {key:"OOT_STONE_EMERALD", name:"Kokiri Emerald"},
  {key:"OOT_STONE_OF_AGONY", name:"Stone of Agony"},
  {key:"OOT_STONE_RUBY", name:"Goron Ruby"},
  {key:"OOT_STONE_SAPPHIRE", name:"Zora Sapphire"},
  {key:"OOT_STRENGTH", name:"Progressive Strength"},
  {key:"OOT_SWORD_GORON", name:"Progressive Goron Sword"},
  {key:"OOT_SWORD_KOKIRI", name:"Kokiri Sword (OOT)"},
  {key:"OOT_SWORD_MASTER", name:"Master Sword"},
  {key:"OOT_TUNIC_GORON", name:"Goron Tunic"},
  {key:"OOT_TUNIC_ZORA", name:"Zora Tunic"},
  {key:"OOT_WALLET", name:"Progressive Wallet (OOT)"},
  {key:"OOT_ZELDA_LETTER", name:"Zelda's Letter"},
]

export const findFrontendItemName = (backendName: string) => {
  const res = FRONTENDNAMES.filter((entry) => { return entry.key === backendName;});
  if (res.length === 0) {
    return backendName;
  }
  else {
    return res[0].name;
  }
};