#ifndef OCARINA_H
#define OCARINA_H

#include <combo.h>

int Ocarina_CheckSongEventSong(u16 ocarinaSong, int songEventId);
void Ocarina_ClearLastPlayedSong(PlayState* play);
void comboSpawnCustomSongTags(PlayState* play);

typedef enum OcarinaSongActionId {
    /* 0x00 */ OCARINA_ACTION_0, // acts like free play but never set
    /* 0x01 */ OCARINA_ACTION_FREE_PLAY,
    /* 0x02 */ OCARINA_ACTION_DEMONSTRATE_SONATA, // Song demonstrated/previewed by another actor/teacher
    /* 0x03 */ OCARINA_ACTION_DEMONSTRATE_GORON_LULLABY,
    /* 0x04 */ OCARINA_ACTION_DEMONSTRATE_NEW_WAVE,
    /* 0x05 */ OCARINA_ACTION_DEMONSTRATE_ELEGY,
    /* 0x06 */ OCARINA_ACTION_DEMONSTRATE_OATH,
    /* 0x07 */ OCARINA_ACTION_DEMONSTRATE_SARIAS,
    /* 0x08 */ OCARINA_ACTION_DEMONSTRATE_TIME,
    /* 0x09 */ OCARINA_ACTION_DEMONSTRATE_HEALING,
    /* 0x0A */ OCARINA_ACTION_DEMONSTRATE_EPONAS,
    /* 0x0B */ OCARINA_ACTION_DEMONSTRATE_SOARING,
    /* 0x0C */ OCARINA_ACTION_DEMONSTRATE_STORMS,
    /* 0x0D */ OCARINA_ACTION_DEMONSTRATE_SUNS,
    /* 0x0E */ OCARINA_ACTION_DEMONSTRATE_INVERTED_TIME,
    /* 0x0F */ OCARINA_ACTION_DEMONSTRATE_DOUBLE_TIME,
    /* 0x10 */ OCARINA_ACTION_DEMONSTRATE_GORON_LULLABY_INTRO,
    /* 0x11 */ OCARINA_ACTION_11,
    /* 0x12 */ OCARINA_ACTION_PROMPT_SONATA, // User plays back song through inputing 1 note at a time, as a tutorial. Each note is verified.
    /* 0x13 */ OCARINA_ACTION_PROMPT_GORON_LULLABY,
    /* 0x14 */ OCARINA_ACTION_PROMPT_NEW_WAVE,
    /* 0x15 */ OCARINA_ACTION_PROMPT_ELEGY,
    /* 0x16 */ OCARINA_ACTION_PROMPT_OATH,
    /* 0x17 */ OCARINA_ACTION_PROMPT_SARIAS,
    /* 0x18 */ OCARINA_ACTION_PROMPT_TIME,
    /* 0x19 */ OCARINA_ACTION_PROMPT_HEALING,
    /* 0x1A */ OCARINA_ACTION_PROMPT_EPONAS,
    /* 0x1B */ OCARINA_ACTION_PROMPT_SOARING,
    /* 0x1C */ OCARINA_ACTION_PROMPT_STORMS,
    /* 0x1D */ OCARINA_ACTION_PROMPT_SUNS,
    /* 0x1E */ OCARINA_ACTION_PROMPT_INVERTED_TIME,
    /* 0x1F */ OCARINA_ACTION_PROMPT_DOUBLE_TIME,
    /* 0x20 */ OCARINA_ACTION_PROMPT_GORON_LULLABY_INTRO,
    /* 0x21 */ OCARINA_ACTION_21,
    /* 0x22 */ OCARINA_ACTION_CHECK_SONATA, // Once the entire song is played, checks for a specific song. Broken as playing any dungeon song will softlock.
    /* 0x23 */ OCARINA_ACTION_CHECK_GORON_LULLABY,
    /* 0x24 */ OCARINA_ACTION_CHECK_NEW_WAVE,
    /* 0x25 */ OCARINA_ACTION_CHECK_ELEGY,
    /* 0x26 */ OCARINA_ACTION_CHECK_OATH,
    /* 0x27 */ OCARINA_ACTION_CHECK_SARIAS,
    /* 0x28 */ OCARINA_ACTION_CHECK_TIME,
    /* 0x29 */ OCARINA_ACTION_CHECK_HEALING,
    /* 0x2A */ OCARINA_ACTION_CHECK_EPONAS,
    /* 0x2B */ OCARINA_ACTION_CHECK_SOARING,
    /* 0x2C */ OCARINA_ACTION_CHECK_STORMS,
    /* 0x2D */ OCARINA_ACTION_CHECK_SUNS,
    /* 0x2E */ OCARINA_ACTION_CHECK_INVERTED_TIME,
    /* 0x2F */ OCARINA_ACTION_CHECK_DOUBLE_TIME,
    /* 0x30 */ OCARINA_ACTION_CHECK_GORON_LULLABY_INTRO,
    /* 0x31 */ OCARINA_ACTION_CHECK_SCARECROW_SPAWN, // TODO: Verify (may include more)
    /* 0x32 */ OCARINA_ACTION_FREE_PLAY_DONE,
    /* 0x33 */ OCARINA_ACTION_SCARECROW_LONG_RECORDING,
    /* 0x34 */ OCARINA_ACTION_SCARECROW_LONG_DEMONSTRATION,
    /* 0x35 */ OCARINA_ACTION_SCARECROW_SPAWN_RECORDING,
    /* 0x36 */ OCARINA_ACTION_SCARECROW_SPAWN_DEMONSTRATION,
    /* 0x37 */ OCARINA_ACTION_37,
    /* 0x38 */ OCARINA_ACTION_CHECK_NOTIME,
    /* 0x39 */ OCARINA_ACTION_CHECK_NOTIME_DONE,
    /* 0x3A */ OCARINA_ACTION_3A, // Monkey Instrument Prompt
    /* 0x3B */ OCARINA_ACTION_3B,
    /* 0x3C */ OCARINA_ACTION_3C,
    /* 0x3D */ OCARINA_ACTION_DEMONSTRATE_EVAN_PART1_FIRST_HALF, // Evan Part 1 demonstrate first half (Japa)
    /* 0x3E */ OCARINA_ACTION_DEMONSTRATE_EVAN_PART2_FIRST_HALF, // Evan Part 2 demonstrate first half (Japa)
    /* 0x3F */ OCARINA_ACTION_DEMONSTRATE_EVAN_PART1_SECOND_HALF, // Evan Part 1 demonstrate second half (Diary)
    /* 0x40 */ OCARINA_ACTION_DEMONSTRATE_EVAN_PART2_SECOND_HALF, // Evan Part 2 demonstrate second half (Diary)
    /* 0x41 */ OCARINA_ACTION_PROMPT_EVAN_PART1_SECOND_HALF, // Evan Part 1 prompt second half (Japa)
    /* 0x42 */ OCARINA_ACTION_PROMPT_EVAN_PART2_SECOND_HALF, // Evan Part 2 prompt second half (Japa)
    /* 0x43 */ OCARINA_ACTION_PROMPT_WIND_FISH_HUMAN,
    /* 0x44 */ OCARINA_ACTION_PROMPT_WIND_FISH_GORON,
    /* 0x45 */ OCARINA_ACTION_PROMPT_WIND_FISH_ZORA,
    /* 0x46 */ OCARINA_ACTION_PROMPT_WIND_FISH_DEKU,
    /* 0x47 */ OCARINA_ACTION_TIMED_PROMPT_SONATA, // Playing back a particular song, but must also time the notes properly. Not fully implemented
    /* 0x48 */ OCARINA_ACTION_TIMED_PROMPT_GORON_LULLABY,
    /* 0x49 */ OCARINA_ACTION_TIMED_PROMPT_NEW_WAVE,
    /* 0x4A */ OCARINA_ACTION_TIMED_PROMPT_ELEGY,
    /* 0x4B */ OCARINA_ACTION_TIMED_PROMPT_OATH,
    /* 0x4C */ OCARINA_ACTION_TIMED_PROMPT_SARIAS,
    /* 0x4D */ OCARINA_ACTION_TIMED_PROMPT_TIME,
    /* 0x4E */ OCARINA_ACTION_TIMED_PROMPT_HEALING,
    /* 0x4F */ OCARINA_ACTION_TIMED_PROMPT_EPONAS,
    /* 0x50 */ OCARINA_ACTION_TIMED_PROMPT_SOARING,
    /* 0x51 */ OCARINA_ACTION_TIMED_PROMPT_STORMS
} OcarinaSongActionId;

#endif
