packages:
  - packages/*

catalog:
  '@types/lodash-es': ^4.17.12
  lodash-es: ^4.18.1
  yaml: ^2.8.3
  '@preact/preset-vite': ^2.10.5
  '@tailwindcss/vite': ^4.2.2
  tailwindcss: ^4.2.2
  preact: ^10.29.1
  react-icons: ^5.6.0
  type-fest: ^5.5.0

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - microtime
  - netlify-cli
  - nx
  - sharp
  - unix-dgram
  - yaz0
