import type { ItemID } from '@ootmm/core';
import { Item, Items } from '@ootmm/core';

const ITEM_NAMES: {[k in ItemID]: string} = {
  [Items.MM_ARROW_FIRE]: "Fire Arrows (MM)",
  [Items.MM_ARROW_ICE]: "Ice Arrows (MM)",
  [Items.MM_ARROW_LIGHT]: "Light Arrows (MM)",
  [Items.MM_ARROWS_10]: "10 Arrows (MM)",
  [Items.MM_ARROWS_30]: "30 Arrows (MM)",
  [Items.MM_ARROWS_40]: "40 Arrows (MM)",
  [Items.MM_DEKU_SEEDS_30]: "30 Deku Seeds (MM)",
  [Items.MM_DEKU_SEEDS_5]: "5 Deku Seeds (MM)",
  [Items.MM_BOMB_BAG]: "Bomb Bag (MM)",
  [Items.MM_BOMB]: "Bomb (MM)",
  [Items.MM_BOMBCHU_10]: "10 Bombchu (MM)",
  [Items.MM_BOMBCHU_20]: "20 Bombchu (MM)",
  [Items.MM_BOMBCHU_5]: "5 Bombchu (MM)",
  [Items.MM_BOMBCHU]: "1 Bombchu (MM)",
  [Items.MM_BOMBER_NOTEBOOK]: "Bombers' Notebook",
  [Items.MM_BOMBS_10]: "10 Bombs (MM)",
  [Items.MM_BOMBS_20]: "20 Bombs (MM)",
  [Items.MM_BOMBS_30]: "30 Bombs (MM)",
  [Items.MM_BOMBS_5]: "5 Bombs (MM)",
  [Items.MM_BOSS_KEY_GB]: "Boss Key (Great Bay Temple)",
  [Items.MM_BOSS_KEY_SH]: "Boss Key (Snowhead Temple)",
  [Items.MM_BOSS_KEY_ST]: "Boss Key (Stone Tower Temple)",
  [Items.MM_BOSS_KEY_WF]: "Boss Key (Woodfall Temple)",
  [Items.MM_BOTTLE_CHATEAU]: "Bottle of Chateau Romani",
  [Items.MM_BOTTLE_EMPTY]: "Empty Bottle (MM)",
  [Items.MM_BOTTLE_MILK]: "Bottle of Milk (MM)",
  [Items.MM_BOTTLE_POTION_RED]: "Bottle of Red Potion (MM)",
  [Items.MM_BOTTLE_POTION_GREEN]: "Bottle of Green Potion (MM)",
  [Items.MM_BOTTLE_POTION_BLUE]: "Bottle of Blue Potion (MM)",
  [Items.OOT_BOTTLE_POTION_RED]: "Bottle of Red Potion (OoT)",
  [Items.OOT_BOTTLE_POTION_GREEN]: "Bottle of Green Potion (OoT)",
  [Items.OOT_BOTTLE_POTION_BLUE]: "Bottle of Blue Potion (OoT)",
  [Items.MM_BOTTLED_GOLD_DUST]: "Bottle of Gold Dust",
  [Items.MM_BOW]: "Hero's Bow (MM)",
  [Items.MM_BUGS]: "Bugs (MM)",
  [Items.MM_CHATEAU]: "Chateau Romani Refill (MM)",
  [Items.MM_COMPASS_GB]: "Compass (Great Bay Temple)",
  [Items.MM_COMPASS_SH]: "Compass (Snowhead Temple)",
  [Items.MM_COMPASS_ST]: "Compass (Stone Tower Temple)",
  [Items.MM_COMPASS_WF]: "Compass (Woodfall Temple)",
  [Items.MM_DEED_LAND]: "Land Title Deed",
  [Items.MM_DEED_MOUNTAIN]: "Mountain Title Deed",
  [Items.MM_DEED_OCEAN]: "Ocean Title Deed",
  [Items.MM_DEED_SWAMP]: "Swamp Title Deed",
  [Items.MM_DEFENSE_UPGRADE]: "Double Defense (MM)",
  [Items.MM_FAIRY]: "Fairy (MM)",
  [Items.MM_FISH]: "Fish (MM)",
  [Items.MM_GREAT_FAIRY_SWORD]: "Great Fairy's Sword (MM)",
  [Items.MM_GS_TOKEN_OCEAN]: "Ocean Skulltula Token",
  [Items.MM_GS_TOKEN_SWAMP]: "Swamp Skulltula Token",
  [Items.MM_HEART_CONTAINER]: "Heart Container (MM)",
  [Items.MM_HEART_PIECE]: "Piece of Heart (MM)",
  [Items.MM_HOOKSHOT]: "Hookshot (MM)",
  [Items.MM_KEY_RING_GB]: "Key Ring (Great Bay)",
  [Items.MM_KEY_RING_SH]: "Key Ring (Snowhead)",
  [Items.MM_KEY_RING_ST]: "Key Ring (Stone Tower)",
  [Items.MM_KEY_RING_WF]: "Key Ring (Woodfall)",
  [Items.MM_LENS]: "Lens of Truth (MM)",
  [Items.MM_LETTER_TO_KAFEI]: "Letter to Kafei",
  [Items.MM_LETTER_TO_MAMA]: "Letter to Mama",
  [Items.MM_MAGIC_BEAN]: "Magic Bean (MM)",
  [Items.MM_MAGIC_UPGRADE]: "Magic Upgrade (MM)",
  [Items.MM_MAP_GB]: "Map (Great Bay Temple)",
  [Items.MM_MAP_SH]: "Map (Snowhead Temple)",
  [Items.MM_MAP_ST]: "Map (Stone Tower Temple)",
  [Items.MM_MAP_WF]: "Map (Woodfall Temple)",
  [Items.MM_MASK_ALL_NIGHT]: "All-Night Mask",
  [Items.MM_MASK_BLAST]: "Blast Mask (MM)",
  [Items.MM_MASK_BREMEN]: "Bremen Mask",
  [Items.MM_MASK_BUNNY]: "Bunny Hood (MM)",
  [Items.MM_MASK_CAPTAIN]: "Captain's Hat",
  [Items.MM_MASK_COUPLE]: "Couple's Mask",
  [Items.MM_MASK_DEKU]: "Deku Mask",
  [Items.MM_MASK_DON_GERO]: "Don Gero's Mask",
  [Items.MM_MASK_FIERCE_DEITY]: "Fierce Deity's Mask",
  [Items.MM_MASK_GARO]: "Garo's Mask",
  [Items.MM_MASK_GERUDO]: "Gerudo Mask (MM)",
  [Items.MM_MASK_GIANT]: "Giant's Mask",
  [Items.MM_MASK_GIBDO]: "Gibdo Mask",
  [Items.MM_MASK_GORON]: "Goron Mask (MM)",
  [Items.MM_MASK_GREAT_FAIRY]: "Great Fairy's Mask",
  [Items.MM_MASK_KAFEI]: "Kafei's Mask",
  [Items.MM_MASK_KAMARO]: "Kamaro's Mask (MM)",
  [Items.MM_MASK_KEATON]: "Keaton Mask",
  [Items.MM_MASK_POSTMAN]: "Postman's Hat",
  [Items.MM_MASK_ROMANI]: "Romani's Mask",
  [Items.MM_MASK_SCENTS]: "Mask of Scents",
  [Items.MM_MASK_SKULL]: "Skull Mask (MM)",
  [Items.MM_MASK_SPOOKY]: "Spooky Mask (MM)",
  [Items.MM_MASK_ADULT]: "Adult Mask",
  [Items.MM_MASK_STONE]: "Stone Mask (MM)",
  [Items.MM_MASK_TROUPE_LEADER]: "Circus Leader's Mask",
  [Items.MM_MASK_TRUTH]: "Mask of Truth (MM)",
  [Items.MM_MASK_ZORA]: "Zora Mask (MM)",
  [Items.MM_MILK]: "Romani Milk",
  [Items.MM_MOON_TEAR]: "Moon's Tear",
  [Items.MM_NUT]: "Nut (MM)",
  [Items.MM_NUTS_10]: "10 Deku Nuts (MM)",
  [Items.MM_NUTS_5]: "5 Deku Nuts (MM)",
  [Items.MM_OCARINA]: "Ocarina (MM)",
  [Items.MM_OWL_CLOCK_TOWN]: "Owl Statue (Clock Town)",
  [Items.MM_OWL_GREAT_BAY]: "Owl Statue (Great Bay)",
  [Items.MM_OWL_IKANA_CANYON]: "Owl Statue (Ikana Canyon)",
  [Items.MM_OWL_MILK_ROAD]: "Owl Statue (Milk Road)",
  [Items.MM_OWL_MOUNTAIN_VILLAGE]: "Owl Statue (Mountain Village)",
  [Items.MM_OWL_SNOWHEAD]: "Owl Statue (Snowhead)",
  [Items.MM_OWL_SOUTHERN_SWAMP]: "Owl Statue (Southern Swamp)",
  [Items.MM_OWL_STONE_TOWER]: "Owl Statue (Stone Tower)",
  [Items.MM_OWL_WOODFALL]: "Owl Statue (Woodfall)",
  [Items.MM_OWL_ZORA_CAPE]: "Owl Statue (Zora Cape)",
  [Items.MM_PENDANT_OF_MEMORIES]: "Pendant of Memories",
  [Items.MM_PICTOGRAPH_BOX]: "Pictograph Box",
  [Items.MM_POTION_BLUE]: "Blue Potion (MM)",
  [Items.MM_POTION_GREEN]: "Green Potion (MM)",
  [Items.MM_POTION_RED]: "Red Potion (MM)",
  [Items.MM_POWDER_KEG]: "Powder Keg (MM)",
  [Items.MM_RECOVERY_HEART]: "Recovery Heart (MM)",
  [Items.MM_REMAINS_GOHT]: "Goht's Remains",
  [Items.MM_REMAINS_GYORG]: "Gyorg's Remains",
  [Items.MM_REMAINS_ODOLWA]: "Odolwa's Remains",
  [Items.MM_REMAINS_TWINMOLD]: "Twinmold's Remains",
  [Items.MM_ROOM_KEY]: "Room Key",
  [Items.MM_RUPEE_BLUE]: "Blue Rupee (MM)",
  [Items.MM_RUPEE_GOLD]: "Gold Rupee (MM)",
  [Items.MM_RUPEE_GREEN]: "Green Rupee (MM)",
  [Items.MM_RUPEE_PURPLE]: "Purple Rupee (MM)",
  [Items.MM_RUPEE_RED]: "Red Rupee (MM)",
  [Items.MM_RUPEE_SILVER]: "Silver Rupee (MM)",
  [Items.MM_SHIELD_DEKU]: "Deku Shield (MM)",
  [Items.MM_SHIELD_HERO]: "Hero's Shield",
  [Items.MM_SHIELD_MIRROR]: "Mirror Shield (MM)",
  [Items.MM_SHIELD]: "Progressive Shield (MM)",
  [Items.MM_SKELETON_KEY]: "Skeleton Key (MM)",
  [Items.MM_SMALL_KEY_GB]: "Small Key (Great Bay Temple)",
  [Items.MM_SMALL_KEY_SH]: "Small Key (Snowhead Temple)",
  [Items.MM_SMALL_KEY_ST]: "Small Key (Stone Tower Temple)",
  [Items.MM_SMALL_KEY_WF]: "Small Key (Woodfall Temple)",
  [Items.MM_SONG_AWAKENING]: "Sonata of Awakening (MM)",
  [Items.MM_SONG_EMPTINESS]: "Elegy of Emptiness (MM)",
  [Items.MM_SONG_EPONA]: "Epona's Song (MM)",
  [Items.MM_SONG_GORON_HALF]: "Progressive Goron Lullaby (MM)",
  [Items.MM_SONG_GORON]: "Goron Lullaby (MM)",
  [Items.MM_SONG_HEALING]: "Song of Healing (MM)",
  [Items.MM_SONG_ORDER]: "Oath to Order (MM)",
  [Items.MM_SONG_SOARING]: "Song of Soaring (MM)",
  [Items.MM_SONG_STORMS]: "Song of Storms (MM)",
  [Items.MM_SONG_SARIA]: "Saria's Song (MM)",
  [Items.MM_SONG_SUN]: "Sun's Song (MM)",
  [Items.MM_SONG_TP_FIRE]: "Bolero of Fire (MM)",
  [Items.MM_SONG_TP_FOREST]: "Minuet of Forest (MM)",
  [Items.MM_SONG_TP_LIGHT]: "Prelude of Light (MM)",
  [Items.MM_SONG_TP_SHADOW]: "Nocturne of Shadow (MM)",
  [Items.MM_SONG_TP_SPIRIT]: "Requiem of Spirit (MM)",
  [Items.MM_SONG_TP_WATER]: "Serenade of Water (MM)",
  [Items.MM_SONG_ZELDA]: "Zelda's Lullaby (MM)",
  [Items.MM_SONG_TIME]: "Song of Time (MM)",
  [Items.MM_SONG_ZORA]: "New Wave Bossa Nova (MM)",
  [Items.MM_SOUL_ENEMY_ARMOS]: "Soul of Armos (MM)",
  [Items.MM_SOUL_ENEMY_BAD_BAT]: "Soul of Bad Bats",
  [Items.MM_SOUL_ENEMY_BEAMOS]: "Soul of Beamos (MM)",
  [Items.MM_SOUL_ENEMY_BIO_BABA]: "Soul of Bio Babas",
  [Items.MM_SOUL_ENEMY_BOE]: "Soul of Boes",
  [Items.MM_SOUL_ENEMY_BUBBLE]: "Soul of Bubbles (MM)",
  [Items.MM_SOUL_ENEMY_CAPTAIN_KEETA]: "Soul of Captain Keeta",
  [Items.MM_SOUL_ENEMY_CHUCHU]: "Soul of Chuchus",
  [Items.MM_SOUL_ENEMY_DEEP_PYTHON]: "Soul of Deep Pythons",
  [Items.MM_SOUL_ENEMY_DEKU_BABA]: "Soul of Deku Babas (MM)",
  [Items.MM_SOUL_ENEMY_DEKU_SCRUB]: "Soul of Deku Scrubs (MM)",
  [Items.MM_SOUL_ENEMY_DEXIHAND]: "Soul of Dexihands",
  [Items.MM_SOUL_ENEMY_DODONGO]: "Soul of Dodongos (MM)",
  [Items.MM_SOUL_ENEMY_DRAGONFLY]: "Soul of Dragonflies",
  [Items.MM_SOUL_ENEMY_EENO]: "Soul of Eenoes",
  [Items.MM_SOUL_ENEMY_EYEGORE]: "Soul of Eyegores",
  [Items.MM_SOUL_ENEMY_FLOORMASTER]: "Soul of Floormasters (MM)",
  [Items.MM_SOUL_ENEMY_FLYING_POT]: "Soul of Flying Pots (MM)",
  [Items.MM_SOUL_ENEMY_FREEZARD]: "Soul of Freezards (MM)",
  [Items.MM_SOUL_ENEMY_GARO]: "Soul of Garo",
  [Items.MM_SOUL_ENEMY_GEKKO]: "Soul of Gekkos",
  [Items.MM_SOUL_BOSS_GOHT]: "Soul of Goht",
  [Items.MM_SOUL_ENEMY_GOMESS]: "Soul of Gomess",
  [Items.MM_SOUL_ENEMY_GUAY]: "Soul of Guays (MM)",
  [Items.MM_SOUL_BOSS_GYORG]: "Soul of Gyorg",
  [Items.MM_SOUL_ENEMY_HIPLOOP]: "Soul of Hiploops",
  [Items.MM_SOUL_BOSS_IGOS]: "Soul of Igos",
  [Items.MM_SOUL_ENEMY_IRON_KNUCKLE]: "Soul of Iron Knuckles (MM)",
  [Items.MM_SOUL_ENEMY_KEESE]: "Soul of Keese (MM)",
  [Items.MM_SOUL_ENEMY_LEEVER]: "Soul of Leevers (MM)",
  [Items.MM_SOUL_ENEMY_LIKE_LIKE]: "Soul of Like Likes (MM)",
  [Items.MM_SOUL_ENEMY_LIZALFOS_DINOLFOS]: "Soul of Lizalfos/Dinolfos (MM)",
  [Items.MM_SOUL_ENEMY_NEJIRON]: "Soul of Nejirons",
  [Items.MM_SOUL_ENEMY_OCTOROK]: "Soul of Octoroks (MM)",
  [Items.MM_SOUL_BOSS_ODOLWA]: "Soul of Odolwa",
  [Items.MM_SOUL_ENEMY_PEAHAT]: "Soul of Peahats (MM)",
  [Items.MM_SOUL_ENEMY_REAL_BOMBCHU]: "Soul of Real Bombchu",
  [Items.MM_SOUL_ENEMY_REDEAD_GIBDO]: "Soul of ReDeads/Gibdos (MM)",
  [Items.MM_SOUL_ENEMY_SHELL_BLADE]: "Soul of Shell Blades (MM)",
  [Items.MM_SOUL_ENEMY_SKULLFISH]: "Soul of Skullfish (MM)",
  [Items.MM_SOUL_ENEMY_SKULLTULA]: "Soul of Skulltulas (MM)",
  [Items.MM_SOUL_ENEMY_SKULLWALLTULA]: "Soul of Skullwalltulas (MM)",
  [Items.MM_SOUL_ENEMY_SNAPPER]: "Soul of Snappers",
  [Items.MM_SOUL_ENEMY_STALCHILD]: "Soul of Stalchildren (MM)",
  [Items.MM_SOUL_ENEMY_TAKKURI]: "Soul of Takkuri",
  [Items.MM_SOUL_ENEMY_TEKTITE]: "Soul of Tektites (MM)",
  [Items.MM_SOUL_BOSS_TWINMOLD]: "Soul of Twinmold",
  [Items.MM_SOUL_ENEMY_WALLMASTER]: "Soul of Wallmasters (MM)",
  [Items.MM_SOUL_ENEMY_WART]: "Soul of Warts",
  [Items.MM_SOUL_ENEMY_WIZZROBE]: "Soul of Wizzrobes",
  [Items.MM_SOUL_ENEMY_WOLFOS]: "Soul of Wolfos (MM)",
  [Items.MM_SPIN_UPGRADE]: "Spin Attack Upgrade (MM)",
  [Items.OOT_SPIN_UPGRADE]: "Spin Attack Upgrade (OoT)",
  [Items.SHARED_SPIN_UPGRADE]: "Spin Attack Upgrade",
  [Items.MM_STICK]: "Deku Stick (MM)",
  [Items.MM_STRAY_FAIRY_GB]: "Stray Fairy (Great Bay Temple)",
  [Items.MM_STRAY_FAIRY_SH]: "Stray Fairy (Snowhead Temple)",
  [Items.MM_STRAY_FAIRY_ST]: "Stray Fairy (Stone Tower Temple)",
  [Items.MM_STRAY_FAIRY_TOWN]: "Stray Fairy (Clock Town)",
  [Items.MM_STRAY_FAIRY_WF]: "Stray Fairy (Woodfall Temple)",
  [Items.MM_SWORD]: "Progressive Sword (MM)",
  [Items.MM_WALLET]: "Progressive Wallet (MM)",
  [Items.MM_WORLD_MAP_CLOCK_TOWN]: "World Map of Clock Town",
  [Items.MM_WORLD_MAP_GREAT_BAY]: "World Map of Great Bay",
  [Items.MM_WORLD_MAP_ROMANI_RANCH]: "World Map of Ranch",
  [Items.MM_WORLD_MAP_SNOWHEAD]: "World Map of Snowhead",
  [Items.MM_WORLD_MAP_STONE_TOWER]: "World Map of Stone Tower",
  [Items.MM_WORLD_MAP_WOODFALL]: "World Map of Woodfall",
  [Items.OOT_ARROW_FIRE]: "Fire Arrows (OoT)",
  [Items.OOT_ARROW_ICE]: "Ice Arrows (OoT)",
  [Items.OOT_ARROW_LIGHT]: "Light Arrows (OoT)",
  [Items.OOT_ARROWS_10]: "10 Arrows (OoT)",
  [Items.OOT_ARROWS_30]: "30 Arrows (OoT)",
  [Items.OOT_ARROWS_5]: "5 Arrows (OoT)",
  [Items.OOT_BLUE_FIRE]: "Blue Fire",
  [Items.OOT_BOMB_BAG]: "Bomb Bag (OoT)",
  [Items.OOT_BOMB]: "Bomb (OoT)",
  [Items.OOT_BOMBCHU_10]: "10 Bombchu (OoT)",
  [Items.OOT_BOMBCHU_20]: "20 Bombchu (OoT)",
  [Items.OOT_BOMBCHU_5]: "5 Bombchu (OoT)",
  [Items.OOT_BOMBS_10]: "10 Bombs (OoT)",
  [Items.OOT_BOMBS_20]: "20 Bombs (OoT)",
  [Items.OOT_BOMBS_30]: "30 Bombs (OoT)",
  [Items.OOT_BOMBS_5]: "5 Bombs (OoT)",
  [Items.OOT_BOOMERANG]: "Boomerang (OOT)",
  [Items.OOT_BOOTS_HOVER]: "Hover Boots (OoT)",
  [Items.OOT_BOOTS_IRON]: "Iron Boots (OoT)",
  [Items.OOT_BOSS_KEY_FIRE]: "Boss Key (Fire Temple)",
  [Items.OOT_BOSS_KEY_FOREST]: "Boss Key (Forest Temple)",
  [Items.OOT_BOSS_KEY_GANON]: "Boss Key (Ganon's Castle)",
  [Items.OOT_BOSS_KEY_SHADOW]: "Boss Key (Shadow Temple)",
  [Items.OOT_BOSS_KEY_SPIRIT]: "Boss Key (Spirit Temple)",
  [Items.OOT_BOSS_KEY_WATER]: "Boss Key (Water Temple)",
  [Items.OOT_BOTTLE_EMPTY]: "Empty Bottle (OoT)",
  [Items.OOT_BOTTLE_MILK]: "Bottle of Milk (OoT)",
  [Items.OOT_BOW]: "Fairy Bow (OoT)",
  [Items.OOT_BROKEN_GORON_SWORD]: "Broken Goron's Sword",
  [Items.OOT_BUGS]: "Bugs (OoT)",
  [Items.OOT_CHICKEN]: "Chicken",
  [Items.OOT_CLAIM_CHECK]: "Claim Check",
  [Items.OOT_COIN_BLUE]: "Coin (Blue)",
  [Items.OOT_COIN_GREEN]: "Coin (Green)",
  [Items.OOT_COIN_RED]: "Coin (Red)",
  [Items.OOT_COIN_YELLOW]: "Coin (Yellow)",
  [Items.OOT_COJIRO]: "Cojiro",
  [Items.OOT_COMPASS_BOTW]: "Compass (Bottom of the Well)",
  [Items.OOT_COMPASS_DC]: "Compass (Dodongo's Cavern)",
  [Items.OOT_COMPASS_DT]: "Compass (Deku Tree)",
  [Items.OOT_COMPASS_FIRE]: "Compass (Fire Temple)",
  [Items.OOT_COMPASS_FOREST]: "Compass (Forest Temple)",
  [Items.OOT_COMPASS_IC]: "Compass (Ice Cavern)",
  [Items.OOT_COMPASS_JJ]: "Compass (Jabu-Jabu's Belly)",
  [Items.OOT_COMPASS_SHADOW]: "Compass (Shadow Temple)",
  [Items.OOT_COMPASS_SPIRIT]: "Compass (Spirit Temple)",
  [Items.OOT_COMPASS_WATER]: "Compass (Water Temple)",
  [Items.OOT_DEFENSE_UPGRADE]: "Double Defense (OoT)",
  [Items.OOT_DEKU_SEEDS_30]: "30 Deku Seeds",
  [Items.OOT_DEKU_SEEDS_5]: "5 Deku Seeds (OoT)",
  [Items.OOT_EYE_DROPS]: "Eye Drops",
  [Items.OOT_EYEBALL_FROG]: "Eyeball Frog",
  [Items.OOT_FAIRY]: "Fairy (OoT)",
  [Items.OOT_FISH]: "Fish (OoT)",
  [Items.OOT_GERUDO_CARD]: "Gerudo's Membership Card",
  [Items.OOT_GS_TOKEN]: "Gold Skulltula Token",
  [Items.OOT_HAMMER]: "Megaton Hammer (OoT)",
  [Items.OOT_GREAT_FAIRY_SWORD]: "Great Fairy's Sword (OoT)",
  [Items.OOT_HEART_CONTAINER]: "Heart Container (OoT)",
  [Items.OOT_HEART_PIECE]: "Piece of Heart (OoT)",
  [Items.OOT_HOOKSHOT]: "Progressive Hookshot (OoT)",
  [Items.OOT_KEY_RING_BOTW]: "Key Ring (Well)",
  [Items.OOT_KEY_RING_FIRE]: "Key Ring (Fire)",
  [Items.OOT_KEY_RING_FOREST]: "Key Ring (Forest)",
  [Items.OOT_KEY_RING_GANON]: "Key Ring (Ganon)",
  [Items.OOT_KEY_RING_GF]: "Key Ring (Hideout)",
  [Items.OOT_KEY_RING_GTG]: "Key Ring (GTG)",
  [Items.OOT_KEY_RING_TCG]: "Key Ring (Chest Game)",
  [Items.OOT_KEY_RING_SHADOW]: "Key Ring (Shadow)",
  [Items.OOT_KEY_RING_SPIRIT]: "Key Ring (Spirit)",
  [Items.OOT_KEY_RING_WATER]: "Key Ring (Water)",
  [Items.OOT_LENS]: "Lens of Truth (OoT)",
  [Items.OOT_MAGIC_BEAN]: "Magic Beans (OoT)",
  [Items.OOT_MAGIC_UPGRADE]: "Magic Upgrade (OoT)",
  [Items.OOT_MAP_BOTW]: "Map (Bottom of the Well)",
  [Items.OOT_MAP_DC]: "Map (Dodongo's Cavern)",
  [Items.OOT_MAP_DT]: "Map (Deku Tree)",
  [Items.OOT_MAP_FIRE]: "Map (Fire Temple)",
  [Items.OOT_MAP_FOREST]: "Map (Forest Temple)",
  [Items.OOT_MAP_IC]: "Map (Ice Cavern)",
  [Items.OOT_MAP_JJ]: "Map (Jabu-Jabu's Belly)",
  [Items.OOT_MAP_SHADOW]: "Map (Shadow Temple)",
  [Items.OOT_MAP_SPIRIT]: "Map (Spirit Temple)",
  [Items.OOT_MAP_WATER]: "Map (Water Temple)",
  [Items.OOT_MASK_BUNNY]: "Bunny Hood (OoT)",
  [Items.OOT_MASK_GERUDO]: "Gerudo Mask (OoT)",
  [Items.OOT_MASK_GORON]: "Goron Mask (OoT)",
  [Items.OOT_MASK_KEATON]: "Keaton Mask (OoT)",
  [Items.OOT_MASK_SKULL]: "Skull Mask (OoT)",
  [Items.OOT_MASK_SPOOKY]: "Spooky Mask (OoT)",
  [Items.OOT_MASK_TRUTH]: "Mask of Truth (OoT)",
  [Items.OOT_MASK_ZORA]: "Zora Mask (OoT)",
  [Items.OOT_MEDALLION_FIRE]: "Fire Medallion",
  [Items.OOT_MEDALLION_FOREST]: "Forest Medallion",
  [Items.OOT_MEDALLION_LIGHT]: "Light Medallion",
  [Items.OOT_MEDALLION_SHADOW]: "Shadow Medallion",
  [Items.OOT_MEDALLION_SPIRIT]: "Spirit Medallion",
  [Items.OOT_MEDALLION_WATER]: "Water Medallion",
  [Items.OOT_MILK]: "Lon Lon Milk (OoT)",
  [Items.OOT_NUT_UPGRADE]: "Deku Nut Upgrade (OoT)",
  [Items.OOT_NUTS_10]: "10 Deku Nuts (OoT)",
  [Items.OOT_NUTS_5_ALT]: "5 Deku Nuts (OoT)",
  [Items.OOT_NUTS_5]: "5 Deku Nuts (OoT)",
  [Items.OOT_OCARINA]: "Progressive Ocarina (OoT)",
  [Items.OOT_ODD_MUSHROOM]: "Odd Mushroom",
  [Items.OOT_ODD_POTION]: "Odd Potion",
  [Items.OOT_POACHER_SAW]: "Poacher's Saw",
  [Items.OOT_POCKET_CUCCO]: "Pocket Cucco",
  [Items.OOT_POCKET_EGG]: "Pocket Egg",
  [Items.OOT_POE]: "Poe (OoT)",
  [Items.OOT_POTION_BLUE]: "Blue Potion (OoT)",
  [Items.OOT_POTION_GREEN]: "Green Potion (OoT)",
  [Items.OOT_POTION_RED]: "Red Potion (OoT)",
  [Items.OOT_PRESCRIPTION]: "Prescription",
  [Items.OOT_RECOVERY_HEART]: "Recovery Heart (OoT)",
  [Items.OOT_RUPEE_BLUE]: "Blue Rupee (OoT)",
  [Items.OOT_RUPEE_GREEN]: "Green Rupee (OoT)",
  [Items.OOT_RUPEE_HUGE]: "Gold Rupee (OoT)",
  [Items.OOT_RUPEE_PURPLE]: "Purple Rupee (OoT)",
  [Items.OOT_RUPEE_RED]: "Red Rupee (OoT)",
  [Items.OOT_RUPEE_RAINBOW]: "Rainbow Rupee (OoT)",
  [Items.OOT_RUPEE_SILVER_BOTW]: "Silver Rupee (Bottom of the Well)",
  [Items.OOT_RUPEE_SILVER_DC]: "Silver Rupee (Dodongo's Cavern)",
  [Items.OOT_RUPEE_SILVER_GANON_FIRE]: "Silver Rupee (Ganon's Castle - Fire Trial)",
  [Items.OOT_RUPEE_SILVER_GANON_FOREST]: "Silver Rupee (Ganon's Castle - Forest Trial)",
  [Items.OOT_RUPEE_SILVER_GANON_LIGHT]: "Silver Rupee (Ganon's Castle - Light Trial)",
  [Items.OOT_RUPEE_SILVER_GANON_SHADOW]: "Silver Rupee (Ganon's Castle - Shadow Trial)",
  [Items.OOT_RUPEE_SILVER_GANON_SPIRIT]: "Silver Rupee (Ganon's Castle - Spirit Trial)",
  [Items.OOT_RUPEE_SILVER_GANON_WATER]: "Silver Rupee (Ganon's Castle - Water Trial)",
  [Items.OOT_RUPEE_SILVER_GTG_LAVA]: "Silver Rupee (Gerudo Training Ground - Lava)",
  [Items.OOT_RUPEE_SILVER_GTG_SLOPES]: "Silver Rupee (Gerudo Training Ground - Slopes)",
  [Items.OOT_RUPEE_SILVER_GTG_WATER]: "Silver Rupee (Gerudo Training Ground - Water)",
  [Items.OOT_RUPEE_SILVER_IC_BLOCK]: "Silver Rupee (Ice Cavern - Block)",
  [Items.OOT_RUPEE_SILVER_IC_SCYTHE]: "Silver Rupee (Ice Cavern - Scythe)",
  [Items.OOT_RUPEE_SILVER_SHADOW_BLADES]: "Silver Rupee (Shadow Temple - Invisible Blades)",
  [Items.OOT_RUPEE_SILVER_SHADOW_PIT]: "Silver Rupee (Shadow Temple - Large Pits)",
  [Items.OOT_RUPEE_SILVER_SHADOW_SCYTHE]: "Silver Rupee (Shadow Temple - Scythe)",
  [Items.OOT_RUPEE_SILVER_SHADOW_SPIKES]: "Silver Rupee (Shadow Temple - Spikes)",
  [Items.OOT_RUPEE_SILVER_SPIRIT_ADULT]: "Silver Rupee (Spirit Temple - Adult)",
  [Items.OOT_RUPEE_SILVER_SPIRIT_BOULDERS]: "Silver Rupee (Spirit Temple - Boulders)",
  [Items.OOT_RUPEE_SILVER_SPIRIT_CHILD]: "Silver Rupee (Spirit Temple - Child)",
  [Items.OOT_RUPEE_SILVER_SPIRIT_LOBBY]: "Silver Rupee (Spirit Temple - Lobby)",
  [Items.OOT_RUPEE_SILVER_SPIRIT_SUN]: "Silver Rupee (Spirit Temple - Sun Block)",
  [Items.OOT_POUCH_SILVER_BOTW]: "Silver Rupee Pouch (Bottom of the Well)",
  [Items.OOT_POUCH_SILVER_DC]: "Silver Rupee Pouch (Dodongo's Cavern)",
  [Items.OOT_POUCH_SILVER_GANON_FIRE]: "Silver Rupee Pouch (Ganon's Castle - Fire Trial)",
  [Items.OOT_POUCH_SILVER_GANON_FOREST]: "Silver Rupee Pouch (Ganon's Castle - Forest Trial)",
  [Items.OOT_POUCH_SILVER_GANON_LIGHT]: "Silver Rupee Pouch (Ganon's Castle - Light Trial)",
  [Items.OOT_POUCH_SILVER_GANON_SHADOW]: "Silver Rupee Pouch (Ganon's Castle - Shadow Trial)",
  [Items.OOT_POUCH_SILVER_GANON_SPIRIT]: "Silver Rupee Pouch (Ganon's Castle - Spirit Trial)",
  [Items.OOT_POUCH_SILVER_GANON_WATER]: "Silver Rupee Pouch (Ganon's Castle - Water Trial)",
  [Items.OOT_POUCH_SILVER_GTG_LAVA]: "Silver Rupee Pouch (Gerudo Training Ground - Lava)",
  [Items.OOT_POUCH_SILVER_GTG_SLOPES]: "Silver Rupee Pouch (Gerudo Training Ground - Slopes)",
  [Items.OOT_POUCH_SILVER_GTG_WATER]: "Silver Rupee Pouch (Gerudo Training Ground - Water)",
  [Items.OOT_POUCH_SILVER_IC_BLOCK]: "Silver Rupee Pouch (Ice Cavern - Block)",
  [Items.OOT_POUCH_SILVER_IC_SCYTHE]: "Silver Rupee Pouch (Ice Cavern - Scythe)",
  [Items.OOT_POUCH_SILVER_SHADOW_BLADES]: "Silver Rupee Pouch (Shadow Temple - Invisible Blades)",
  [Items.OOT_POUCH_SILVER_SHADOW_PIT]: "Silver Rupee Pouch (Shadow Temple - Large Pits)",
  [Items.OOT_POUCH_SILVER_SHADOW_SCYTHE]: "Silver Rupee Pouch (Shadow Temple - Scythe)",
  [Items.OOT_POUCH_SILVER_SHADOW_SPIKES]: "Silver Rupee Pouch (Shadow Temple - Spikes)",
  [Items.OOT_POUCH_SILVER_SPIRIT_ADULT]: "Silver Rupee Pouch (Spirit Temple - Adult)",
  [Items.OOT_POUCH_SILVER_SPIRIT_BOULDERS]: "Silver Rupee Pouch (Spirit Temple - Boulders)",
  [Items.OOT_POUCH_SILVER_SPIRIT_CHILD]: "Silver Rupee Pouch (Spirit Temple - Child)",
  [Items.OOT_POUCH_SILVER_SPIRIT_LOBBY]: "Silver Rupee Pouch (Spirit Temple - Lobby)",
  [Items.OOT_POUCH_SILVER_SPIRIT_SUN]: "Silver Rupee Pouch (Spirit Temple - Sun Block)",
  [Items.OOT_RUPEE_MAGICAL]: "Magical Silver Rupee",
  [Items.MM_TRANSCENDENT_FAIRY]: "Transcendent Fairy",
  [Items.OOT_BOTTLE_RUTO_LETTER]: "Ruto's Letter",
  [Items.OOT_SCALE]: "Progressive Scale (OoT)",
  [Items.OOT_SHIELD_DEKU]: "Deku Shield (OoT)",
  [Items.OOT_SHIELD_HYLIAN]: "Hylian Shield",
  [Items.OOT_SHIELD_MIRROR]: "Mirror Shield (OoT)",
  [Items.OOT_SHIELD]: "Progressive Shield (OoT)",
  [Items.OOT_SKELETON_KEY]: "Skeleton Key (OoT)",
  [Items.OOT_SLINGSHOT]: "Fairy Slingshot (OoT)",
  [Items.OOT_SMALL_KEY_BOTW]: "Small Key (Bottom of the Well)",
  [Items.OOT_SMALL_KEY_FIRE]: "Small Key (Fire Temple)",
  [Items.OOT_SMALL_KEY_FOREST]: "Small Key (Forest Temple)",
  [Items.OOT_SMALL_KEY_GANON]: "Small Key (Ganon's Castle)",
  [Items.OOT_SMALL_KEY_GF]: "Small Key (Gerudo's Fortress)",
  [Items.OOT_SMALL_KEY_GTG]: "Small Key (Gerudo's Training Ground)",
  [Items.OOT_SMALL_KEY_SHADOW]: "Small Key (Shadow Temple)",
  [Items.OOT_SMALL_KEY_SPIRIT]: "Small Key (Spirit Temple)",
  [Items.OOT_SMALL_KEY_WATER]: "Small Key (Water Temple)",
  [Items.OOT_SMALL_KEY_TCG]: "Small Key (Chest Game)",
  [Items.OOT_SONG_EPONA]: "Epona's Song (OoT)",
  [Items.OOT_SONG_SARIA]: "Saria's Song (OoT)",
  [Items.OOT_SONG_STORMS]: "Song of Storms (OoT)",
  [Items.OOT_SONG_SUN]: "Sun's Song (OoT)",
  [Items.OOT_SONG_TIME]: "Song of Time (OoT)",
  [Items.OOT_SONG_TP_FIRE]: "Bolero of Fire (OoT)",
  [Items.OOT_SONG_TP_FOREST]: "Minuet of Forest (OoT)",
  [Items.OOT_SONG_TP_LIGHT]: "Prelude of Light (OoT)",
  [Items.OOT_SONG_TP_SHADOW]: "Nocturne of Shadow (OoT)",
  [Items.OOT_SONG_TP_SPIRIT]: "Requiem of Spirit (OoT)",
  [Items.OOT_SONG_TP_WATER]: "Serenade of Water (OoT)",
  [Items.OOT_SONG_ZELDA]: "Zelda's Lullaby (OoT)",
  [Items.OOT_SOUL_ENEMY_ANUBIS]: "Soul of Anubis",
  [Items.OOT_SOUL_ENEMY_ARMOS]: "Soul of Armos (OoT)",
  [Items.OOT_SOUL_ENEMY_BABY_DODONGO]: "Soul of Baby Dodongos",
  [Items.OOT_SOUL_BOSS_BARINADE]: "Soul of Barinade",
  [Items.OOT_SOUL_ENEMY_BEAMOS]: "Soul of Beamos (OoT)",
  [Items.OOT_SOUL_ENEMY_BIRI_BARI]: "Soul of Biris/Baris",
  [Items.OOT_SOUL_BOSS_BONGO_BONGO]: "Soul of Bongo Bongo",
  [Items.OOT_SOUL_ENEMY_BUBBLE]: "Soul of Bubbles (OoT)",
  [Items.OOT_SOUL_ENEMY_DARK_LINK]: "Soul of Dark Link",
  [Items.OOT_SOUL_ENEMY_DEAD_HAND]: "Soul of Dead Hands",
  [Items.OOT_SOUL_ENEMY_DEKU_BABA]: "Soul of Deku Babas (OoT)",
  [Items.OOT_SOUL_ENEMY_DEKU_SCRUB]: "Soul of Deku Scrubs (OoT)",
  [Items.OOT_SOUL_ENEMY_DODONGO]: "Soul of Dodongos (OoT)",
  [Items.OOT_SOUL_ENEMY_FLARE_DANCER]: "Soul of Flare Dancers",
  [Items.OOT_SOUL_ENEMY_FLOORMASTER]: "Soul of Floormasters (OoT)",
  [Items.OOT_SOUL_ENEMY_POE]: "Soul of Poes (OoT)",
  [Items.MM_SOUL_ENEMY_POE]: "Soul of Poes (MM)",
  [Items.SHARED_SOUL_ENEMY_POE]: "Soul of Poes",
  [Items.OOT_SOUL_ENEMY_FLYING_POT]: "Soul of Flying Pots (OoT)",
  [Items.OOT_SOUL_ENEMY_FREEZARD]: "Soul of Freezards (OoT)",
  [Items.OOT_SOUL_ENEMY_GOHMA_LARVA]: "Soul of Gohma Larvae",
  [Items.OOT_SOUL_ENEMY_GUAY]: "Soul of Guays (OoT)",
  [Items.OOT_SOUL_ENEMY_IRON_KNUCKLE]: "Soul of Iron Knuckles (OoT)",
  [Items.OOT_SOUL_ENEMY_KEESE]: "Soul of Keese (OoT)",
  [Items.OOT_SOUL_BOSS_KING_DODONGO]: "Soul of King Dodongo",
  [Items.OOT_SOUL_ENEMY_LEEVER]: "Soul of Leevers (OoT)",
  [Items.OOT_SOUL_ENEMY_LIKE_LIKE]: "Soul of Like Likes (OoT)",
  [Items.OOT_SOUL_ENEMY_LIZALFOS_DINOLFOS]: "Soul of Lizalfos/Dinolfos (OoT)",
  [Items.OOT_SOUL_ENEMY_MOBLIN]: "Soul of Moblins",
  [Items.OOT_SOUL_BOSS_MORPHA]: "Soul of Morpha",
  [Items.OOT_SOUL_ENEMY_OCTOROK]: "Soul of Octoroks (OoT)",
  [Items.OOT_SOUL_ENEMY_PARASITE]: "Soul of Jabu-Jabu's Parasites",
  [Items.OOT_SOUL_ENEMY_PEAHAT]: "Soul of Peahats (OoT)",
  [Items.OOT_SOUL_BOSS_PHANTOM_GANON]: "Soul of Phantom Ganon",
  [Items.OOT_SOUL_BOSS_QUEEN_GOHMA]: "Soul of Queen Gohma",
  [Items.OOT_SOUL_ENEMY_REDEAD_GIBDO]: "Soul of ReDeads/Gibdos (OoT)",
  [Items.OOT_SOUL_ENEMY_SHABOM]: "Soul of Shaboms",
  [Items.OOT_SOUL_ENEMY_SHELL_BLADE]: "Soul of Shell Blades (OoT)",
  [Items.OOT_SOUL_ENEMY_SKULL_KID]: "Soul of Skull Kids (OoT)",
  [Items.OOT_SOUL_ENEMY_SKULLTULA]: "Soul of Skulltulas (OoT)",
  [Items.OOT_SOUL_ENEMY_SKULLWALLTULA]: "Soul of Skullwalltulas (OoT)",
  [Items.OOT_SOUL_ENEMY_SPIKE]: "Soul of Spikes",
  [Items.OOT_SOUL_ENEMY_STALCHILD]: "Soul of Stalchildren (OoT)",
  [Items.OOT_SOUL_ENEMY_STALFOS]: "Soul of Stalfos (OoT)",
  [Items.OOT_SOUL_ENEMY_STINGER]: "Soul of Stingers",
  [Items.OOT_SOUL_ENEMY_TAILPASARN]: "Soul of Tailpasarans",
  [Items.OOT_SOUL_ENEMY_TEKTITE]: "Soul of Tektites (OoT)",
  [Items.OOT_SOUL_ENEMY_TORCH_SLUG]: "Soul of Torch Slugs",
  [Items.OOT_SOUL_BOSS_TWINROVA]: "Soul of Twinrova",
  [Items.OOT_SOUL_BOSS_VOLVAGIA]: "Soul of Volvagia",
  [Items.OOT_SOUL_ENEMY_WALLMASTER]: "Soul of Wallmasters (OoT)",
  [Items.OOT_SOUL_ENEMY_WOLFOS]: "Soul of Wolfos (OoT)",
  [Items.OOT_SPELL_FIRE]: "Din's Fire (OoT)",
  [Items.OOT_SPELL_LOVE]: "Nayru's Love (OoT)",
  [Items.OOT_SPELL_WIND]: "Farore's Wind (OoT)",
  [Items.OOT_STICK_UPGRADE]: "Deku Stick Upgrade (OoT)",
  [Items.OOT_STICK]: "Deku Stick (OoT)",
  [Items.OOT_STICKS_10]: "10 Deku Sticks (OoT)",
  [Items.OOT_STICKS_5]: "5 Deku Sticks (OoT)",
  [Items.OOT_STONE_EMERALD]: "Kokiri's Emerald",
  [Items.OOT_STONE_OF_AGONY]: "Stone of Agony (OoT)",
  [Items.MM_STONE_OF_AGONY]: "Stone of Agony (MM)",
  [Items.SHARED_STONE_OF_AGONY]: "Stone of Agony",
  [Items.OOT_STONE_RUBY]: "Goron's Ruby",
  [Items.OOT_STONE_SAPPHIRE]: "Zora's Sapphire",
  [Items.OOT_STRENGTH]: "Progressive Strength (OoT)",
  [Items.OOT_SWORD_BIGGORON]: "Biggoron's Sword",
  [Items.OOT_SWORD_GORON]: "Progressive Goron Sword",
  [Items.OOT_SWORD_KNIFE]: "Giant's Knife",
  [Items.OOT_SWORD_KOKIRI]: "Kokiri Sword (OoT)",
  [Items.OOT_SWORD_MASTER]: "Master Sword",
  [Items.SHARED_SWORD]: "Progressive Sword",
  [Items.OOT_SWORD]: "Progressive Sword (OoT)",
  [Items.OOT_TUNIC_GORON]: "Goron Tunic (OoT)",
  [Items.OOT_TUNIC_ZORA]: "Zora Tunic (OoT)",
  [Items.OOT_WALLET]: "Progressive Wallet (OoT)",
  [Items.OOT_WEIRD_EGG]: "Weird Egg",
  [Items.OOT_ZELDA_LETTER]: "Zelda's Letter",
  [Items.SHARED_ARROW_FIRE]: "Shared Fire Arrows",
  [Items.SHARED_ARROW_ICE]: "Shared Ice Arrows",
  [Items.SHARED_ARROW_LIGHT]: "Shared Light Arrows",
  [Items.SHARED_ARROWS_10]: "10 Arrows",
  [Items.SHARED_ARROWS_30]: "30 Arrows",
  [Items.SHARED_ARROWS_40]: "40 Arrows",
  [Items.SHARED_ARROWS_5]: "5 Arrows",
  [Items.SHARED_DEKU_SEEDS_30]: "30 Deku Seeds",
  [Items.SHARED_DEKU_SEEDS_5]: "5 Deku Seeds",
  [Items.SHARED_BOMB_BAG]: "Shared Bomb Bag",
  [Items.SHARED_BOMB]: "1 Bomb",
  [Items.SHARED_BOMBCHU_10]: "10 Bombchu",
  [Items.SHARED_BOMBCHU_20]: "20 Bombchu",
  [Items.SHARED_BOMBCHU_5]: "5 Bombchu",
  [Items.SHARED_BOMBCHU]: "Bombchu",
  [Items.SHARED_BOMBS_10]: "10 Bombs",
  [Items.SHARED_BOMBS_20]: "20 Bombs",
  [Items.SHARED_BOMBS_30]: "30 Bombs",
  [Items.SHARED_BOMBS_5]: "5 Bombs",
  [Items.SHARED_BOW]: "Shared Bow",
  [Items.SHARED_DEFENSE_UPGRADE]: "Double Defense",
  [Items.SHARED_HEART_CONTAINER]: "Heart Container",
  [Items.SHARED_HEART_PIECE]: "Piece of Heart",
  [Items.SHARED_HOOKSHOT]: "Progressive Hookshot",
  [Items.SHARED_LENS]: "Lens of Truth",
  [Items.SHARED_MAGIC_UPGRADE]: "Shared Magic Upgrade",
  [Items.SHARED_MASK_BUNNY]: "Bunny Hood",
  [Items.SHARED_MASK_GORON]: "Goron Mask",
  [Items.SHARED_MASK_KEATON]: "Keaton Mask",
  [Items.SHARED_MASK_TRUTH]: "Mask of Truth",
  [Items.SHARED_MASK_ZORA]: "Zora Mask",
  [Items.SHARED_MASK_GERUDO]: "Gerudo Mask",
  [Items.SHARED_MASK_SKULL]: "Skull Mask",
  [Items.SHARED_MASK_SPOOKY]: "Spooky Mask",
  [Items.SHARED_NUT]: "Deku Nut",
  [Items.SHARED_NUTS_10]: "10 Deku Nuts",
  [Items.SHARED_NUTS_5]: "5 Deku Nuts",
  [Items.SHARED_OCARINA]: "Progressive Ocarina",
  [Items.SHARED_RECOVERY_HEART]: "Recovery Heart",
  [Items.SHARED_RUPEE_BLUE]: "Blue Rupee",
  [Items.SHARED_RUPEE_GOLD]: "Gold Rupee",
  [Items.SHARED_RUPEE_GREEN]: "Green Rupee",
  [Items.SHARED_RUPEE_PURPLE]: "Purple Rupee",
  [Items.SHARED_RUPEE_RED]: "Red Rupee",
  [Items.SHARED_RUPEE_SILVER]: "Silver Rupee",
  [Items.SHARED_RUPEE_RAINBOW]: "Rainbow Rupee",
  [Items.SHARED_SKELETON_KEY]: "Skeleton Key",
  [Items.SHARED_SONG_EPONA]: "Epona's Song",
  [Items.SHARED_SONG_STORMS]: "Song of Storms",
  [Items.SHARED_SONG_TIME]: "Song of Time",
  [Items.SHARED_SONG_ZELDA]: "Zelda's Lullaby",
  [Items.SHARED_SONG_SARIA]: "Saria's Song",
  [Items.SHARED_SONG_SUN]: "Sun's Song",
  [Items.SHARED_SONG_TP_FIRE]: "Bolero of Fire",
  [Items.SHARED_SONG_TP_FOREST]: "Minuet of Forest",
  [Items.SHARED_SONG_TP_LIGHT]: "Prelude of Light",
  [Items.SHARED_SONG_TP_SHADOW]: "Nocturne of Shadow",
  [Items.SHARED_SONG_TP_SPIRIT]: "Requiem of Spirit",
  [Items.SHARED_SONG_TP_WATER]: "Serenade of Water",
  [Items.SHARED_SOUL_ENEMY_ARMOS]: "Soul of Armos",
  [Items.SHARED_SOUL_ENEMY_BEAMOS]: "Soul of Beamos",
  [Items.SHARED_SOUL_ENEMY_BUBBLE]: "Soul of Bubbles",
  [Items.SHARED_SOUL_ENEMY_DEKU_BABA]: "Soul of Deku Babas",
  [Items.SHARED_SOUL_ENEMY_DEKU_SCRUB]: "Soul of Deku Scrubs",
  [Items.SHARED_SOUL_ENEMY_DODONGO]: "Soul of Dodongos",
  [Items.SHARED_SOUL_ENEMY_FLOORMASTER]: "Soul of Floormasters",
  [Items.SHARED_SOUL_ENEMY_FLYING_POT]: "Soul of Flying Pots",
  [Items.SHARED_SOUL_ENEMY_FREEZARD]: "Soul of Freezards",
  [Items.SHARED_SOUL_ENEMY_GUAY]: "Soul of Guays",
  [Items.SHARED_SOUL_ENEMY_IRON_KNUCKLE]: "Soul of Iron Knuckles",
  [Items.SHARED_SOUL_ENEMY_KEESE]: "Soul of Keese",
  [Items.SHARED_SOUL_ENEMY_LEEVER]: "Soul of Leevers",
  [Items.SHARED_SOUL_ENEMY_LIKE_LIKE]: "Soul of Like Likes",
  [Items.SHARED_SOUL_ENEMY_LIZALFOS_DINOLFOS]: "Soul of Lizalfos/Dinolfos",
  [Items.SHARED_SOUL_ENEMY_OCTOROK]: "Soul of Octoroks",
  [Items.SHARED_SOUL_ENEMY_PEAHAT]: "Soul of Peahats",
  [Items.SHARED_SOUL_ENEMY_REDEAD_GIBDO]: "Soul of ReDeads/Gibdos",
  [Items.SHARED_SOUL_ENEMY_SHELL_BLADE]: "Soul of Shell Blades",
  [Items.SHARED_SOUL_ENEMY_SKULLTULA]: "Soul of Skulltulas",
  [Items.SHARED_SOUL_ENEMY_SKULLWALLTULA]: "Soul of Skullwalltulas",
  [Items.SHARED_SOUL_ENEMY_STALCHILD]: "Soul of Stalchildren",
  [Items.SHARED_SOUL_ENEMY_TEKTITE]: "Soul of Tektites",
  [Items.SHARED_SOUL_ENEMY_WALLMASTER]: "Soul of Wallmasters",
  [Items.SHARED_SOUL_ENEMY_WOLFOS]: "Soul of Wolfos",
  [Items.SHARED_STICK]: "Deku Stick",
  [Items.SHARED_STICKS_10]: "10 Deku Sticks",
  [Items.SHARED_STICKS_5]: "5 Deku Sticks",
  [Items.SHARED_TRIFORCE_COURAGE]: "Triforce of Courage",
  [Items.SHARED_TRIFORCE_POWER]: "Triforce of Power",
  [Items.SHARED_TRIFORCE_WISDOM]: "Triforce of Wisdom",
  [Items.SHARED_TRIFORCE]: "Triforce Piece",
  [Items.SHARED_WALLET]: "Progressive Wallet",
  [Items.SHARED_SPELL_FIRE]: "Din's Fire",
  [Items.SHARED_SPELL_LOVE]: "Nayru's Love",
  [Items.SHARED_SPELL_WIND]: "Farore's Wind",
  [Items.SHARED_BOOTS_IRON]: 'Iron Boots',
  [Items.SHARED_BOOTS_HOVER]: 'Hover Boots',
  [Items.SHARED_TUNIC_GORON]: 'Goron Tunic',
  [Items.SHARED_TUNIC_ZORA]: 'Zora Tunic',
  [Items.SHARED_SCALE]: "Progressive Scale",
  [Items.SHARED_STRENGTH]: "Progressive Strength",
  [Items.OOT_BUTTON_A]: "A Button (OoT)",
  [Items.OOT_BUTTON_C_RIGHT]: "C-Right Button (OoT)",
  [Items.OOT_BUTTON_C_LEFT]: "C-Left Button (OoT)",
  [Items.OOT_BUTTON_C_UP]: "C-Up Button (OoT)",
  [Items.OOT_BUTTON_C_DOWN]: "C-Down Button (OoT)",
  [Items.MM_BUTTON_A]: "A Button (MM)",
  [Items.MM_BUTTON_C_RIGHT]: "C-Right Button (MM)",
  [Items.MM_BUTTON_C_LEFT]: "C-Left Button (MM)",
  [Items.MM_BUTTON_C_UP]: "C-Up Button (MM)",
  [Items.MM_BUTTON_C_DOWN]: "C-Down Button (MM)",
  [Items.SHARED_BUTTON_A]: "A Button",
  [Items.SHARED_BUTTON_C_RIGHT]: "C-Right Button",
  [Items.SHARED_BUTTON_C_LEFT]: "C-Left Button",
  [Items.SHARED_BUTTON_C_UP]: "C-Up Button",
  [Items.SHARED_BUTTON_C_DOWN]: "C-Down Button",
  [Items.OOT_SOUL_NPC_SARIA]: "Soul of Saria",
  [Items.OOT_SOUL_NPC_DARUNIA]: "Soul of Darunia",
  [Items.OOT_SOUL_NPC_RUTO]: "Soul of Ruto (OoT)",
  [Items.OOT_SOUL_NPC_KING_ZORA]: "Soul of King Zora",
  [Items.OOT_SOUL_NPC_ZELDA]: "Soul of Zelda",
  [Items.OOT_SOUL_NPC_SHEIK]: "Soul of Sheik",
  [Items.OOT_SOUL_NPC_ANJU]: "Soul of Cucco Lady (OoT)",
  [Items.OOT_SOUL_NPC_CARPENTERS]: "Soul of Carpenters (OoT)",
  [Items.OOT_SOUL_NPC_GURU_GURU]: "Soul of Guru-Guru (OoT)",
  [Items.OOT_SOUL_NPC_MIDO]: "Soul of Mido",
  [Items.OOT_SOUL_NPC_KOKIRI]: "Soul of Kokiri",
  [Items.OOT_SOUL_NPC_KOKIRI_SHOPKEEPER]: "Soul of Kokiri Shopkeeper",
  [Items.OOT_SOUL_NPC_HYLIAN_GUARD]: "Soul of Hylian Guard",
  [Items.OOT_SOUL_NPC_CITIZEN]: "Soul of the Citizens (OoT)",
  [Items.OOT_SOUL_NPC_MALON]: "Soul of Malon (OoT)",
  [Items.OOT_SOUL_NPC_TALON]: "Soul of Talon (OoT)",
  [Items.OOT_SOUL_NPC_FISHING_POND_OWNER]: "Soul of Fishing Pond Owner (OoT)",
  [Items.OOT_SOUL_NPC_GORON]: "Soul of Goron (OoT)",
  [Items.OOT_SOUL_NPC_MEDIGORON]: "Soul of Medigoron (OoT)",
  [Items.OOT_SOUL_NPC_BIGGORON]: "Soul of Biggoron (OoT)",
  [Items.OOT_SOUL_NPC_GORON_CHILD]: "Soul of Goron Child (OoT)",
  [Items.OOT_SOUL_NPC_GORON_SHOPKEEPER]: "Soul of Goron Shopkeeper (OoT)",
  [Items.OOT_SOUL_NPC_ZORA]: "Soul of Zora (OoT)",
  [Items.OOT_SOUL_NPC_ZORA_SHOPKEEPER]: "Soul of Zora Shopkeeper (OoT)",
  [Items.OOT_SOUL_NPC_BAZAAR_SHOPKEEPER]: "Soul of Bazaar Shopkeeper (OoT)",
  [Items.OOT_SOUL_NPC_BOMBCHU_SHOPKEEPER]: "Soul of Bombchu Shopkeeper (OoT)",
  [Items.OOT_SOUL_NPC_POTION_SHOPKEEPER]: "Soul of Potion Shopkeeper",
  [Items.OOT_SOUL_NPC_BOMBCHU_BOWLING_LADY]: "Soul of Bombchu Bowling Lady (OoT)",
  [Items.OOT_SOUL_NPC_CHEST_GAME_OWNER]: "Soul of Chest Game Owner (OoT)",
  [Items.OOT_SOUL_NPC_SHOOTING_GALLERY_OWNER]: "Soul of Shooting Gallery Owner (OoT)",
  [Items.OOT_SOUL_NPC_DAMPE]: "Soul of Dampe (OoT)",
  [Items.OOT_SOUL_NPC_BOMBERS]: "Soul of Graveyard Kid (OoT)",
  [Items.OOT_SOUL_NPC_POE_COLLECTOR]: "Soul of Poe Collector (OoT)",
  [Items.OOT_SOUL_NPC_COMPOSER_BROS]: "Soul of Composer Bros. (OoT)",
  [Items.OOT_SOUL_NPC_HONEY_DARLING]: "Soul of Honey & Darling (OoT)",
  [Items.OOT_SOUL_NPC_ASTRONOMER]: "Soul of the Astronomer (OoT)",
  [Items.OOT_SOUL_NPC_ROOFTOP_MAN]: "Soul of the Rooftop Man (OoT)",
  [Items.OOT_SOUL_NPC_BEAN_SALESMAN]: "Soul of the Bean Salesman (OoT)",
  [Items.OOT_SOUL_NPC_SCIENTIST]: "Soul of the Scientist (OoT)",
  [Items.OOT_SOUL_NPC_GORMAN]: "Soul of Ingo (OoT)",
  [Items.OOT_SOUL_NPC_GROG]: "Soul of the Punk Kid (OoT)",
  [Items.OOT_SOUL_NPC_DOG_LADY]: "Soul of the Dog Lady (OoT)",
  [Items.OOT_SOUL_NPC_CARPET_MAN]: "Soul of the Carpet Man (OoT)",
  [Items.OOT_SOUL_NPC_OLD_HAG]: "Soul of the Old Hag (OoT)",
  [Items.OOT_SOUL_NPC_BANKER]: "Soul of the Beggar (OoT)",
  [Items.MM_SOUL_NPC_AROMA]: "Soul of Madame Aroma (MM)",
  [Items.MM_SOUL_NPC_SHOOTING_GALLERY_OWNER]: "Soul of Town Archery Owner (MM)",
  [Items.MM_SOUL_NPC_BAZAAR_SHOPKEEPER]: "Soul of Swamp Archery Owner (MM)",
  [Items.MM_SOUL_NPC_GORON]: "Soul of Gorons (MM)",
  [Items.MM_SOUL_NPC_GORON_CHILD]: "Soul of the Goron Baby (MM)",
  [Items.MM_SOUL_NPC_BOMBCHU_SHOPKEEPER]: "Soul of the Bomb Shop Owner (MM)",
  [Items.MM_SOUL_NPC_BOMBERS]: "Soul of Bombers (MM)",
  [Items.MM_SOUL_NPC_BUTLER_DEKU]: "Soul of the Deku Butler",
  [Items.MM_SOUL_NPC_CITIZEN]: "Soul of Citizens (MM)",
  [Items.MM_SOUL_NPC_COMPOSER_BROS]: "Soul of Composer Bros. (MM)",
  [Items.MM_SOUL_NPC_DAMPE]: "Soul of Dampe (MM)",
  [Items.MM_SOUL_NPC_DEKU_KING]: "Soul of the Deku King",
  [Items.MM_SOUL_NPC_DEKU_PRINCESS]: "Soul of the Deku Princess",
  [Items.MM_SOUL_NPC_PLAYGROUND_SCRUBS]: "Soul of Playground Scrubs",
  [Items.MM_SOUL_NPC_GORON_ELDER]: "Soul of the Goron Elder",
  [Items.MM_SOUL_NPC_CHEST_GAME_OWNER]: "Soul of the Fisherman (MM)",
  [Items.MM_SOUL_NPC_GORON_SHOPKEEPER]: "Soul of the Goron Shopkeeper (MM)",
  [Items.MM_SOUL_NPC_HONEY_DARLING]: "Soul of Honey & Darling (MM)",
  [Items.MM_SOUL_NPC_TOTO]: "Soul of Toto (MM)",
  [Items.MM_SOUL_NPC_RUTO]: "Soul of Lulu (MM)",
  [Items.MM_SOUL_NPC_ZORA_MUSICIANS]: "Soul of the Zora Musicians",
  [Items.MM_SOUL_NPC_KAFEI]: "Soul of Kafei",
  [Items.MM_SOUL_NPC_KEATON]: "Soul of Keaton",
  [Items.MM_SOUL_NPC_KOUME_KOTAKE]: "Soul of Koume and Kotake",
  [Items.MM_SOUL_NPC_MAYOR_DOTOUR]: "Soul of Mayor Dotour",
  [Items.MM_SOUL_NPC_MEDIGORON]: "Soul of Keg Trial Goron (MM)",
  [Items.MM_SOUL_NPC_BIGGORON]: "Soul of Biggoron (MM)",
  [Items.MM_SOUL_NPC_TALON]: "Soul of Mr. Barten (MM)",
  [Items.MM_SOUL_NPC_ASTRONOMER]: "Soul of Astronomer (MM)",
  [Items.MM_SOUL_NPC_POE_COLLECTOR]: "Soul of Ghost Hut Owner (MM)",
  [Items.MM_SOUL_NPC_BLACKSMITHS]: "Soul of Blacksmiths",
  [Items.MM_SOUL_NPC_BOMBCHU_BOWLING_LADY]: "Soul of Chest Game Lady (MM)",
  [Items.MM_SOUL_NPC_TINGLE]: "Soul of Tingle",
  [Items.MM_SOUL_NPC_TOILET_HAND]: "Soul of Toilet Hand",
  [Items.MM_SOUL_NPC_FISHING_POND_OWNER]: "Soul of Trading Post Owner (MM)",
  [Items.MM_SOUL_NPC_ROOFTOP_MAN]: "Soul of Part-Timer (MM)",
  [Items.MM_SOUL_NPC_ZORA]: "Soul of Zoras (MM)",
  [Items.MM_SOUL_NPC_ZORA_SHOPKEEPER]: "Soul of the Zora Shopkeeper (MM)",
  [Items.MM_SOUL_NPC_MALON]: "Soul of Romani/Cremia (MM)",
  [Items.MM_SOUL_NPC_BEAN_SALESMAN]: "Soul of the Bean Salesman (MM)",
  [Items.MM_SOUL_NPC_CARPENTERS]: "Soul of Carpenters (MM)",
  [Items.MM_SOUL_NPC_ANJU]: "Soul of Anju (MM)",
  [Items.MM_SOUL_NPC_GURU_GURU]: "Soul of Guru-Guru (MM)",
  [Items.MM_SOUL_NPC_SCIENTIST]: "Soul of the Scientist (MM)",
  [Items.MM_SOUL_NPC_GORMAN]: "Soul of Gorman & Bros. (MM)",
  [Items.MM_SOUL_NPC_GROG]: "Soul of Grog (MM)",
  [Items.MM_SOUL_NPC_DOG_LADY]: "Soul of Dog Lady (MM)",
  [Items.MM_SOUL_NPC_CARPET_MAN]: "Soul of Swordsman (MM)",
  [Items.MM_SOUL_NPC_OLD_HAG]: "Soul of Anju's Grandmother (MM)",
  [Items.MM_SOUL_NPC_TOURIST_CENTER]: "Soul of Tourist Center Owner",
  [Items.MM_SOUL_NPC_BANKER]: "Soul of the Banker (MM)",
  [Items.MM_SOUL_NPC_MOON_CHILDREN]: "Soul of Moon Children",
  [Items.SHARED_SOUL_NPC_SHOOTING_GALLERY_OWNER]: "Soul of the Shooting Gallery/Town Archery Owner",
  [Items.SHARED_SOUL_NPC_BAZAAR_SHOPKEEPER]: "Soul of the Bazaar/Swamp Archery Owner",
  [Items.SHARED_SOUL_NPC_GORON]: "Soul of Gorons",
  [Items.SHARED_SOUL_NPC_GORON_CHILD]: "Soul of the Goron Child/Baby",
  [Items.SHARED_SOUL_NPC_BOMBCHU_SHOPKEEPER]: "Soul of the Bombchu/Bomb Shop Owner",
  [Items.SHARED_SOUL_NPC_BOMBERS]: "Soul of the Graveyard Kid/Bombers",
  [Items.SHARED_SOUL_NPC_CITIZEN]: "Soul of Citizens",
  [Items.SHARED_SOUL_NPC_COMPOSER_BROS]: "Soul of Composer Bros.",
  [Items.SHARED_SOUL_NPC_DAMPE]: "Soul of Dampe",
  [Items.SHARED_SOUL_NPC_CHEST_GAME_OWNER]: "Soul of the Chest Game Owner/Fisherman",
  [Items.SHARED_SOUL_NPC_GORON_SHOPKEEPER]: "Soul of the Goron Shopkeeper",
  [Items.SHARED_SOUL_NPC_HONEY_DARLING]: "Soul of Honey & Darling",
  [Items.SHARED_SOUL_NPC_RUTO]: "Soul of Ruto/Lulu",
  [Items.SHARED_SOUL_NPC_MEDIGORON]: "Soul of Medigoron/Keg Trial Goron",
  [Items.SHARED_SOUL_NPC_BIGGORON]: "Soul of Biggoron",
  [Items.SHARED_SOUL_NPC_TALON]: "Soul of Talon/Mr. Barten",
  [Items.SHARED_SOUL_NPC_ASTRONOMER]: "Soul of the Astronomer",
  [Items.SHARED_SOUL_NPC_POE_COLLECTOR]: "Soul of Poe Collector/Ghost Hut Owner",
  [Items.SHARED_SOUL_NPC_BOMBCHU_BOWLING_LADY]: "Soul of Bombchu Bowling/Chest Game Lady",
  [Items.SHARED_SOUL_NPC_FISHING_POND_OWNER]: "Soul of Fishing Pond/Trading Post Owner",
  [Items.SHARED_SOUL_NPC_ROOFTOP_MAN]: "Soul of Rooftop Man/Part-Timer",
  [Items.SHARED_SOUL_NPC_ZORA]: "Soul of Zoras",
  [Items.SHARED_SOUL_NPC_ZORA_SHOPKEEPER]: "Soul of the Zora Shopkeeper",
  [Items.SHARED_SOUL_NPC_MALON]: "Soul of Malon/Romani/Cremia",
  [Items.SHARED_SOUL_NPC_BEAN_SALESMAN]: "Soul of the Bean Salesman",
  [Items.SHARED_SOUL_NPC_CARPENTERS]: "Soul of Carpenters",
  [Items.SHARED_SOUL_NPC_ANJU]: "Soul of Cucco Lady/Anju",
  [Items.SHARED_SOUL_NPC_GURU_GURU]: "Soul of Guru-Guru",
  [Items.SHARED_SOUL_NPC_SCIENTIST]: "Soul of the Scientist",
  [Items.SHARED_SOUL_NPC_GORMAN]: "Soul of Ingo/Gorman & Bros.",
  [Items.SHARED_SOUL_NPC_GROG]: "Soul of the Punk Kid/Grog",
  [Items.SHARED_SOUL_NPC_DOG_LADY]: "Soul of the Dog Lady",
  [Items.SHARED_SOUL_NPC_CARPET_MAN]: "Soul of the Carpet Man/Swordsman",
  [Items.SHARED_SOUL_NPC_OLD_HAG]: "Soul of the Old Hag/Anju's Grandmother",
  [Items.SHARED_SOUL_NPC_BANKER]: "Soul of the Beggar/Banker",
  [Items.OOT_FISHING_POND_CHILD_FISH]: 'Child Fish (Placeholder)',
  [Items.OOT_FISHING_POND_ADULT_FISH]: 'Adult Fish (Placeholder)',
  [Items.OOT_FISHING_POND_CHILD_LOACH]: 'Child Loach (Placeholder)',
  [Items.OOT_FISHING_POND_ADULT_LOACH]: 'Adult Loach (Placeholder)',
  [Items.OOT_FISHING_POND_CHILD_FISH_2LBS]: 'Child Fish (2 pounds)',
  [Items.OOT_FISHING_POND_CHILD_FISH_3LBS]: 'Child Fish (3 pounds)',
  [Items.OOT_FISHING_POND_CHILD_FISH_4LBS]: 'Child Fish (4 pounds)',
  [Items.OOT_FISHING_POND_CHILD_FISH_5LBS]: 'Child Fish (5 pounds)',
  [Items.OOT_FISHING_POND_CHILD_FISH_6LBS]: 'Child Fish (6 pounds)',
  [Items.OOT_FISHING_POND_CHILD_FISH_7LBS]: 'Child Fish (7 pounds)',
  [Items.OOT_FISHING_POND_CHILD_FISH_8LBS]: 'Child Fish (8 pounds)',
  [Items.OOT_FISHING_POND_CHILD_FISH_9LBS]: 'Child Fish (9 pounds)',
  [Items.OOT_FISHING_POND_CHILD_FISH_10LBS]: 'Child Fish (10 pounds)',
  [Items.OOT_FISHING_POND_CHILD_FISH_11LBS]: 'Child Fish (11 pounds)',
  [Items.OOT_FISHING_POND_CHILD_FISH_12LBS]: 'Child Fish (12 pounds)',
  [Items.OOT_FISHING_POND_CHILD_FISH_13LBS]: 'Child Fish (13 pounds)',
  [Items.OOT_FISHING_POND_CHILD_FISH_14LBS]: 'Child Fish (14 pounds)',
  [Items.OOT_FISHING_POND_ADULT_FISH_4LBS]: 'Adult Fish (4 pounds)',
  [Items.OOT_FISHING_POND_ADULT_FISH_5LBS]: 'Adult Fish (5 pounds)',
  [Items.OOT_FISHING_POND_ADULT_FISH_6LBS]: 'Adult Fish (6 pounds)',
  [Items.OOT_FISHING_POND_ADULT_FISH_7LBS]: 'Adult Fish (7 pounds)',
  [Items.OOT_FISHING_POND_ADULT_FISH_8LBS]: 'Adult Fish (8 pounds)',
  [Items.OOT_FISHING_POND_ADULT_FISH_9LBS]: 'Adult Fish (9 pounds)',
  [Items.OOT_FISHING_POND_ADULT_FISH_10LBS]: 'Adult Fish (10 pounds)',
  [Items.OOT_FISHING_POND_ADULT_FISH_11LBS]: 'Adult Fish (11 pounds)',
  [Items.OOT_FISHING_POND_ADULT_FISH_12LBS]: 'Adult Fish (12 pounds)',
  [Items.OOT_FISHING_POND_ADULT_FISH_13LBS]: 'Adult Fish (13 pounds)',
  [Items.OOT_FISHING_POND_ADULT_FISH_14LBS]: 'Adult Fish (14 pounds)',
  [Items.OOT_FISHING_POND_ADULT_FISH_15LBS]: 'Adult Fish (15 pounds)',
  [Items.OOT_FISHING_POND_ADULT_FISH_16LBS]: 'Adult Fish (16 pounds)',
  [Items.OOT_FISHING_POND_ADULT_FISH_17LBS]: 'Adult Fish (17 pounds)',
  [Items.OOT_FISHING_POND_ADULT_FISH_18LBS]: 'Adult Fish (18 pounds)',
  [Items.OOT_FISHING_POND_ADULT_FISH_19LBS]: 'Adult Fish (19 pounds)',
  [Items.OOT_FISHING_POND_ADULT_FISH_20LBS]: 'Adult Fish (20 pounds)',
  [Items.OOT_FISHING_POND_ADULT_FISH_21LBS]: 'Adult Fish (21 pounds)',
  [Items.OOT_FISHING_POND_ADULT_FISH_22LBS]: 'Adult Fish (22 pounds)',
  [Items.OOT_FISHING_POND_ADULT_FISH_23LBS]: 'Adult Fish (23 pounds)',
  [Items.OOT_FISHING_POND_ADULT_FISH_24LBS]: 'Adult Fish (24 pounds)',
  [Items.OOT_FISHING_POND_ADULT_FISH_25LBS]: 'Adult Fish (25 pounds)',
  [Items.OOT_FISHING_POND_CHILD_LOACH_14LBS]: 'Child Loach (14 pounds)',
  [Items.OOT_FISHING_POND_CHILD_LOACH_15LBS]: 'Child Loach (15 pounds)',
  [Items.OOT_FISHING_POND_CHILD_LOACH_16LBS]: 'Child Loach (16 pounds)',
  [Items.OOT_FISHING_POND_CHILD_LOACH_17LBS]: 'Child Loach (17 pounds)',
  [Items.OOT_FISHING_POND_CHILD_LOACH_18LBS]: 'Child Loach (18 pounds)',
  [Items.OOT_FISHING_POND_CHILD_LOACH_19LBS]: 'Child Loach (19 pounds)',
  [Items.OOT_FISHING_POND_ADULT_LOACH_29LBS]: 'Adult Loach (29 pounds)',
  [Items.OOT_FISHING_POND_ADULT_LOACH_30LBS]: 'Adult Loach (30 pounds)',
  [Items.OOT_FISHING_POND_ADULT_LOACH_31LBS]: 'Adult Loach (31 pounds)',
  [Items.OOT_FISHING_POND_ADULT_LOACH_32LBS]: 'Adult Loach (32 pounds)',
  [Items.OOT_FISHING_POND_ADULT_LOACH_33LBS]: 'Adult Loach (33 pounds)',
  [Items.OOT_FISHING_POND_ADULT_LOACH_34LBS]: 'Adult Loach (34 pounds)',
  [Items.OOT_FISHING_POND_ADULT_LOACH_35LBS]: 'Adult Loach (35 pounds)',
  [Items.OOT_FISHING_POND_ADULT_LOACH_36LBS]: 'Adult Loach (36 pounds)',
  [Items.SHARED_SHIELD_DEKU]: "Deku Shield",
  [Items.SHARED_SHIELD_HYLIAN]: "Hylian/Hero Shield",
  [Items.SHARED_SHIELD_MIRROR]: "Mirror Shield",
  [Items.SHARED_SHIELD]: "Progressive Shield",
  [Items.OOT_BOTTLE_FAIRY]: "Bottled Fairy (OoT)",
  [Items.MM_BOTTLE_FAIRY]: "Bottled Fairy (MM)",
  [Items.OOT_BOTTLE_POE]: "Bottled Poe (OoT)",
  [Items.MM_BOTTLE_POE]: "Bottled Poe (MM)",
  [Items.OOT_BOTTLE_BIG_POE]: "Bottled Big Poe (OoT)",
  [Items.MM_BOTTLE_BIG_POE]: "Bottled Big Poe (MM)",
  [Items.MM_POE]: "Poe (MM)",
  [Items.OOT_BIG_POE]: "Big Poe (OoT)",
  [Items.MM_BIG_POE]: "Big Poe (MM)",
  [Items.OOT_MAGIC_JAR_SMALL]: "Small Magic Jar (OoT)",
  [Items.OOT_MAGIC_JAR_LARGE]: "Large Magic Jar (OoT)",
  [Items.MM_MAGIC_JAR_SMALL]: "Small Magic Jar (MM)",
  [Items.MM_MAGIC_JAR_LARGE]: "Large Magic Jar (MM)",
  [Items.SHARED_MAGIC_JAR_SMALL]: "Small Magic Jar",
  [Items.SHARED_MAGIC_JAR_LARGE]: "Large Magic Jar",
  [Items.NOTHING]: 'Nothing',
  [Items.OOT_FAIRY_BIG]: 'Big Fairy (OoT)',
  [Items.MM_FAIRY_BIG]: 'Big Fairy (MM)',
  [Items.SHARED_FAIRY_BIG]: 'Big Fairy',
  [Items.OOT_BOTTLE_BLUE_FIRE]: "Bottle of Blue Fire",
  [Items.MM_SPELL_FIRE]: "Din's Fire (MM)",
  [Items.MM_SPELL_LOVE]: "Nayru's Love (MM)",
  [Items.MM_SPELL_WIND]: "Farore's Wind (MM)",
  [Items.MM_BOOTS_IRON]: 'Iron Boots (MM)',
  [Items.MM_BOOTS_HOVER]: 'Hover Boots (MM)',
  [Items.MM_TUNIC_GORON]: 'Goron Tunic (MM)',
  [Items.MM_TUNIC_ZORA]: 'Zora Tunic (MM)',
  [Items.MM_SCALE]: "Progressive Scale (MM)",
  [Items.MM_STRENGTH]: "Progressive Strength (MM)",
  [Items.OOT_MASK_BLAST]: "Blast Mask (OoT)",
  [Items.SHARED_MASK_BLAST]: "Blast Mask",
  [Items.OOT_MASK_STONE]: "Stone Mask (OoT)",
  [Items.SHARED_MASK_STONE]: "Stone Mask",
  [Items.OOT_MASK_KAMARO]: "Kamaro's Mask (OoT)",
  [Items.SHARED_MASK_KAMARO]: "Kamaro's Mask",
  [Items.OOT_SONG_EMPTINESS]: "Elegy of Emptiness (OoT)",
  [Items.SHARED_SONG_EMPTINESS]: "Elegy of Emptiness",
  [Items.OOT_SONG_HEALING]: "Song of Healing (OoT)",
  [Items.SHARED_SONG_HEALING]: "Song of Healing",
  [Items.OOT_SONG_SOARING]: "Song of Soaring (OoT)",
  [Items.SHARED_SONG_SOARING]: "Song of Soaring",
  [Items.OOT_SONG_AWAKENING]: "Sonata of Awakening (OoT)",
  [Items.SHARED_SONG_AWAKENING]: "Sonata of Awakening",
  [Items.OOT_SONG_GORON_HALF]: "Progressive Goron Lullaby (OoT)",
  [Items.SHARED_SONG_GORON_HALF]: "Progressive Goron Lullaby",
  [Items.OOT_SONG_GORON]: "Goron Lullaby (OoT)",
  [Items.SHARED_SONG_GORON]: "Goron Lullaby",
  [Items.OOT_SONG_ZORA]: "New Wave Bossa Nova (OoT)",
  [Items.SHARED_SONG_ZORA]: "New Wave Bossa Nova",
  [Items.OOT_SONG_ORDER]: "Oath to Order (OoT)",
  [Items.SHARED_SONG_ORDER]: "Oath to Order",
  [Items.OOT_POWDER_KEG]: 'Powder Keg (OoT)',
  [Items.SHARED_POWDER_KEG]: 'Powder Keg',
  [Items.MM_CLOCK]: "Progressive Clock (MM)",
  [Items.MM_CLOCK1]: "Clock (MM, Day 1)",
  [Items.MM_CLOCK2]: "Clock (MM, Night 1)",
  [Items.MM_CLOCK3]: "Clock (MM, Day 2)",
  [Items.MM_CLOCK4]: "Clock (MM, Night 2)",
  [Items.MM_CLOCK5]: "Clock (MM, Day 3)",
  [Items.MM_CLOCK6]: "Clock (MM, Night 3)",
  [Items.OOT_CLOCK]: "Clock (OoT)",
  [Items.OOT_TRAP_ICE]: "Ice Trap",
  [Items.OOT_TRAP_FIRE]: "Fire Trap",
  [Items.OOT_TRAP_SHOCK]: "Shock Trap",
  [Items.OOT_TRAP_DRAIN]: "Drain Trap",
  [Items.OOT_TRAP_ANTI_MAGIC]: "Anti-Magic Trap",
  [Items.OOT_TRAP_KNOCKBACK]: "Knockback Trap",
  [Items.OOT_TRAP_RUPOOR]: "Rupoor",
  [Items.OOT_SOUL_MISC_GS]: "Soul of Gold Skulltulas (OoT)",
  [Items.OOT_SOUL_MISC_BUSINESS_SCRUB]: "Soul of Business Scrubs (OoT)",
  [Items.MM_SOUL_MISC_GS]: "Soul of Gold Skulltulas (MM)",
  [Items.MM_SOUL_MISC_BUSINESS_SCRUB]: "Soul of Business Scrubs (MM)",
  [Items.SHARED_SOUL_MISC_GS]: "Soul of Gold Skulltulas",
  [Items.SHARED_SOUL_MISC_BUSINESS_SCRUB]: "Soul of Business Scrubs",
  [Items.OOT_SOUL_NPC_THIEVES]: 'Soul of the Patrolling Gerudos',
  [Items.MM_SOUL_NPC_THIEVES]: 'Soul of the Patrolling Pirates and their Chief',
  [Items.OOT_SOUL_ENEMY_THIEVES]: 'Soul of the Fighting Gerudos',
  [Items.MM_SOUL_ENEMY_THIEVES]: 'Soul of the Fighting Pirates',
  [Items.SHARED_SOUL_NPC_THIEVES]: 'Soul of the Patrolling Thieves and their Chief',
  [Items.SHARED_SOUL_ENEMY_THIEVES]: 'Soul of Fighting Thieves',
  [Items.MM_HAMMER]: 'Megaton Hammer (MM)',
  [Items.SHARED_HAMMER]: 'Megaton Hammer',
  [Items.MM_BOOMERANG]: 'Boomerang (MM)',
  [Items.SHARED_BOOMERANG]: 'Boomerang',
  [Items.SHARED_GREAT_FAIRY_SWORD]: "Great Fairy's Sword",
  [Items.MM_SLINGSHOT]: 'Fairy Slingshot (MM)',
  [Items.SHARED_SLINGSHOT]: 'Fairy Slingshot',
  [Items.MM_STICK_UPGRADE]: "Deku Stick Upgrade (MM)",
  [Items.MM_NUT_UPGRADE]: "Deku Nut Upgrade (MM)",
  [Items.SHARED_STICK_UPGRADE]: "Deku Stick Upgrade",
  [Items.SHARED_NUT_UPGRADE]: "Deku Nut Upgrade",
  [Items.OOT_BOMBCHU_BAG]: "Bombchu Bag (OoT)",
  [Items.MM_BOMBCHU_BAG]: "Bombchu Bag (MM)",
  [Items.SHARED_BOMBCHU_BAG]: "Bombchu Bag",
  [Items.OOT_SONG_NOTE_EPONA]: "Note from Epona's Song (OoT)",
  [Items.OOT_SONG_NOTE_SARIA]: "Note from Saria's Song (OoT)",
  [Items.OOT_SONG_NOTE_STORMS]: "Note from Song of Storms (OoT)",
  [Items.OOT_SONG_NOTE_SUN]: "Note from Sun's Song (OoT)",
  [Items.OOT_SONG_NOTE_TIME]: "Note from Song of Time (OoT)",
  [Items.OOT_SONG_NOTE_ZELDA]: "Note from Zelda's Lullaby (OoT)",
  [Items.OOT_SONG_NOTE_TP_FIRE]: "Note from Bolero of Fire (OoT)",
  [Items.OOT_SONG_NOTE_TP_FOREST]: "Note from Minuet of Forest (OoT)",
  [Items.OOT_SONG_NOTE_TP_LIGHT]: "Note from Prelude of Light (OoT)",
  [Items.OOT_SONG_NOTE_TP_SHADOW]: "Note from Nocturne of Shadow (OoT)",
  [Items.OOT_SONG_NOTE_TP_SPIRIT]: "Note from Requiem of Spirit (OoT)",
  [Items.OOT_SONG_NOTE_TP_WATER]: "Note from Serenade of Water (OoT)",
  [Items.OOT_SONG_NOTE_EMPTINESS]: "Note from Elegy of Emptiness (OoT)",
  [Items.OOT_SONG_NOTE_HEALING]: "Note from Song of Healing (OoT)",
  [Items.OOT_SONG_NOTE_SOARING]: "Note from Song of Soaring (OoT)",
  [Items.OOT_SONG_NOTE_AWAKENING]: "Note from Sonata of Awakening (OoT)",
  [Items.OOT_SONG_NOTE_GORON]: "Note from Goron Lullaby (OoT)",
  [Items.OOT_SONG_NOTE_ORDER]: "Note from Oath to Order (OoT)",
  [Items.OOT_SONG_NOTE_ZORA]: "Note from New Wave Bossa Nova (OoT)",
  [Items.MM_SONG_NOTE_AWAKENING]: "Note from Sonata of Awakening (MM)",
  [Items.MM_SONG_NOTE_EMPTINESS]: "Note from Elegy of Emptiness (MM)",
  [Items.MM_SONG_NOTE_EPONA]: "Note from Epona's Song (MM)",
  [Items.MM_SONG_NOTE_GORON]: "Note from Goron Lullaby (MM)",
  [Items.MM_SONG_NOTE_HEALING]: "Note from Song of Healing (MM)",
  [Items.MM_SONG_NOTE_ORDER]: "Note from Oath to Order (MM)",
  [Items.MM_SONG_NOTE_SOARING]: "Note from Song of Soaring (MM)",
  [Items.MM_SONG_NOTE_STORMS]: "Note from Song of Storms (MM)",
  [Items.MM_SONG_NOTE_TIME]: "Note from Song of Time (MM)",
  [Items.MM_SONG_NOTE_ZORA]: "Note from New Wave Bossa Nova (MM)",
  [Items.MM_SONG_NOTE_ZELDA]: "Note from Zelda's Lullaby (MM)",
  [Items.MM_SONG_NOTE_SARIA]: "Note from Saria's Song (MM)",
  [Items.MM_SONG_NOTE_SUN]: "Note from Sun's Song (MM)",
  [Items.MM_SONG_NOTE_TP_FIRE]: "Note from Bolero of Fire (MM)",
  [Items.MM_SONG_NOTE_TP_FOREST]: "Note from Minuet of Forest (MM)",
  [Items.MM_SONG_NOTE_TP_LIGHT]: "Note from Prelude of Light (MM)",
  [Items.MM_SONG_NOTE_TP_SHADOW]: "Note from Nocturne of Shadow (MM)",
  [Items.MM_SONG_NOTE_TP_SPIRIT]: "Note from Requiem of Spirit (MM)",
  [Items.MM_SONG_NOTE_TP_WATER]: "Note from Serenade of Water (MM)",
  [Items.SHARED_SONG_NOTE_EPONA]: "Note from Epona's Song",
  [Items.SHARED_SONG_NOTE_TIME]: "Note from Song of Time",
  [Items.SHARED_SONG_NOTE_STORMS]: "Note from Song of Storms",
  [Items.SHARED_SONG_NOTE_EMPTINESS]: "Note from Elegy of Emptiness",
  [Items.SHARED_SONG_NOTE_HEALING]: "Note from Song of Healing",
  [Items.SHARED_SONG_NOTE_SOARING]: "Note from Song of Soaring",
  [Items.SHARED_SONG_NOTE_AWAKENING]: "Note from Sonata of Awakening",
  [Items.SHARED_SONG_NOTE_GORON]: "Note from Goron Lullaby",
  [Items.SHARED_SONG_NOTE_ORDER]: "Note from Oath to Order",
  [Items.SHARED_SONG_NOTE_ZORA]: "Note from New Wave Bossa Nova",
  [Items.SHARED_SONG_NOTE_ZELDA]: "Note from Zelda's Lullaby",
  [Items.SHARED_SONG_NOTE_SARIA]: "Note from Saria's Song",
  [Items.SHARED_SONG_NOTE_SUN]: "Note from Sun's Song",
  [Items.SHARED_SONG_NOTE_TP_FIRE]: "Note from Bolero of Fire",
  [Items.SHARED_SONG_NOTE_TP_FOREST]: "Note from Minuet of Forest",
  [Items.SHARED_SONG_NOTE_TP_LIGHT]: "Note from Prelude of Light",
  [Items.SHARED_SONG_NOTE_TP_SHADOW]: "Note from Nocturne of Shadow",
  [Items.SHARED_SONG_NOTE_TP_SPIRIT]: "Note from Requiem of Spirit",
  [Items.SHARED_SONG_NOTE_TP_WATER]: "Note from Serenade of Water",
  [Items.SHARED_BOTTLE_POTION_RED]: "Bottle of Red Potion",
  [Items.SHARED_BOTTLE_POTION_GREEN]: "Bottle of Green Potion",
  [Items.SHARED_BOTTLE_POTION_BLUE]: "Bottle of Blue Potion",
  [Items.SHARED_BOTTLE_FAIRY]: "Bottled Fairy",
  [Items.SHARED_BOTTLE_POE]: "Bottled Poe",
  [Items.SHARED_BOTTLE_BIG_POE]: "Bottled Big Poe",
  [Items.SHARED_BOTTLE_BLUE_FIRE]: "Bottle of Blue Fire",
  [Items.SHARED_BOTTLE_MILK]: "Bottle of Milk",
  [Items.SHARED_BOTTLE_CHATEAU]: "Bottle of Chateau Romani",
  [Items.SHARED_BOTTLE_EMPTY]: "Empty Bottle",
  [Items.SHARED_BOTTLED_GOLD_DUST]: "Bottle of Gold Dust",
  [Items.SHARED_BOTTLE_RUTO_LETTER]: "Ruto's Letter",
  [Items.SHARED_POTION_RED]: "Red Potion",
  [Items.SHARED_POTION_GREEN]: "Green Potion",
  [Items.SHARED_POTION_BLUE]: "Blue Potion",
  [Items.SHARED_FAIRY]: "Fairy",
  [Items.SHARED_POE]: "Poe",
  [Items.SHARED_BIG_POE]: "Big Poe",
  [Items.SHARED_BLUE_FIRE]: "Blue Fire",
  [Items.SHARED_MILK]: "Milk",
  [Items.SHARED_CHATEAU]: "Chateau Romani Refill",
  [Items.SHARED_BUGS]: "Bugs",
  [Items.SHARED_FISH]: "Fish",
  [Items.MM_BLUE_FIRE]: "Blue Fire",
  [Items.OOT_BOTTLE_CHATEAU]: "Bottle of Chateau Romani",
  [Items.OOT_CHATEAU]: "Chateau Romani Refill",
  [Items.MM_BOTTLE_RUTO_LETTER]: "Ruto's Letter",
  [Items.OOT_BOTTLED_GOLD_DUST]: "Bottle of Gold Dust",
  [Items.MM_BOTTLE_BLUE_FIRE]: "Bottle of Blue Fire",
  [Items.OOT_SOUL_ANIMAL_CUCCO]: 'Soul of Cuccos (OoT)',
  [Items.OOT_SOUL_ANIMAL_COW]: 'Soul of Cows (OoT)',
  [Items.OOT_SOUL_ANIMAL_DOG]: 'Soul of Dogs (OoT)',
  [Items.OOT_SOUL_ANIMAL_BUTTERFLY]: 'Soul of Butterflies (OoT)',
  [Items.MM_SOUL_ANIMAL_CUCCO]: 'Soul of Cuccos (MM)',
  [Items.MM_SOUL_ANIMAL_COW]: 'Soul of Cows (MM)',
  [Items.MM_SOUL_ANIMAL_DOG]: 'Soul of Dogs (MM)',
  [Items.MM_SOUL_ANIMAL_BUTTERFLY]: 'Soul of Butterflies (MM)',
  [Items.SHARED_SOUL_ANIMAL_CUCCO]: 'Soul of Cuccos',
  [Items.SHARED_SOUL_ANIMAL_COW]: 'Soul of Cows',
  [Items.SHARED_SOUL_ANIMAL_DOG]: 'Soul of Dogs',
  [Items.SHARED_SOUL_ANIMAL_BUTTERFLY]: 'Soul of Butterflies',
  [Items.OOT_PLATINUM_TOKEN]: "Platinum Token (OoT)",
  [Items.MM_PLATINUM_TOKEN]: "Platinum Token (MM)",
  [Items.SHARED_PLATINUM_TOKEN]: "Platinum Token",
  [Items.OOT_RUSTY_KEY_TREASURE_CHEST_GAME]: "Rusty Key (Treasure Chest Game)",
  [Items.OOT_RUSTY_KEY_GUARD_HOUSE]: "Rusty Key (Guard House)",
  [Items.OOT_RUSTY_KEY_HYRULE_CASTLE]: "Rusty Key (Hyrule Castle)",
  [Items.OOT_RUSTY_KEY_DOG_LADY_HOUSE]: "Rusty Key (Dog Lady House)",
  [Items.OOT_RUSTY_KEY_BACK_ALLEY_HOUSE]: "Rusty Key (Back Alley House)",
  [Items.OOT_RUSTY_KEY_BOMBCHU_SHOP]: "Rusty Key (Bombchu Shop)",
  [Items.OOT_RUSTY_KEY_MASK_SHOP]: "Rusty Key (Mask Shop)",
  [Items.OOT_RUSTY_KEY_CHILD_BAZAAR]: "Rusty Key (Child Bazaar)",
  [Items.OOT_RUSTY_KEY_CHILD_POTION_SHOP]: "Rusty Key (Child Potion Shop)",
  [Items.OOT_RUSTY_KEY_CHILD_SHOOTING_GALLERY]: "Rusty Key (Child Shooting Gallery)",
  [Items.OOT_RUSTY_KEY_BOMBCHU_BOWLING]: "Rusty Key (Bombchu Bowling)",
  [Items.OOT_RUSTY_KEY_LABORATORY]: "Rusty Key (Laboratory)",
  [Items.OOT_RUSTY_KEY_FISHING_POND]: "Rusty Key (Fishing Pond)",
  [Items.OOT_RUSTY_KEY_SILO]: "Rusty Key (Silo)",
  [Items.OOT_RUSTY_KEY_RANCH_STABLE]: "Rusty Key (Ranch Stable)",
  [Items.OOT_RUSTY_KEY_RANCH_HOUSE]: "Rusty Key (Ranch House)",
  [Items.OOT_RUSTY_KEY_RANCH_HOUSE_ROOM]: "Rusty Key (Malon's Room)",
  [Items.OOT_RUSTY_KEY_GRAVEYARD]: "Rusty Key (Kakariko Graveyard Hut)",
  [Items.OOT_RUSTY_KEY_WINDMILL]: "Rusty Key (Windmill)",
  [Items.OOT_RUSTY_KEY_IMPA_HOUSE]: "Rusty Key (Impa's House)",
  [Items.OOT_RUSTY_KEY_CARPENTER_HOUSE]: "Rusty Key (Carpenter House)",
  [Items.OOT_RUSTY_KEY_GRANNY_POTION_SHOP]: "Rusty Key (Granny Potion Shop)",
  [Items.OOT_RUSTY_KEY_ADULT_SHOOTING_GALLERY]: "Rusty Key (Adult Shooting Gallery)",
  [Items.OOT_RUSTY_KEY_SKULLTULA_HOUSE]: "Rusty Key (Skulltula House)",
  [Items.OOT_RUSTY_KEY_ADULT_BAZAAR]: "Rusty Key (Adult Bazaar)",
  [Items.OOT_RUSTY_KEY_ADULT_POTION_SHOP]: "Rusty Key (Adult Potion Shop)",
  [Items.OOT_RUSTY_KEY_ADULT_POTION_SHOP_BACK]: "Rusty Key (Adult Potion Shop Back)",
  [Items.MM_RUSTY_KEY_TOURIST_INFORMATION]: "Rusty Key (Tourist Information)",
  [Items.MM_RUSTY_KEY_POTION_SHOP]: "Rusty Key (Potion Shop)",
  [Items.MM_RUSTY_KEY_POST_OFFICE]: "Rusty Key (Post Office)",
  [Items.MM_RUSTY_KEY_SWORDSMAN_SCHOOL]: "Rusty Key (Swordsman School)",
  [Items.MM_RUSTY_KEY_LOTTERY]: "Rusty Key (Lottery)",
  [Items.MM_RUSTY_KEY_BOMB_SHOP]: "Rusty Key (Bomb Shop)",
  [Items.MM_RUSTY_KEY_TRADING_POST]: "Rusty Key (Trading Post)",
  [Items.MM_RUSTY_KEY_CURIOSITY_SHOP]: "Rusty Key (Curiosity Shop)",
  [Items.MM_RUSTY_KEY_KAFEI_HIDEOUT]: "Rusty Key (Kafei's Hideout)",
  [Items.MM_RUSTY_KEY_TOWN_ARCHERY]: "Rusty Key (Town Archery)",
  [Items.MM_RUSTY_KEY_SWAMP_ARCHERY]: "Rusty Key (Swamp Archery)",
  [Items.MM_RUSTY_KEY_OBSERVATORY]: "Rusty Key (Observatory)",
  [Items.MM_RUSTY_KEY_BLACKSMITH]: "Rusty Key (Blacksmith)",
  [Items.MM_RUSTY_KEY_MUSIC_HOUSE]: "Rusty Key (Music House)",
  [Items.MM_RUSTY_KEY_LABORATORY]: "Rusty Key (Oceanic Laboratory)",
  [Items.MM_RUSTY_KEY_BENEATH_GRAVEYARD]: "Rusty Key (Beneath the Graveyard)",
  [Items.MM_RUSTY_KEY_DAMPE_HOUSE]: "Rusty Key (Dampe's House)",
  [Items.MM_RUSTY_KEY_MAYOR_RESIDENCE]: "Rusty Key (Mayor's Residence)",
  [Items.MM_RUSTY_KEY_MAYOR_RESIDENCE_OFFICE]: "Rusty Key (Mayor's Residence Office)",
  [Items.MM_RUSTY_KEY_MAYOR_RESIDENCE_SALON]: "Rusty Key (Mayor's Residence Salon)",
  [Items.MM_RUSTY_KEY_MAYOR_RESIDENCE_KAFEI]: "Rusty Key (Kafei's Room)",
  [Items.MM_RUSTY_KEY_TREASURE_CHEST_GAME]: "Rusty Key (Treasure Game)",
  [Items.MM_RUSTY_KEY_HONEY_DARLING]: "Rusty Key (Honey & Darling)",
  [Items.MM_RUSTY_KEY_MILK_BAR]: "Rusty Key (Milk Bar)",
  [Items.MM_RUSTY_KEY_DOG_RACETRACK]: "Rusty Key (Doggy Racetrack)",
  [Items.MM_RUSTY_KEY_CUCCO_SHACK]: "Rusty Key (Cucco Shack)",
  [Items.MM_RUSTY_KEY_RANCH_HOUSE]: "Rusty Key (Romani Ranch House)",
  [Items.MM_RUSTY_KEY_RANCH_BARN]: "Rusty Key (Romani Ranch Barn)",
  [Items.MM_RUSTY_KEY_RANCH_HOUSE_ROOM]: "Rusty Key (Romani's Room)",
  [Items.MM_RUSTY_KEY_ZORA_SHOP]: "Rusty Key (Zora Shop)",
  [Items.MM_RUSTY_KEY_ZORA_JAPAS_ROOM]: "Rusty Key (Japas' Room)",
  [Items.MM_RUSTY_KEY_ZORA_TIJO_ROOM]: "Rusty Key (Tijo's Room)",
  [Items.MM_RUSTY_KEY_ZORA_LULU_ROOM]: "Rusty Key (Lulu's Room)",
  [Items.MM_RUSTY_KEY_ZORA_EVAN_ROOM]: "Rusty Key (Evan's Room)",
  [Items.MM_RUSTY_KEY_STOCK_POT_INN]: "Rusty Key (Stock Pot Inn)",
  [Items.MM_RUSTY_KEY_STOCK_POT_INN_ROOF]: "Rusty Key (Stock Pot Inn Roof)",
  [Items.MM_RUSTY_KEY_GRANDMA_ROOM]: "Rusty Key (Grandma's Room)",
  [Items.MM_RUSTY_KEY_STOCK_POT_INN_STAFF_ROOM]: "Rusty Key (Stock Pot Inn Staff Room)",
  [Items.MM_RUSTY_KEY_STOCK_POT_INN_DORMITORY]: "Rusty Key (Stock Pot Inn Dormitory)",
  [Items.OOT_SHOVEL]: "Shovel (OoT)",
  [Items.MM_SHOVEL]: "Shovel (MM)",
  [Items.SHARED_SHOVEL]: "Shovel",
};

export function itemNiceName(item: ItemID) {
  if (ITEM_NAMES.hasOwnProperty(item)) {
    return ITEM_NAMES[item];
  } else {
    return Item.name(item);
  }
}
