import type { Settings } from '@ootmm/core';
import type { PartialDeep } from 'type-fest';
import { DEFAULT_SETTINGS, makeSettings, TRICKS } from '@ootmm/core';

export type Presets = { [k: string]: Settings };

const PRESET_DEFAULT = DEFAULT_SETTINGS;

const BLITZ_BASE: PartialDeep<Settings> = {
  hintPathBoss: true,
  hintPathEndBoss: true,
  hintPathEvents: true,
  clearStateDungeonsMm: {
    type: 'specific',
    values: ["WF", "GB"]
  },
  tingleShuffle: 'starting',
  openMaskShop: true,
  hintImportance: true,
  strayFairyChestShuffle: 'starting',
  mapCompassShuffle: 'starting',
  smallKeyShuffleMm: 'removed',
  smallKeyShuffleHideout: 'vanilla',
  bossKeyShuffleOot: 'ownDungeon',
  bossKeyShuffleMm: 'ownDungeon',
  shuffleMasterSword: true,
  shuffleGerudoCard: false,
  shuffleMerchantsMm: false,
  songEventsShuffleOot: true,
  songEventsShuffleMm: true,
  startingAgeOot: 'random',
  timeTravelSword: false,
  ageChange: 'always',
  doorOfTime: 'open',
  dekuTree: 'closed',
  kakarikoGate: 'open',
  beneathWell: 'remorseless',
  gerudoFortress: 'single',
  skipZelda: true,
  bossWarpPads: 'remains',
  crossAge: true,
  fastBunnyHood: true,
  bottleContentShuffle: true,
  sticksNutsUpgradesMm: true,
  blueFireArrows: true,
  iceArrowPlatformsOot: true,
  sunlightArrows: true,
  progressiveGoronLullabyMm: 'single',
  progressiveGoronLullabyOot: 'single',
  freeScarecrowOot: true,
  freeScarecrowMm: true,
  lenientSpikes: false,
  shortHookshotMm: true,
  bombchuBehaviorOot: 'bagSeparate',
  bombchuBehaviorMm: 'bagSeparate',
  spellFireMm: true,
  spellWindMm: true,
  spellLoveMm: true,
  hammerMm: true,
  boomerangMm: true,
  gfsOot: true,
  slingshotMm: true,
  spinUpgradeOot: true,
  extraChildSwordsOot: true,
  dekuShieldMm: true,
  sharedSwords: true,
  sharedNutsSticks: true,
  sharedBows: true,
  sharedBombBags: true,
  sharedMagic: true,
  sharedMagicArrowFire: true,
  sharedMagicArrowIce: true,
  sharedMagicArrowLight: true,
  sharedSongStorms: true,
  sharedHookshot: true,
  sharedLens: true,
  sharedMaskGoron: true,
  sharedMaskZora: true,
  sharedMaskBunny: true,
  sharedMaskKeaton: true,
  sharedMaskTruth: true,
  sharedWallets: true,
  sharedHealth: true,
  sharedShields: true,
  sharedBombchu: true,
  sharedSpellFire: true,
  sharedSpellWind: true,
  sharedSpellLove: true,
  sharedBottles: true,
  noPlandoHints: true,
  bootsIronMm: true,
  bootsHoverMm: true,
  tunicGoronMm: true,
  tunicZoraMm: true,
  sharedBootsIron: true,
  sharedBootsHover: true,
  sharedTunicGoron: true,
  sharedTunicZora: true,
  sharedHammer: true,
  sharedBoomerang: true,
  sharedGFS: true,
  sharedSlingshot: true,
  blastMaskOot: true,
  stoneMaskOot: true,
  kamaroMaskOot: true,
  elegyOot: true,
  songHealingOot: true,
  songSoaringOot: true,
  songAwakeningOot: true,
  songGoronOot: true,
  songZoraOot: true,
  songOrderOot: true,
  powderKegOot: true,
  sharedMaskBlast: true,
  sharedMaskStone: true,
  sharedMaskKamaro: true,
  sharedSongElegy: true,
  sharedSongHealing: true,
  sharedSongSoaring: true,
  sharedSongAwakening: true,
  sharedSongGoron: true,
  sharedSongZora: true,
  sharedSongOrder: true,
  songZeldaLullabyMm: true,
  songSariasMm: true,
  songMinuetMm: true,
  songBoleroMm: true,
  songSerenadeMm: true,
  songRequiemMm: true,
  songNocturneMm: true,
  songPreludeMm: true,
  sharedSongZeldaLullaby: true,
  sharedSongSarias: true,
  sharedSongMinuet: true,
  sharedSongBolero: true,
  sharedSongSerenade: true,
  sharedSongRequiem: true,
  sharedSongNocturne: true,
  sharedSongPrelude: true,
  sharedPowderKeg: true,
  agelessGFS: true,
  agelessChildTrade: true,
  mmSongOfDoubleTimeTimeSelector: true,
  agelessSoaring: true,
  scalesMm: true,
  strengthMm: true,
  kegStrength3: true,
  sharedScales: true,
  sharedStrength: true,
  keepItemsReset: true,
  mmEasierLightblock: true,
  shadowFastBoat: true,
  songOfDoubleTimeOot: true,
  sharedSpinUpgrade: true,
  trapIce: false,
  mmPreActivatedOwls: {
    type: 'specific',
    values: ["clocktown"]
  },
  startingItems: {
    SHARED_NUTS_10: 2,
    OOT_SHIELD_DEKU: 1,
    SHARED_STICK: 10,
    SHARED_SHIELD_DEKU: 1,
    MM_SONG_TIME: 1,
    MM_SONG_EPONA: 1,
    MM_OCARINA: 1,
    OOT_OCARINA: 1,
    SHARED_SONG_SOARING: 1
  },
  tricks: [
    "MM_EVAN_FARORE",
    "MM_KEG_RED_BOULDER",
    "MM_LENS",
    "MM_NO_SEAHORSE",
    "MM_ONE_MASK_STONE_TOWER",
    "MM_PALACE_BEAN_SKIP",
    "MM_SOUTHERN_SWAMP_SCRUB_HP_GORON",
    "MM_TUNICS",
    "MM_ZORA_HALL_SCRUB_HP_NO_DEKU",
    "OOT_DC_JUMP",
    "OOT_DEAD_HAND_STICKS",
    "OOT_FIRE_TEMPLE_BOSS_DOOR_ROLL_JUMP",
    "OOT_FOREST_HOOK",
    "OOT_HAMMER_WALLS",
    "OOT_HIDDEN_GROTTOS",
    "OOT_LENS",
    "OOT_MAN_ON_ROOF",
    "OOT_NIGHT_GS",
    "OOT_TUNICS",
    "OOT_VOLCANO_HOVERS",
    "OOT_WINDMILL_HP_NOTHING",
  ],
  plando: {
    songEvents: {
      oot: {
        SONG_EVENT_WINDMILL: { song: 'STORMS' },
        SONG_EVENT_ZORA_RIVER: { song: 'ZELDAS_LULLABY' },
        SONG_EVENT_GORON_CITY: { song: 'GORON_LULLABY' },
        SONG_EVENT_GREAT_FAIRY_SPELL_WIND: { song: 'NEW_WAVE' },
        SONG_EVENT_GREAT_FAIRY_SPELL_FIRE: { song: 'ZELDAS_LULLABY' },
        SONG_EVENT_GREAT_FAIRY_SPELL_LOVE: { song: 'ELEGY' },
        SONG_EVENT_GREAT_FAIRY_UPGRADE_MAGIC: { song: 'GORON_LULLABY' },
        SONG_EVENT_GREAT_FAIRY_UPGRADE_MAGIC2: { song: 'GORON_LULLABY' },
        SONG_EVENT_GREAT_FAIRY_UPGRADE_DEFENSE: { song: 'ZELDAS_LULLABY' },
        SONG_EVENT_TEMPLE_WATER: { song: 'NEW_WAVE' },
        SONG_EVENT_TEMPLE_SHADOW: { song: 'ZELDAS_LULLABY' },
        SONG_EVENT_TEMPLE_SPIRIT_STATUE: { song: 'ZELDAS_LULLABY' },
        SONG_EVENT_TEMPLE_SPIRIT_LOWER: { song: 'ZELDAS_LULLABY' },
        SONG_EVENT_TEMPLE_SPIRIT_HIGHER: { song: 'ZELDAS_LULLABY' },
        SONG_EVENT_TEMPLE_BOTW: { song: 'ZELDAS_LULLABY' },
        SONG_EVENT_TEMPLE_GANON: { song: 'ZELDAS_LULLABY' },
      },
      mm: {
        SONG_EVENT_TEMPLE_WOODFALL: { song: 'SONATA' },
        SONG_EVENT_TEMPLE_SNOWHEAD: { song: 'GORON_LULLABY' },
        SONG_EVENT_TEMPLE_GREATBAY: { song: 'NEW_WAVE' },
        SONG_EVENT_HEALING_DARMANI: { song: 'HEALING' },
        SONG_EVENT_HEALING_PAMELA_FATHER: { song: 'HEALING' },
        SONG_EVENT_HEALING_KAMARO: { song: 'HEALING' },
        SONG_EVENT_HEALING_MIKAU: { song: 'HEALING' },
        SONG_EVENT_AWAKENING_KEETA: { song: 'SONATA' },
        SONG_EVENT_LULLABY_KID: { song: 'GORON_LULLABY' },
        SONG_EVENT_STORMS_COMPOSER: { song: 'ZELDAS_LULLABY' },
        SONG_EVENT_CLOCK_TOWER_ROOF: { song: 'OATH' },
      }
    },
    locations: {
      'OOT Zora River Bean Seller': 'OOT_MAGIC_BEAN',
      'OOT Zelda\'s Letter': 'OOT_OCARINA',
      'OOT Zelda\'s Song': 'SHARED_SONG_TP_LIGHT',
      'MM Initial Song of Healing': 'SHARED_RECOVERY_HEART'
    }
  },
};

const makeBlitz = (input: PartialDeep<Settings>): Settings => {
  const x = Object.assign({}, BLITZ_BASE, input);
  return makeSettings(x);
};

const PRESET_BLITZ = makeBlitz({
  rainbowBridge: 'custom',
  moon: 'custom',
  specialConds: {
    BRIDGE: {
      count: 5,
      stones: true,
      medallions: true
    },
    MOON: {
      count: 4,
      stones: true,
      remains: true
    }
  },
  junkLocations: [
    'MM Deku Playground Reward All Days',
    'MM Beneath The Graveyard Dampe Chest',
    'MM Goron Race Reward',
    'MM Great Bay Great Fairy',
    'MM Honey & Darling Reward All Days',
    'MM Ikana Great Fairy',
    'MM Laboratory Zora Song',
    'MM Moon Fierce Deity Mask',
    'MM Mountain Village Frog Choir HP',
    'MM Ocean Spider House Wallet',
    'MM Pinnacle Rock HP',
    'MM Snowhead Great Fairy',
    'MM Stock Pot Inn Couple\'s Mask',
    'MM Swamp Spider House Mask of Truth',
    'MM Town Archery Reward 2',
    'MM Waterfall Rapids Beaver Race 2',
    'MM Woodfall Great Fairy',
    'OOT Hyrule Field Ocarina of Time',
    'OOT Kakariko Song Shadow',
    'OOT Skulltula House 40 Tokens',
    'OOT Skulltula House 50 Tokens'
  ],
  hints: [
    { type: "foolish", amount: 8, extra: 1 },
    { type: "always", amount: "max", extra: 1 },
    { type: "sometimes", amount: 4, extra: 1 },
    { type: "item", amount: 1, extra: 1, item: "SHARED_SHIELD_MIRROR" },
    { type: "item", amount: 1, extra: 1, item: "MM_MASK_CAPTAIN" },
    { type: "item", amount: 1, extra: 1, item: "SHARED_POWDER_KEG" },
    { type: "item", amount: 1, extra: 1, item: "OOT_SWORD_MASTER" },
    { type: "item", amount: 1, extra: 1, item: "SHARED_ARROW_ICE" },
    { type: "playthrough", amount: 1, extra: 1 },
    { type: "woth", amount: 9, extra: 1 },
    { type: "sometimes", amount: "max", extra: 1 }
  ]
});

const PRESET_BLITZ_PRECOMPLETED = makeBlitz({
  rainbowBridge: 'custom',
  moon: 'custom',
  preCompletedDungeons: true,
  preCompletedDungeonsMajor: 6,
  preCompletedDungeonsStones: 2,
  preCompletedDungeonsMedallions: 2,
  preCompletedDungeonsRemains: 2,
  junkLocations: [
    "MM Beneath The Graveyard Dampe Chest",
    "MM Deku Playground Reward All Days",
    "MM Goron Race Reward",
    "MM Great Bay Great Fairy",
    "MM Honey & Darling Reward All Days",
    "MM Ikana Great Fairy",
    "MM Laboratory Zora Song",
    "MM Moon Fierce Deity Mask",
    "MM Mountain Village Frog Choir HP",
    "MM Ocean Spider House Wallet",
    "MM Pinnacle Rock HP",
    "MM Snowhead Great Fairy",
    "MM Stock Pot Inn Couple's Mask",
    "MM Swamp Spider House Mask of Truth",
    "MM Town Archery Reward 2",
    "MM Waterfall Rapids Beaver Race 2",
    "MM Woodfall Great Fairy",
    "OOT Skulltula House 40 Tokens",
    "OOT Skulltula House 50 Tokens",
  ],
  specialConds: {
    BRIDGE: {
      count: 9,
      stones: true,
      medallions: true,
      remains: false,
    },
    MOON: {
      count: 7,
      stones: true,
      medallions: false,
      remains: true,
    }
  },
  hints: [
    { type: "foolish", amount: 8, extra: 1 },
    { type: "always", amount: "max", extra: 1 },
    { type: "sometimes", amount: 4, extra: 1 },
    { type: "item", amount: 1, extra: 1, item: "SHARED_SHIELD_MIRROR" },
    { type: "item", amount: 1, extra: 1, item: "MM_MASK_CAPTAIN" },
    { type: "item", amount: 1, extra: 1, item: "SHARED_POWDER_KEG" },
    { type: "item", amount: 1, extra: 1, item: "SHARED_ARROW_ICE" },
    { type: "item", amount: 1, extra: 1, item: "OOT_SWORD_MASTER" },
    { type: "woth", amount: 9, extra: 1 },
    { type: "sometimes", amount: "max", extra: 1 }
  ]
});

const PRESET_TRIFORCE_BLITZ = makeBlitz({
  goal: "triforce3",
  strayFairyChestShuffle: "starting",
  rainbowBridge: 'custom',
  moon: 'custom',
  preCompletedDungeons: true,
  preCompletedDungeonsMajor: 8,
  preCompletedDungeonsStones: 2,
  preCompletedDungeonsMedallions: 4,
  preCompletedDungeonsRemains: 2,
  junkLocations: [
    "MM Beneath The Graveyard Dampe Chest",
    "MM Deku Playground Reward All Days",
    "MM Goron Race Reward",
    "MM Great Bay Great Fairy",
    "MM Honey & Darling Reward All Days",
    "MM Ikana Great Fairy",
    "MM Laboratory Zora Song",
    "MM Moon Fierce Deity Mask",
    "MM Mountain Village Frog Choir HP",
    "MM Ocean Spider House Wallet",
    "MM Pinnacle Rock HP",
    "MM Snowhead Great Fairy",
    "MM Swamp Spider House Mask of Truth",
    "MM Town Archery Reward 2",
    "MM Waterfall Rapids Beaver Race 2",
    "MM Woodfall Great Fairy",
    "OOT Skulltula House 40 Tokens",
    "OOT Skulltula House 50 Tokens"
  ],
  specialConds: {
    BRIDGE: {
      count: 0
    },
    MOON: {
      count: 7,
      stones: true,
      remains: true
    }
  },
  hints: [
    { type: "foolish", amount: 8, extra: 1 },
    { type: "always", amount: "max", extra: 1 },
    { type: "sometimes", amount: 4, extra: 1 },
    { type: "item", amount: 1, extra: 1, item: "MM_MASK_CAPTAIN" },
    { type: "item", amount: 1, extra: 1, item: "SHARED_POWDER_KEG" },
    { type: "item", amount: 1, extra: 1, item: "SHARED_SHIELD_MIRROR" },
    { type: "item", amount: 1, extra: 1, item: "SHARED_ARROW_LIGHT" },
    { type: "item", amount: 1, extra: 1, item: "OOT_SWORD_MASTER" },
    { type: "woth", amount: 9, extra: 1 },
    { type: "sometimes", amount: "max", extra: 1 }
  ]
})

const ALLSANITY_HELL: PartialDeep<Settings> = {
  ageChange: 'oot',
  alterLostWoodsExits: true,
  blastMaskCooldown: 'short',
  blastMaskOot: true,
  blueFireArrows: true,
  bombchuBehaviorMm: 'bagSeparate',
  bombchuBehaviorOot: 'bagSeparate',
  boomerangMm: true,
  bootsHoverMm: true,
  bootsIronMm: true,
  bossKeyShuffleMm: 'anywhere',
  bossKeyShuffleOot: 'anywhere',
  bottleContentShuffle: true,
  bottomlessWallets: true,
  bronzeScale: true,
  childWallets: true,
  clocksOot: 'random',
  colossalWallets: true,
  cowShuffleMm: true,
  cowShuffleOot: true,
  crossAge: true,
  crossGameFw: true,
  dekuTree: 'closed',
  divingGameRupeeShuffle: true,
  doorOfTime: 'closed',
  eggShuffle: true,
  elegyOot: true,
  erBeneathWell: true,
  erBoss: 'full',
  erDungeons: 'full',
  erGanonCastle: true,
  erGanonTower: true,
  erGrottos: 'full',
  erIkanaCastle: true,
  erIndoors: 'full',
  erIndoorsExtra: true,
  erIndoorsGameLinks: true,
  erIndoorsMajor: true,
  erMajorDungeons: true,
  erMinorDungeons: true,
  erMixed: 'full',
  erMixedDungeons: true,
  erMixedGrottos: true,
  erMixedIndoors: true,
  erMixedOverworld: true,
  erMixedRegions: true,
  erMoon: true,
  erNoPolarity: true,
  erOneWays: 'full',
  erOneWaysAnywhere: true,
  erOneWaysIkana: true,
  erOneWaysMajor: true,
  erOneWaysOwls: true,
  erOneWaysSongs: true,
  erOneWaysStatues: true,
  erOneWaysWaterVoids: true,
  erOneWaysWoods: true,
  erOverworld: 'full',
  erPirateFortress: true,
  erPiratesWorld: true,
  erRegions: 'full',
  erRegionsExtra: true,
  erRegionsShortcuts: true,
  erSecretShrine: true,
  erSelfLoops: true,
  erSpawns: 'both',
  erSpiderHouses: true,
  erWallmasters: 'full',
  erWarps: 'full',
  extraChildSwordsOot: true,
  extraHintRegions: true,
  fairyFountainFairyShuffleMm: true,
  fairyFountainFairyShuffleOot: true,
  fairyOcarinaMm: true,
  fairySpotShuffleOot: true,
  fastBunnyHood: true,
  gfsOot: true,
  goldSkulltulaTokens: 'all',
  hammerMm: true,
  hintImportance: true,
  housesSkulltulaTokens: 'all',
  iceArrowPlatformsOot: true,
  kamaroMaskOot: true,
  logic: 'beatable',
  mapCompassShuffle: 'anywhere',
  moonCrash: 'cycle',
  mqDungeons: { type: 'random' },
  ocarinaButtonsShuffleMm: true,
  ocarinaButtonsShuffleOot: true,
  owlShuffle: 'anywhere',
  pondFishShuffle: true,
  powderKegOot: true,
  rainbowBridge: 'medallions',
  restoreBrokenActors: true,
  rupeeScaling: true,
  rustyKeysMm: true,
  rustyKeysOot: true,
  scalesMm: true,
  scrubShuffleMm: true,
  scrubShuffleOot: true,
  shadowFastBoat: true,
  shopShuffleMm: 'full',
  shopShuffleOot: 'full',
  shortHookshotMm: true,
  shovelMm: true,
  shovelOot: true,
  shuffleBarrelsMm: 'all',
  shuffleBouldersMm: 'all',
  shuffleBouldersOot: 'all',
  shuffleBushMm: 'all',
  shuffleBushOot: true,
  shuffleButterfliesMm: true,
  shuffleButterfliesOot: true,
  shuffleCratesMm: 'all',
  shuffleCratesOot: 'all',
  shuffleFreeHeartsMm: true,
  shuffleFreeHeartsOot: 'all',
  shuffleFreeRupeesMm: 'all',
  shuffleFreeRupeesOot: 'all',
  shuffleFrogsRupeesOot: true,
  shuffleGerudoCard: true,
  shuffleGrassMm: 'all',
  shuffleGrassOot: 'all',
  shuffleHivesMm: true,
  shuffleHivesOot: true,
  shuffleIciclesMm: true,
  shuffleIciclesOot: true,
  shuffleMaskTrades: true,
  shuffleMasterSword: true,
  shuffleMerchantsMm: true,
  shuffleMerchantsOot: true,
  shufflePotsMm: 'all',
  shufflePotsOot: 'all',
  shuffleRedBouldersMm: true,
  shuffleRedBouldersOot: true,
  shuffleRedIceOot: true,
  shuffleRocksMm: 'all',
  shuffleRocksOot: true,
  shuffleSilverBouldersOot: true,
  shuffleSkulltulaFinalReward: true,
  shuffleSnowballsMm: 'all',
  shuffleSoilMm: 'all',
  shuffleSoilOot: true,
  shuffleTFGrassMm: true,
  shuffleTreesMm: 'all',
  shuffleTreesOot: true,
  shuffleWonderItemsMm: true,
  shuffleWonderItemsOot: 'all',
  silverRupeeShuffle: 'anywhere',
  slingshotMm: true,
  smallKeyShuffleChestGame: 'anywhere',
  smallKeyShuffleHideout: 'anywhere',
  smallKeyShuffleMm: 'anywhere',
  smallKeyShuffleOot: 'anywhere',
  songAwakeningOot: true,
  songBoleroMm: true,
  songGoronOot: true,
  songHealingOot: true,
  songMinuetMm: true,
  songNocturneMm: true,
  songOfDoubleTimeOot: true,
  songOrderOot: true,
  songPreludeMm: true,
  songRequiemMm: true,
  songSerenadeMm: true,
  songSoaringOot: true,
  songSunMm: true,
  songZoraOot: true,
  soulsAnimalMm: true,
  soulsAnimalOot: true,
  soulsBossMm: true,
  soulsBossOot: true,
  soulsEnemyMm: true,
  soulsEnemyOot: true,
  soulsMiscMm: true,
  soulsMiscOot: true,
  soulsNpcMm: true,
  soulsNpcOot: true,
  spellFireMm: true,
  spellLoveMm: true,
  spellWindMm: true,
  spinUpgradeOot: true,
  startingAgeOot: 'random',
  sticksNutsUpgradesInitial: true,
  sticksNutsUpgradesMm: true,
  stoneAgonyMm: true,
  stoneMaskOot: true,
  strayFairyChestShuffle: 'anywhere',
  strayFairyOtherShuffle: 'anywhere',
  strengthMm: true,
  sunlightArrows: true,
  timeTravelSword: false,
  tingleShuffle: 'anywhere',
  townFairyShuffle: 'anywhere',
  trapRupoor: true,
  tunicGoronMm: true,
  tunicZoraMm: true,
  openDungeonsOot: {
    type: "specific",
    values: ["dekuTreeAdult", "wellAdult", "fireChild"]
  },
};

const PRESET_ALLSANITY = makeSettings({
  ...ALLSANITY_HELL,
  autoInvert: 'firstCycle',
  beneathWell: 'remorseless',
  bossWarpPads: 'remains',
  csmc: 'always',
  csmcCow: true,
  csmcHearts: true,
  csmcMapCompass: true,
  csmcSkulltula: true,
  dungeonRewardShuffle: 'dungeonBlueWarps',
  fillWallets: true,
  freeScarecrowMm: true,
  freeScarecrowOot: true,
  ganonBossKey: 'anywhere',
  kakarikoGate: 'vanilla',
  keepItemsReset: true,
  openMaskShop: true,
  openZdShortcut: true,
  priceMmShops: 'weighted',
  priceMmTingle: 'weighted',
  priceOotScrubs: 'weighted',
  priceOotShops: 'weighted',
  progressiveGoronLullabyMm: 'single',
  progressiveGoronLullabyOot: 'single',
  progressiveShieldsMm: 'separate',
  progressiveShieldsOot: 'separate',
  progressiveSwordsOot: 'separate',
  sharedBombBags: true,
  sharedBombchu: true,
  sharedBoomerang: true,
  sharedBootsHover: true,
  sharedBootsIron: true,
  sharedBottles: true,
  sharedBows: true,
  sharedGFS: true,
  sharedHammer: true,
  sharedHealth: true,
  sharedHookshot: true,
  sharedLens: true,
  sharedMagic: true,
  sharedMagicArrowFire: true,
  sharedMagicArrowIce: true,
  sharedMagicArrowLight: true,
  sharedMaskBlast: true,
  sharedMaskBunny: true,
  sharedMaskGoron: true,
  sharedMaskKamaro: true,
  sharedMaskKeaton: true,
  sharedMaskStone: true,
  sharedMaskTruth: true,
  sharedMaskZora: true,
  sharedNutsSticks: true,
  sharedOcarinaButtons: true,
  sharedPowderKeg: true,
  sharedScales: true,
  sharedShields: true,
  sharedSlingshot: true,
  sharedSongAwakening: true,
  sharedSongBolero: true,
  sharedSongElegy: true,
  sharedSongEpona: true,
  sharedSongGoron: true,
  sharedSongHealing: true,
  sharedSongMinuet: true,
  sharedSongNocturne: true,
  sharedSongOrder: true,
  sharedSongPrelude: true,
  sharedSongRequiem: true,
  sharedSongSerenade: true,
  sharedSongSoaring: true,
  sharedSongStorms: true,
  sharedSongSun: true,
  sharedSongTime: true,
  sharedSongZora: true,
  sharedSoulsEnemy: true,
  sharedSoulsMisc: true,
  sharedSoulsNpc: true,
  sharedSpellFire: true,
  sharedSpellLove: true,
  sharedSpellWind: true,
  sharedSpinUpgrade: true,
  sharedStoneAgony: true,
  sharedStrength: true,
  sharedSwords: true,
  sharedTunicGoron: true,
  sharedTunicZora: true,
  sharedWallets: true,
  silverRupeePouches: { type: 'random' },
  skipZelda: true,
  smallKeyRingMm: { type: 'random' },
  smallKeyRingOot: { type: 'random' },
  songs: 'anywhere',
  zoraKing: 'vanilla',
});

const allTricks = Object.keys(TRICKS).filter(k => !TRICKS[k].glitch);

const PRESET_HELL = makeSettings({
  ...ALLSANITY_HELL,
  clocksMm: true,
  clockSpeed: 'fast',
  csmc: 'never',
  dungeonRewardShuffle: 'dungeonsLimited',
  erDecoupled: true,
  erIndoorsTelescopes: true,
  ganonBossKey: 'custom',
  ganonTrials: { type: 'all' },
  itemPool: 'barren',
  jpLayouts: { type: 'random' },
  majoraChild: 'custom',
  priceMmShops: 'random',
  priceMmTingle: 'random',
  priceOotScrubs: 'random',
  priceOotShops: 'random',
  progressiveClocks: 'separate',
  progressiveGoronLullabyMm: 'progressive',
  progressiveGoronLullabyOot: 'progressive',
  progressiveShieldsMm: 'progressive',
  progressiveShieldsOot: 'progressive',
  progressiveSwordsOot: 'goron',
  songs: 'notes',
  trapAntiMagic: true,
  trapDrain: true,
  trapFire: true,
  trapIce: true,
  trapKnockback: true,
  trapShock: true,
  specialConds: {
    GANON_BK: {
      count: 268,
      stones: true,
      medallions: true,
      remains: true,
      skullsGold: true,
      skullsSwamp: true,
      skullsOcean: true,
      fairiesWF: true,
      fairiesSH: true,
      fairiesGB: true,
      fairiesST: true,
      fairyTown: true,
      masksRegular: true,
      masksTransform: true,
      masksOot: true
    },
    MAJORA: {
      count: 268,
      stones: true,
      medallions: true,
      remains: true,
      skullsGold: true,
      skullsSwamp: true,
      skullsOcean: true,
      fairiesWF: true,
      fairiesSH: true,
      fairiesGB: true,
      fairiesST: true,
      fairyTown: true,
      masksRegular: true,
      masksTransform: true,
      masksOot: true
    }
  },
  hints: [
    { type: 'foolish', amount: 'max', extra: 2 },
  ],
  tricks: allTricks,
});

const PRESET_CIRCLE9 = makeSettings({
  ...PRESET_HELL,
  menuNotebook: true,
  rupeeScaling: false,
  blastMaskCooldown: 'verylong',
});

const PRESET_BEGINNER = makeSettings({
  autoInvert: 'firstCycle',
  clearStateDungeonsMm: {
    type: 'specific',
    values: ["WF", "GB"]
  },
  hintImportance: true,
  tingleShuffle: 'starting',
  mapCompassShuffle: 'starting',
  smallKeyShuffleMm: 'removed',
  smallKeyShuffleHideout: 'vanilla',
  strayFairyChestShuffle: 'starting',
  shuffleGerudoCard: false,
  startingAgeOot: 'random',
  doorOfTime: 'open',
  dekuTree: 'closed',
  kakarikoGate: 'open',
  gerudoFortress: 'single',
  skipZelda: true,
  rainbowBridge: 'medallions',
  bossWarpPads: 'remains',
  freeScarecrowOot: true,
  freeScarecrowMm: true,
  openMaskShop: true,
  bottleContentShuffle: true,
  bombchuBehaviorOot: 'bagSeparate',
  bombchuBehaviorMm: 'bagSeparate',
  songSoaringOot: true,
  sharedBows: true,
  sharedBombBags: true,
  sharedMagic: true,
  sharedMagicArrowFire: true,
  sharedMagicArrowIce: true,
  sharedMagicArrowLight: true,
  sharedSongEpona: true,
  sharedSongStorms: true,
  sharedHookshot: true,
  sharedLens: true,
  sharedMaskGoron: true,
  sharedMaskZora: true,
  sharedMaskBunny: true,
  sharedMaskKeaton: true,
  sharedMaskTruth: true,
  sharedWallets: true,
  sharedHealth: true,
  sharedShields: true,
  sharedBombchu: true,
  sharedSongSoaring: true,
  songMinuetMm: true,
  songBoleroMm: true,
  songSerenadeMm: true,
  songRequiemMm: true,
  songNocturneMm: true,
  songPreludeMm: true,
  sharedSongMinuet: true,
  sharedSongBolero: true,
  sharedSongSerenade: true,
  sharedSongRequiem: true,
  sharedSongNocturne: true,
  sharedSongPrelude: true,
  agelessSoaring: true,
  startingItems: {
    OOT_NUTS_10: 2,
    OOT_SHIELD_DEKU: 1,
    OOT_STICK: 10,
    SHARED_SHIELD_HYLIAN: 1,
    MM_OCARINA: 1,
    OOT_OCARINA: 1,
    MM_SWORD: 2,
    SHARED_SONG_SOARING: 1
  },
  junkLocations: [
    'MM Beneath The Graveyard Dampe Chest',
    'MM Deku Playground Reward All Days',
    'MM Goron Race Reward',
    'MM Great Bay Great Fairy',
    'MM Honey & Darling Reward All Days',
    'MM Ikana Great Fairy',
    'MM Laboratory Zora Song',
    'MM Moon Fierce Deity Mask',
    'MM Mountain Village Frog Choir HP',
    'MM Ocean Spider House Wallet',
    'MM Pinnacle Rock HP',
    'MM Snowhead Great Fairy',
    "MM Stock Pot Inn Couple's Mask",
    'MM Swamp Spider House Mask of Truth',
    'MM Town Archery Reward 2',
    'MM Waterfall Rapids Beaver Race 2',
    'MM Woodfall Great Fairy',
    'OOT Skulltula House 40 Tokens',
    'OOT Skulltula House 50 Tokens'
  ],
  plando: {
    locations: {
      'OOT Zora River Bean Seller': 'OOT_MAGIC_BEAN',
      "OOT Zelda's Letter": 'OOT_OCARINA',
      "OOT Zelda's Song": 'SHARED_SONG_TP_LIGHT',
      'MM Initial Song of Healing': 'MM_SONG_TIME'
    }
  },
  hints: [
    { type: 'foolish', amount: 8, extra: 1 },
    { type: 'always', amount: 'max', extra: 1 },
    { type: 'sometimes', amount: 4, extra: 1 },
    { type: 'item', amount: 1, extra: 1, item: 'SHARED_SHIELD_MIRROR' },
    { type: 'item', amount: 1, extra: 1, item: 'SHARED_POWDER_KEG' },
    { type: 'item', amount: 1, extra: 1, item: 'MM_MASK_CAPTAIN' },
    { type: 'playthrough', amount: 1, extra: 1 },
    { type: 'woth', amount: 9, extra: 1 },
    { type: 'sometimes', amount: 'max', extra: 1 }
  ]
});

const PRESET_CROSSKEYS = makeSettings({
  goal: 'any',
  preCompletedDungeons: true,
  preCompletedDungeonsMajor: 3,
  hintPathEndBoss: true,
  hintPathEvents: true,
  noPlandoHints: false,
  extraHintRegions: true,
  hintImportance: true,
  cloakTraps: false,
  songs: 'anywhere',
  tingleShuffle: 'starting',
  mapCompassShuffle: 'anywhere',
  smallKeyShuffleOot: 'anywhere',
  smallKeyShuffleMm: 'anywhere',
  smallKeyShuffleHideout: 'anywhere',
  bossKeyShuffleOot: 'anywhere',
  bossKeyShuffleMm: 'anywhere',
  strayFairyChestShuffle: 'starting',
  strayFairyOtherShuffle: 'starting',
  ganonBossKey: 'anywhere',
  startingAgeOot: 'random',
  doorOfTime: 'open',
  ageChange: 'oot',
  openDungeonsOot: {
    type: "specific",
    values: ["dekuTreeAdult", "wellAdult", "fireChild"]
  },
  kakarikoGate: 'open',
  openZdShortcut: false,
  zoraKing: 'open',
  gerudoFortress: 'single',
  skipZelda: true,
  rainbowBridge: 'custom',
  majoraChild: 'custom',
  bossWarpPads: 'remains',
  freeScarecrowOot: true,
  freeScarecrowMm: true,
  openMaskShop: true,
  crossAge: true,
  crossGameFw: false,
  restoreBrokenActors: true,
  fillWallets: true,
  progressiveGoronLullabyMm: 'single',
  progressiveGoronLullabyOot: 'single',
  bottleContentShuffle: true,
  fairyOcarinaMm: true,
  blueFireArrows: true,
  sunlightArrows: true,
  shortHookshotMm: true,
  bombchuBehaviorOot: 'bagFirst',
  bombchuBehaviorMm: 'bagFirst',
  spellFireMm: true,
  spellWindMm: true,
  spellLoveMm: true,
  bootsIronMm: true,
  bootsHoverMm: true,
  tunicGoronMm: true,
  tunicZoraMm: true,
  scalesMm: true,
  strengthMm: true,
  kegStrength3: true,
  hammerMm: true,
  boomerangMm: true,
  gfsOot: true,
  slingshotMm: true,
  spinUpgradeOot: true,
  blastMaskOot: true,
  stoneMaskOot: true,
  kamaroMaskOot: true,
  elegyOot: true,
  songHealingOot: true,
  songSoaringOot: true,
  songAwakeningOot: true,
  songGoronOot: true,
  songZoraOot: true,
  songOrderOot: true,
  powderKegOot: true,
  lenientSpikes: false,
  sharedBows: true,
  sharedBombBags: true,
  sharedMagic: true,
  sharedMagicArrowFire: true,
  sharedMagicArrowIce: true,
  sharedMagicArrowLight: true,
  sharedSongEpona: true,
  sharedSongStorms: true,
  sharedSongTime: true,
  sharedSongSun: true,
  sharedHookshot: true,
  sharedLens: true,
  sharedOcarina: true,
  sharedMaskGoron: true,
  sharedMaskZora: true,
  sharedMaskKeaton: true,
  sharedMaskTruth: true,
  sharedMaskBlast: true,
  sharedMaskStone: true,
  sharedMaskKamaro: true,
  sharedSongElegy: true,
  sharedSongHealing: true,
  sharedSongSoaring: true,
  sharedSongAwakening: true,
  sharedSongGoron: true,
  sharedSongZora: true,
  sharedSongOrder: true,
  sharedPowderKeg: true,
  sharedWallets: true,
  sharedHealth: true,
  sharedShields: true,
  sharedBombchu: true,
  sharedSpellFire: true,
  sharedSpellWind: true,
  sharedSpellLove: true,
  sharedBootsIron: true,
  sharedBootsHover: true,
  sharedTunicGoron: true,
  sharedTunicZora: true,
  sharedScales: true,
  sharedStrength: true,
  sharedHammer: true,
  sharedBoomerang: true,
  sharedGFS: true,
  sharedSlingshot: true,
  sharedBottles: true,
  songMinuetMm: true,
  songBoleroMm: true,
  songSerenadeMm: true,
  songRequiemMm: true,
  songNocturneMm: true,
  songPreludeMm: true,
  sharedSongMinuet: true,
  sharedSongBolero: true,
  sharedSongSerenade: true,
  sharedSongRequiem: true,
  sharedSongNocturne: true,
  sharedSongPrelude: true,
  mmEasierLightblock: true,
  shadowFastBoat: true,
  songOfDoubleTimeOot: true,
  sharedSpinUpgrade: true,
  songSunMm: true,
  agelessSwords: true,
  agelessTunics: true,
  agelessBoots: true,
  agelessChildTrade: true,
  erDungeons: 'full',
  erGrottos: 'full',
  erMixed: 'full',
  erMixedDungeons: true,
  erMixedIndoors: true,
  erMixedGrottos: true,
  erMajorDungeons: true,
  erMinorDungeons: true,
  erGanonCastle: true,
  erMoon: true,
  erSpiderHouses: true,
  erPirateFortress: true,
  erBeneathWell: true,
  erIkanaCastle: true,
  erSecretShrine: true,
  erIndoors: 'full',
  erIndoorsMajor: true,
  erIndoorsExtra: true,
  erOneWays: 'full',
  erOneWaysMajor: true,
  extraChildSwordsOot: true,
  sharedSwords: true,
  startingItems: {
    OOT_NUTS_10: 2,
    OOT_MASK_BUNNY: 1,
    OOT_STICK: 10,
    MM_NUTS_10: 2,
    MM_STICK: 10,
    SHARED_SONG_SOARING: 1
  },
  moon: 'open',
  junkLocations: [
    'MM Beneath The Graveyard Dampe Chest',
    'MM Deku Playground Reward All Days',
    'MM Goron Race Reward',
    'MM Great Bay Great Fairy',
    'MM Honey & Darling Reward All Days',
    'MM Ikana Great Fairy',
    'MM Laboratory Zora Song',
    'MM Moon Fierce Deity Mask',
    'MM Mountain Village Frog Choir HP',
    'MM Ocean Spider House Wallet',
    'MM Pinnacle Rock HP',
    'MM Snowhead Great Fairy',
    "MM Stock Pot Inn Couple's Mask",
    'MM Swamp Spider House Mask of Truth',
    'MM Town Archery Reward 2',
    'MM Waterfall Rapids Beaver Race 2',
    'MM Woodfall Great Fairy',
    'OOT Hyrule Field Ocarina of Time',
    'OOT Kakariko Song Shadow',
    'OOT Skulltula House 40 Tokens',
    'OOT Skulltula House 50 Tokens'
  ],
  tricks: [
    'MM_EVAN_FARORE',
    'MM_LENS',
    'MM_NO_SEAHORSE',
    'MM_ONE_MASK_STONE_TOWER',
    'MM_PALACE_BEAN_SKIP',
    'MM_SOUTHERN_SWAMP_SCRUB_HP_GORON',
    'MM_ZORA_HALL_SCRUB_HP_NO_DEKU',
    'OOT_DC_JUMP',
    'OOT_DEAD_HAND_STICKS',
    'OOT_FOREST_HOOK',
    'OOT_HAMMER_WALLS',
    'OOT_HIDDEN_GROTTOS',
    'OOT_LENS',
    'OOT_MAN_ON_ROOF',
    'OOT_NIGHT_GS',
    'OOT_TUNICS',
    'OOT_VOLCANO_HOVERS',
    'OOT_WINDMILL_HP_NOTHING'
  ],
  specialConds: {
    BRIDGE: {
      count: 8,
      stones: true,
      medallions: true,
      remains: true,
      skullsGold: false,
      skullsSwamp: false,
      skullsOcean: false,
      fairiesWF: false,
      fairiesSH: false,
      fairiesGB: false,
      fairiesST: false,
      fairyTown: false,
      masksRegular: false,
      masksTransform: false,
      masksOot: false,
      triforce: false,
      coinsRed: false,
      coinsGreen: false,
      coinsBlue: false,
      coinsYellow: false
    },
    LACS: {
      count: 0,
      stones: false,
      medallions: false,
      remains: false,
      skullsGold: false,
      skullsSwamp: false,
      skullsOcean: false,
      fairiesWF: false,
      fairiesSH: false,
      fairiesGB: false,
      fairiesST: false,
      fairyTown: false,
      masksRegular: false,
      masksTransform: false,
      masksOot: false,
      triforce: false,
      coinsRed: false,
      coinsGreen: false,
      coinsBlue: false,
      coinsYellow: false
    },
    GANON_BK: {
      count: 0,
      stones: false,
      medallions: false,
      remains: false,
      skullsGold: false,
      skullsSwamp: false,
      skullsOcean: false,
      fairiesWF: false,
      fairiesSH: false,
      fairiesGB: false,
      fairiesST: false,
      fairyTown: false,
      masksRegular: false,
      masksTransform: false,
      masksOot: false,
      triforce: false,
      coinsRed: false,
      coinsGreen: false,
      coinsBlue: false,
      coinsYellow: false
    },
    MAJORA: {
      count: 8,
      stones: true,
      medallions: true,
      remains: true,
      skullsGold: false,
      skullsSwamp: false,
      skullsOcean: false,
      fairiesWF: false,
      fairiesSH: false,
      fairiesGB: false,
      fairiesST: false,
      fairyTown: false,
      masksRegular: false,
      masksTransform: false,
      masksOot: false,
      triforce: false,
      coinsRed: false,
      coinsGreen: false,
      coinsBlue: false,
      coinsYellow: false
    }
  },
  plando: { locations: { 'OOT Zora River Bean Seller': 'OOT_MAGIC_BEAN' } },
  hints: [
    { type: 'foolish', amount: 8, extra: 1 },
    { type: 'always', amount: 'max', extra: 1 },
    { type: 'sometimes', amount: 3, extra: 1 },
    { type: 'item', amount: 1, extra: 1, item: 'OOT_SWORD_MASTER' },
    { type: 'item', amount: 1, extra: 1, item: 'SHARED_SONG_TIME' },
    { type: 'item', amount: 1, extra: 1, item: 'MM_MASK_CAPTAIN' },
    { type: 'item', amount: 1, extra: 1, item: 'SHARED_SONG_STORMS' },
    { type: 'woth', amount: 10, extra: 1 },
    { type: 'playthrough', amount: 'max', extra: 1 },
  ]
});

const PRESET_ONLY_OOT = makeSettings({
  games: 'oot',
  goal: 'ganon',
  hintImportance: true,
  mapCompassShuffle: 'starting',
  shuffleMasterSword: false,
  shuffleGerudoCard: false,
  startingAgeOot: 'random',
  doorOfTime: 'open',
  dekuTree: 'closed',
  kakarikoGate: 'open',
  skipZelda: true,
  freeScarecrowOot: true,
  bottleContentShuffle: true,
  bombchuBehaviorOot: 'bagSeparate',
  startingItems: {
    OOT_NUTS_10: 2,
    OOT_SHIELD_DEKU: 1,
    OOT_STICK: 10,
    OOT_SHIELD_HYLIAN: 1,
    OOT_OCARINA: 1
  },
  specialConds: {
    BRIDGE: {
      count: 0,
      stones: false,
      medallions: false,
      remains: false,
      skullsGold: false,
      skullsSwamp: false,
      skullsOcean: false,
      fairiesWF: false,
      fairiesSH: false,
      fairiesGB: false,
      fairiesST: false,
      fairyTown: false,
      masksRegular: false,
      masksTransform: false,
      masksOot: false,
      triforce: false,
      coinsRed: false,
      coinsGreen: false,
      coinsBlue: false,
      coinsYellow: false
    },
    LACS: {
      count: 0,
      stones: false,
      medallions: false,
      remains: false,
      skullsGold: false,
      skullsSwamp: false,
      skullsOcean: false,
      fairiesWF: false,
      fairiesSH: false,
      fairiesGB: false,
      fairiesST: false,
      fairyTown: false,
      masksRegular: false,
      masksTransform: false,
      masksOot: false,
      triforce: false,
      coinsRed: false,
      coinsGreen: false,
      coinsBlue: false,
      coinsYellow: false
    },
    GANON_BK: {
      count: 5,
      stones: true,
      medallions: true,
      remains: false,
      skullsGold: false,
      skullsSwamp: false,
      skullsOcean: false,
      fairiesWF: false,
      fairiesSH: false,
      fairiesGB: false,
      fairiesST: false,
      fairyTown: false,
      masksRegular: false,
      masksTransform: false,
      masksOot: false,
      triforce: false,
      coinsRed: false,
      coinsGreen: false,
      coinsBlue: false,
      coinsYellow: false
    },
    MAJORA: {
      count: 4,
      stones: true,
      medallions: false,
      remains: true,
      skullsGold: false,
      skullsSwamp: false,
      skullsOcean: false,
      fairiesWF: false,
      fairiesSH: false,
      fairiesGB: false,
      fairiesST: false,
      fairyTown: false,
      masksRegular: false,
      masksTransform: false,
      masksOot: false,
      triforce: false,
      coinsRed: false,
      coinsGreen: false,
      coinsBlue: false,
      coinsYellow: false
    }
  },
  plando: {
    locations: {
      'OOT Zora River Bean Seller': 'OOT_MAGIC_BEAN',
      "OOT Zelda's Letter": 'OOT_OCARINA',
      "OOT Zelda's Song": 'OOT_SONG_TP_LIGHT'
    }
  },
  hints: [
    { type: 'foolish', amount: 3, extra: 1 },
    { type: 'always', amount: 'max', extra: 1 },
    { type: 'sometimes', amount: 7, extra: 1 },
    { type: 'item', amount: 1, extra: 1, item: 'OOT_MAGIC_UPGRADE' },
    { type: 'playthrough', amount: 1, extra: 1 },
    { type: 'woth', amount: 5, extra: 1 },
    { type: 'sometimes', amount: 'max', extra: 1 }
  ]
});

const PRESET_ONLY_MM = makeSettings({
  games: 'mm',
  goal: 'majora',
  hintImportance: true,
  tingleShuffle: 'starting',
  mapCompassShuffle: 'starting',
  strayFairyChestShuffle: 'starting',
  bossWarpPads: 'remains',
  bottleContentShuffle: true,
  bombchuBehaviorMm: 'bagSeparate',
  lenientSpikes: false,
  startingItems: { MM_SHIELD_HERO: 1, MM_OCARINA: 1, MM_SWORD: 1, MM_SONG_SOARING: 1 },
  freeScarecrowMm: true,
  junkLocations: [
    'MM Deku Playground Reward All Days',
    'MM Goron Race Reward',
    'MM Great Bay Great Fairy',
    'MM Honey & Darling Reward All Days',
    'MM Ikana Great Fairy',
    'MM Laboratory Zora Song',
    'MM Moon Fierce Deity Mask',
    'MM Moon Trial Deku HP',
    'MM Moon Trial Goron HP',
    'MM Moon Trial Link Garo Master Chest',
    'MM Moon Trial Link HP',
    'MM Moon Trial Link Iron Knuckle Chest',
    'MM Moon Trial Zora HP',
    'MM Mountain Village Frog Choir HP',
    'MM Snowhead Great Fairy',
    "MM Stock Pot Inn Couple's Mask",
    'MM Town Archery Reward 2',
    'MM Waterfall Rapids Beaver Race 2',
    'MM Woodfall Great Fairy'
  ],
  specialConds: {
    BRIDGE: {
      count: 0,
      stones: false,
      medallions: false,
      remains: false,
      skullsGold: false,
      skullsSwamp: false,
      skullsOcean: false,
      fairiesWF: false,
      fairiesSH: false,
      fairiesGB: false,
      fairiesST: false,
      fairyTown: false,
      masksRegular: false,
      masksTransform: false,
      masksOot: false,
      triforce: false,
      coinsRed: false,
      coinsGreen: false,
      coinsBlue: false,
      coinsYellow: false
    },
    LACS: {
      count: 0,
      stones: false,
      medallions: false,
      remains: false,
      skullsGold: false,
      skullsSwamp: false,
      skullsOcean: false,
      fairiesWF: false,
      fairiesSH: false,
      fairiesGB: false,
      fairiesST: false,
      fairyTown: false,
      masksRegular: false,
      masksTransform: false,
      masksOot: false,
      triforce: false,
      coinsRed: false,
      coinsGreen: false,
      coinsBlue: false,
      coinsYellow: false
    },
    GANON_BK: {
      count: 5,
      stones: true,
      medallions: true,
      remains: false,
      skullsGold: false,
      skullsSwamp: false,
      skullsOcean: false,
      fairiesWF: false,
      fairiesSH: false,
      fairiesGB: false,
      fairiesST: false,
      fairyTown: false,
      masksRegular: false,
      masksTransform: false,
      masksOot: false,
      triforce: false,
      coinsRed: false,
      coinsGreen: false,
      coinsBlue: false,
      coinsYellow: false
    },
    MAJORA: {
      count: 4,
      stones: true,
      medallions: false,
      remains: true,
      skullsGold: false,
      skullsSwamp: false,
      skullsOcean: false,
      fairiesWF: false,
      fairiesSH: false,
      fairiesGB: false,
      fairiesST: false,
      fairyTown: false,
      masksRegular: false,
      masksTransform: false,
      masksOot: false,
      triforce: false,
      coinsRed: false,
      coinsGreen: false,
      coinsBlue: false,
      coinsYellow: false
    }
  },
  plando: {
    locations: {
      'MM Initial Song of Healing': 'MM_SONG_TIME'
    }
  },
  hints: [
    { type: 'foolish', amount: 3, extra: 1 },
    { type: 'always', amount: 'max', extra: 1 },
    { type: 'item', amount: 1, extra: 2, item: 'MM_SHIELD_MIRROR' },
    { type: 'item', amount: 1, extra: 1, item: 'MM_POWDER_KEG' },
    { type: 'item', amount: 1, extra: 1, item: 'MM_MASK_CAPTAIN' },
    { type: 'woth', amount: 3, extra: 1 },
    { type: 'sometimes', amount: 'max', extra: 1 }
  ]
});

export const PRESETS: Presets = {
  'Default': PRESET_DEFAULT,
  'Beginner': PRESET_BEGINNER,
  'Blitz': PRESET_BLITZ,
  'Blitz (with pre-completed dungeons)': PRESET_BLITZ_PRECOMPLETED,
  'Triforce Blitz': PRESET_TRIFORCE_BLITZ,
  'Crosskeys': PRESET_CROSSKEYS,
  'Allsanity': PRESET_ALLSANITY,
  'Hell': PRESET_HELL,
  'Circle 9': PRESET_CIRCLE9,
  'Only OoT': PRESET_ONLY_OOT,
  'Only MM': PRESET_ONLY_MM,
};
