#ifndef COMBO_MM_SCENE_H
#define COMBO_MM_SCENE_H

#define SCE_SOUTHERN_SWAMP_CLEAR                0x00
#define SCE_GROTTOS                             0x07
#define SCE_CUTSCENE_MAP                        0x08
#define SCE_POTION_SHOP                         0x0a
#define SCE_LAIR_MAJORA                         0x0b
#define SCE_BENEATH_THE_GRAVEYARD               0x0c
#define SCE_CURIOSITY_SHOP                      0x0d
#define SCE_RANCH_HOUSE_BARN                    0x10
#define SCE_HONEY_DARLING                       0x11
#define SCE_MAYOR_HOUSE                         0x12
#define SCE_IKANA_CANYON                        0x13
#define SCE_PIRATE_FORTRESS                     0x14
#define SCE_MILK_BAR                            0x15
#define SCE_STONE_TOWER_TEMPLE                  0x16
#define SCE_TREASURE_SHOP                       0x17
#define SCE_STONE_TOWER_TEMPLE_INVERTED         0x18
#define SCE_CLOCK_TOWER_ROOFTOP                 0x19
#define SCE_OPENING                             0x1a
#define SCE_WOODFALL_TEMPLE                     0x1b
#define SCE_PATH_MOUNTAIN_VILLAGE               0x1c
#define SCE_ANCIENT_CASTLE_IKANA                0x1d
#define SCE_DEKU_SCRUB_PLAYGROUND               0x1e
#define SCE_LAIR_ODOLWA                         0x1f
#define SCE_SHOOTING_GALLERY                    0x20
#define SCE_SNOWHEAD_TEMPLE                     0x21
#define SCE_MILK_ROAD                           0x22
#define SCE_PIRATE_FORTRESS_INTERIOR            0x23
#define SCE_SHOOTING_GALLERY_SWAMP              0x24
#define SCE_PINNACLE_ROCK                       0x25
#define SCE_FAIRY_FOUNTAIN                      0x26
#define SCE_SPIDER_HOUSE_SWAMP                  0x27
#define SCE_SPIDER_HOUSE_OCEAN                  0x28
#define SCE_OBSERVATORY                         0x29
#define SCE_MOON_DEKU                           0x2a
#define SCE_DEKU_PALACE                         0x2b
#define SCE_BLACKSMITH	                        0x2c
#define SCE_TERMINA_FIELD                       0x2d
#define SCE_POST_OFFICE                         0x2e
#define SCE_LABORATORY                          0x2f
#define SCE_DAMPE_HOUSE                         0x30
#define SCE_GORON_SHRINE                        0x32
#define SCE_ZORA_HALL                           0x33
#define SCE_TRADING_POST                        0x34
#define SCE_ROMANI_RANCH                        0x35
#define SCE_LAIR_TWINMOLD                       0x36
#define SCE_GREAT_BAY_COAST                     0x37
#define SCE_ZORA_CAPE                           0x38
#define SCE_LOTTERY	                            0x39
#define SCE_PIRATE_FORTRESS_EXTERIOR            0x3b
#define SCE_FISHERMAN_HUT	                    0x3c
#define SCE_GORON_SHOP                          0x3d
#define SCE_DEKU_KING_CHAMBER                   0x3e
#define SCE_MOON_GORON                          0x3f
#define SCE_ROAD_SOUTHERN_SWAMP                 0x40
#define SCE_DOG_RACETRACK                       0x41
#define SCE_CUCCO_SHACK                         0x42
#define SCE_IKANA_GRAVEYARD                     0x43
#define SCE_LAIR_GOHT                           0x44
#define SCE_SOUTHERN_SWAMP_POISONED             0x45
#define SCE_WOODFALL                            0x46
#define SCE_MOON_ZORA                           0x47
#define SCE_GORON_VILLAGE_SPRING                0x48
#define SCE_GREAT_BAY_TEMPLE                    0x49
#define SCE_WATERFALL_RAPIDS                    0x4a
#define SCE_BENEATH_THE_WELL                    0x4b
#define SCE_ZORA_HALL_ROOMS                     0x4c
#define SCE_GORON_VILLAGE_WINTER                0x4d
#define SCE_GORON_GRAVEYARD                     0x4e
#define SCE_SAKON_HIDEOUT                       0x4f
#define SCE_MOUNTAIN_VILLAGE_WINTER             0x50
#define SCE_GHOST_HUT                           0x51
#define SCE_DEKU_SHRINE                         0x52
#define SCE_ROAD_IKANA                          0x53
#define SCE_SWORDSMAN_SCHOOL                    0x54
#define SCE_MUSIC HOUSE	MUSIC BOX HOUSE         0x55
#define SCE_LAIR_IKANA                          0x56
#define SCE_TOURIST_INFORMATION                 0x57
#define SCE_STONE_TOWER                         0x58
#define SCE_STONE_TOWER_INVERTED                0x59
#define SCE_MOUNTAIN_VILLAGE_SPRING             0x5a
#define SCE_PATH_SNOWHEAD                       0x5b
#define SCE_SNOWHEAD                            0x5c
#define SCE_PATH_GORON_VILLAGE_WINTER           0x5d
#define SCE_PATH_GORON_VILLAGE_SPRING           0x5e
#define SCE_LAIR_GYORG                          0x5f
#define SCE_SECRET_SHRINE                       0x60
#define SCE_STOCK_POT_INN                       0x61
#define SCE_GREAT_BAY_CUTSCENE                  0x62
#define SCE_CLOCK_TOWER_INTERIOR                0x63
#define SCE_WOODS_MYSTERY                       0x64
#define SCE_LOST_WOODS                          0x65
#define SCE_MOON_LINK                           0x66
#define SCE_MOON                                0x67
#define SCE_BOMB_SHOP                           0x68
#define SCE_GIANT_CHAMBER                       0x69
#define SCE_GORMAN_TRACK                        0x6a
#define SCE_GORON_RACETRACK                     0x6b
#define SCE_CLOCK_TOWN_EAST                     0x6c
#define SCE_CLOCK_TOWN_WEST                     0x6d
#define SCE_CLOCK_TOWN_NORTH                    0x6e
#define SCE_CLOCK_TOWN_SOUTH                    0x6f
#define SCE_LAUNDRY_POOL                        0x70

#endif
