import type { ItemID } from './defs';

import * as ItemGroups from './groups';
import { Items } from './defs';

export const isCompass = (item: ItemID) => ItemGroups.COMPASSES.has(item);
export const isMap = (item: ItemID) => ItemGroups.MAPS.has(item);
export const isMapCompass = (item: ItemID) => isMap(item) || isCompass(item);
export const isSong = (item: ItemID) => ItemGroups.SONGS.has(item);
export const isSmallKey = (item: ItemID) => isSmallKeyRegular(item) || isSmallKeyHideout(item) || isSmallKeyTCG(item);
export const isSmallKeyHideout = (item: ItemID) => item === Items.OOT_SMALL_KEY_GF;
export const isSmallKeyTCG = (item: ItemID) => item === Items.OOT_SMALL_KEY_TCG;
export const isSmallKeyRegularOot = (item: ItemID) => ItemGroups.SMALL_KEYS_OOT.has(item);
export const isSmallKeyRegularMm = (item: ItemID) => ItemGroups.SMALL_KEYS_MM.has(item);
export const isSmallKeyRegular = (item: ItemID) => isSmallKeyRegularOot(item) || isSmallKeyRegularMm(item);
export const isKeyRing = (item: ItemID) => isKeyRingRegular(item) || isKeyRingHideout(item) || isKeyRingTCG(item);
export const isKeyRingHideout = (item: ItemID) => item === Items.OOT_KEY_RING_GF;
export const isKeyRingTCG = (item: ItemID) => item === Items.OOT_KEY_RING_TCG;
export const isKeyRingRegularOot = (item: ItemID) => ItemGroups.KEY_RINGS_OOT.has(item);
export const isKeyRingRegularMm = (item: ItemID) => ItemGroups.KEY_RINGS_MM.has(item);
export const isKeyRingRegular = (item: ItemID) => isKeyRingRegularOot(item) || isKeyRingRegularMm(item);
export const isGanonBossKey = (item: ItemID) => item === Items.OOT_BOSS_KEY_GANON;
export const isBossKey = (item: ItemID) => isRegularBossKey(item) || isGanonBossKey(item);
export const isRegularBossKeyOot = (item: ItemID) => ItemGroups.BOSS_KEYS_OOT.has(item);
export const isRegularBossKeyMm = (item: ItemID) => ItemGroups.BOSS_KEYS_MM.has(item);
export const isRegularBossKey = (item: ItemID) => isRegularBossKeyOot(item) || isRegularBossKeyMm(item);
export const isStrayFairy = (item: ItemID) => isTownStrayFairy(item) || isDungeonStrayFairy(item);
export const isTownStrayFairy = (item: ItemID) => item === Items.MM_STRAY_FAIRY_TOWN;
export const isDungeonStrayFairy = (item: ItemID) => ItemGroups.STRAY_FAIRIES_DUNGEON.has(item);
export const isKey = (item: ItemID) => isSmallKey(item) || isBossKey(item) || isKeyRing(item);
export const isDungeonItem = (item: ItemID) => isMapCompass(item) || isKey(item) || isStrayFairy(item) || isSilverRupee(item);
export const isDungeonReward = (item: ItemID) => ItemGroups.DUNGEON_REWARDS.has(item);
export const isItemMajor = (item: ItemID) => ItemGroups.REQUIRED.has(item);
export const isGoldToken = (item: ItemID) => item === Items.OOT_GS_TOKEN;
export const isHouseToken = (item: ItemID) => item === Items.MM_GS_TOKEN_SWAMP || item === Items.MM_GS_TOKEN_OCEAN;
export const isToken = (item: ItemID) => isGoldToken(item) || isHouseToken(item);
export const isMasterSword = (item: ItemID) => item === Items.OOT_SWORD_MASTER;
export const isGerudoCard = (item: ItemID) => item === Items.OOT_GERUDO_CARD;
export const isItemConsumable = (item: ItemID) => ItemGroups.CONSUMABLES.has(item);
export const isRupees = (item: ItemID) => ItemGroups.RUPEES.has(item);
export const isItemUnlimitedStarting = (item: ItemID) => isRupees(item) || isItemConsumable(item);
export const isItemCriticalRenewable = (item: ItemID) => ItemGroups.CRITICAL_RENEWABLES.has(item);
export const isTingleMap = (item: ItemID) => ItemGroups.TINGLE_MAPS.has(item);
export const isOwlStatue = (item: ItemID) => ItemGroups.OWLS.has(item);
export const isTriforcePiece = (item: ItemID) => ItemGroups.TRIFORCE.has(item);
export const isSilverRupee = (item: ItemID) => ItemGroups.RUPEES_SILVER.has(item);
export const isNamedTriforce = (item: ItemID) => ItemGroups.NAMED_TRIFORCE.has(item);
export const isFishingPondFish = (item: ItemID) => ItemGroups.FISHING_POND_FISH.has(item);
export const isSongNote = (item: ItemID) => ItemGroups.SONG_NOTES.has(item);
