export const TRICKS = {
  OOT_LENS: "Fewer Lens Requirements (OoT)",
  OOT_TUNICS: "Fewer Tunic Requirements",
  OOT_HIDDEN_GROTTOS: "Hidden Grottos (OoT) without Stone of Agony",
  OOT_MIDO_SKIP: "Backflip Over Mido",
  OOT_MAN_ON_ROOF: "Man on Roof with Nothing",
  OOT_BLIND_WASTELAND: "Blind Wasteland Crossing",
  OOT_DEKU_SKIP: "Deku Tree B1 Skip",
  OOT_DC_JUMP: "Dodongo's Cavern Upper Adult Jump",
  OOT_FOREST_HOOK: "Forest Temple Garden Vines with Hookshot",
  OOT_HAMMER_WALLS: "Hammer Through Walls",
  OOT_VOLCANO_HOVERS: "Volcano Item with Hover Boots",
  OOT_NIGHT_GS: "Nighttime Gold Skulltulas without Sun's Song",
  OOT_DOMAIN_CUCCO: "Enter Child Zora's Domain with Cucco",
  OOT_DOMAIN_HOVER: "Enter Zora's Domain using Hover Boots",
  OOT_WATER_LONGSHOT: "Drain Water Temple using Longshot",
  OOT_SAND_RIVER_NOTHING: "Cross the River of Sand with Nothing",
  OOT_SHADOW_FIRE_ARROW: "Enter Shadow Temple using Fire Arrows",
  OOT_KZ_SKIP: "Skip King Zora as Adult",
  OOT_LOST_WOODS_ADULT_GS: "Lost Woods Adult GS without Bean",
  OOT_WINDMILL_HP_NOTHING: "Windmill HP as Adult with Nothing",
  OOT_LAB_DIVE_NO_GOLD_SCALE: "Laboratory Dive without Gold Scale",
  OOT_LAB_WALL_GS: "Laboratory Wall GS with Jump Slash",
  OOT_PASS_COLLISION: "Pass through Visible One-Way Collisions",
  OOT_DMT_RED_ROCK_GS: "DMT Red Rock Skulls without Hammer",
  OOT_DEAD_HAND_STICKS: "Child Dead Hand without Kokiri Sword",
  OOT_BFA_MUDWALLS: "Break Mud Walls with Blue Fire Arrows",
  OOT_JABU_BOSS_HOVER: "Access Jabu-Jabu Pre-Boss using Hover Boots",
  OOT_SPIRIT_CHILD_HOVER: "Access Adult Spirit as Child using Hover Boots",
  OOT_VALLEY_GATE_HOVER: "Reach Gerudo Fortress as Child using Hover Boots",
  OOT_MQ_ICE_SCARE_NOTHING: "MQ Ice Cavern GS without Scarecrow or Hover Boots",
  OOT_MQ_ICE_SCARE_HOVER: "MQ Ice Cavern GS using only Hover Boots",
  OOT_MQ_GTG_FLAMES: "MQ Gerudo Training Grounds Lava Room Walk along Flame Circles",
  OOT_FORTRESS_JUMPS: "Jump up to higher ledges outside Gerudo Fortress",
  OOT_COLOSSUS_GS_NO_BEAN: "Desert Colossus Plateau GS without Bean Plant",
  OOT_ENTER_JABU: "Enter Jabu-Jabu with Head Collision",
  OOT_JABU_BOSS_HIGH_SWITCH: "Jabu Boss Switch without Boomerang or Climb Anywhere",
  OOT_WATER_REVERSE_RIVER: "Water Temple Reverse River with Hookshot Anywhere",
  OOT_WATER_PIT_GS_CHU: "Water Temple Large Pit GS with Bombchus",
  OOT_SHADOW_BOAT_EARLY: "Reach Shadow Temple Boat with Climb Anywhere",
  OOT_SPIRIT_BOSS_CLIMB_NO_HOOK: "Reach Twinrova using Climb Anywhere and Hover Boots",
  OOT_DC_BOULDER: "Skip Dodongo Cavern's Boulder using Ageless Hookshot Anywhere",
  OOT_LAKE_SHORTCUT: "Move Between Lake Hylia and Zora's Domain with Ageless Hookshot Anywhere",
  OOT_JJB_BOXLESS: "Access Jabu-Jabu pre-boss without the box",
  OOT_TENT_CHILD: "Enter the Gerudo Valley Tent as Child",
  OOT_WELL_ADULT_TT: "Enter Bottom of the Well as Adult with Time Travel",
  OOT_ADULT_GALLERY_TT: "Enter Adult Shooting Gallery as Child with Time Travel",
  OOT_GTG_CHILD_TT: "Enter Gerudo Training Grounds as Child with Time Travel",
  OOT_REVERSE_DAMPE: "Navigate Dampe's Grave in Reverse",
  OOT_GANON_FAIRY_TT: "Ganon's Great Fairy with Age Swap and without Gold Gauntlets",
  OOT_GANON_CASTLE_ENTRY: "Enter Ganon's Castle with Longshot Anywhere",
  OOT_SHADOW_TEMPLE_STICKS: "Enter Shadow Temple with Sticks & Fire Arrows",
  MM_LENS: "Fewer Lens Requirements (MM)",
  MM_PALACE_BEAN_SKIP: "Skip Planting Beans in Deku Palace",
  MM_DARMANI_WALL: "Climb Mountain Village Wall Blind",
  MM_NO_SEAHORSE: "Pinnacle Rock without Seahorse",
  MM_ZORA_HALL_HUMAN: "Swim to Zora Hall as Human",
  MM_ICELESS_IKANA: "Climb Ikana Canyon without Ice Arrows",
  MM_ONE_MASK_STONE_TOWER: "Climb Stone Tower with One Mask",
  MM_ISTT_EYEGORE: "Inverted Stone Tower Temple Eyegore Skips",
  MM_SCT_NOTHING: "South Clock Town Chest with Nothing",
  MM_GORON_BOMB_JUMP: "Bomb Jump Fences as Goron",
  MM_BOMBER_SKIP: "Guess Bomber Code",
  MM_CAPTAIN_SKIP: "Guess Oceanside Spider House Code",
  MM_ISTT_ENTRY_JUMP: "Inverted Stone Tower Temple Long Jump to Death Armos",
  MM_SHORT_HOOK_HARD: "Precise Short Hookshot Usage",
  MM_PFI_BOAT_HOOK: "Enter Pirate Fortress Interior using Hookshot from the Boats",
  MM_PALACE_GUARD_SKIP: "Backflip over Deku Palace Guards",
  MM_SHT_FIRELESS: "Complete Snowhead Temple without Fire Arrows",
  MM_SHT_STICKS_RUN: "Access SHT Pillar Fireless with Precise Stick Run",
  MM_SHT_PILLARLESS: "Snowhead Temple Skip Raising Pillar",
  MM_KEG_EXPLOSIVES: "Use Powder Kegs as Explosives",
  MM_DOG_RACE_CHEST_NOTHING: "Doggy Racetrack Chest with Nothing",
  MM_MAJORA_LOGIC: "Fight Majora to Reset Time",
  MM_SOUTHERN_SWAMP_SCRUB_HP_GORON: "Southern Swamp Scrub HP as Goron",
  MM_ZORA_HALL_SCRUB_HP_NO_DEKU: "Zora Hall Scrub HP without Deku",
  MM_IKANA_ROOF_PARKOUR: "Jump from Ikana Castle's Roof Interior to Exterior",
  MM_POST_OFFICE_GAME: "Post Office Timing Game without Bunny Hood",
  MM_WELL_HSW: "Well's Hot Spring Water without Killing Dexihand",
  MM_ISTT_CHUCHU_LESS: "ISTT Block Room without Chuchu jellies",
  MM_GBT_WATERWHEEL_GORON: "Cross GBT WaterWheel Room as Goron",
  MM_GBT_ENTRANCE_BOW: "Great Bay Temple Entrance Chest using only Bow",
  MM_OOB_MOVEMENT: "Walk Along Surfaces Out of Bounds",
  MM_ST_UPDRAFTS: "Stone Tower Updrafts without Deku Mask",
  MM_ESCAPE_CAGE: "Escape the Monkey Cage with Hookshot Anywhere",
  MM_GBT_FAIRY2_HOOK: "GBT First Underwater Fairy with Short Hookshot Anywhere",
  MM_GBT_CENTRAL_GEYSER: "GBT Central Room without Zora using Fire & Ice Arrows",
  MM_BANK_ONE_WALLET: "Bank Rewards Require One Less Wallet",
  MM_BANK_NO_WALLET: "Bank Rewards Require No Wallets",
};

export type Trick = keyof typeof TRICKS;

export const DEFAULT_TRICKS: Trick[] = ['OOT_NIGHT_GS'];
