#ifndef COMBO_OOT_SCENE_H
#define COMBO_OOT_SCENE_H

#define SCE_INSIDE_DEKU_TREE                    0x00
#define SCE_DODONGO_CAVERN                      0x01
#define SCE_INSIDE_JABU_JABU                    0x02
#define SCE_TEMPLE_FOREST                       0x03
#define SCE_TEMPLE_FIRE                         0x04
#define SCE_TEMPLE_WATER                        0x05
#define SCE_TEMPLE_SPIRIT                       0x06
#define SCE_TEMPLE_SHADOW                       0x07
#define SCE_BOTTOM_OF_THE_WELL                  0x08
#define SCE_ICE_CAVERN                          0x09
#define SCE_GANON_TOWER                         0x0a
#define SCE_GERUDO_TRAINING_GROUND              0x0b
#define SCE_THIEVES_HIDEOUT                     0x0c
#define SCE_INSIDE_GANON_CASTLE                 0x0d
#define SCE_GANON_TOWER_COLLAPSING              0x0e
#define SCE_INSIDE_GANON_CASTLE_COLLAPSING      0x0f
#define SCE_TREASURE_BOX_SHOP                   0x10
#define SCE_LAIR_GOHMA                          0x11
#define SCE_LAIR_KING_DODONGO                   0x12
#define SCE_LAIR_BARINADE                       0x13
#define SCE_LAIR_PHANTOM_GANON                  0x14
#define SCE_LAIR_VOLVAGIA                       0x15
#define SCE_LAIR_MORPHA                         0x16
#define SCE_LAIR_TWINROVA                       0x17
#define SCE_LAIR_BONGO_BONGO                    0x18
#define SCE_LAIR_GANONDORF                      0x19
#define SCE_TOWER_COLLAPSE_EXTERIOR             0x1a
#define SCE_MARKET_ENTRANCE_CHILD_DAY           0x1b
#define SCE_MARKET_ENTRANCE_CHILD_NIGHT         0x1c
#define SCE_MARKET_ENTRANCE_ADULT               0x1d
#define SCE_BACK_ALLEY_DAY                      0x1e
#define SCE_BACK_ALLEY_NIGHT                    0x1f
#define SCE_MARKET_CHILD_DAY                    0x20
#define SCE_MARKET_CHILD_NIGHT                  0x21
#define SCE_MARKET_ADULT                        0x22
#define SCE_TEMPLE_OF_TIME_EXTERIOR_CHILD_DAY   0x23
#define SCE_TEMPLE_OF_TIME_EXTERIOR_CHILD_NIGHT 0x24
#define SCE_TEMPLE_OF_TIME_EXTERIOR_ADULT       0x25
#define SCE_KOKIRI_KNOW_IT_ALL                  0x26
#define SCE_KOKIRI_TWINS                        0x27
#define SCE_KOKIRI_MIDO                         0x28
#define SCE_KOKIRI_SARIA                        0x29
#define SCE_CARPENTER_BOSS_HOUSE                0x2a
#define SCE_BACK_ALLEY_HOUSE                    0x2b
#define SCE_BAZAAR                              0x2c
#define SCE_KOKIRI_SHOP                         0x2d
#define SCE_GORON_SHOP                          0x2e
#define SCE_ZORA_SHOP                           0x2f
#define SCE_KAKARIKO_POTION_SHOP                0x30
#define SCE_MARKET_POTION_SHOP                  0x31
#define SCE_BOMBCHU_SHOP                        0x32
#define SCE_HAPPY_MASK_SHOP                     0x33
#define SCE_LINK_HOUSE                          0x34
#define SCE_BACK_ALLEY_HOUSE2                   0x35
#define SCE_STABLE                              0x36
#define SCE_IMPA_HOUSE                          0x37
#define SCE_LABORATORY                          0x38
#define SCE_CARPENTER_TENT                      0x39
#define SCE_GRAVEKEEPER_HUT                     0x3a
#define SCE_GREAT_FAIRY_FOUNTAIN_UPGRADES       0x3b
#define SCE_FAIRY_FOUNTAIN                      0x3c
#define SCE_GREAT_FAIRY_FOUNTAIN_SPELLS         0x3d
#define SCE_GROTTOS                             0x3e
#define SCE_TOMB_REDEAD                         0x3f
#define SCE_TOMB_FAIRY                          0x40
#define SCE_TOMB_ROYAL                          0x41
#define SCE_SHOOTING_GALLERY                    0x42
#define SCE_TEMPLE_OF_TIME                      0x43
#define SCE_CHAMBER_OF_THE_SAGES                0x44
#define SCE_CASTLE_MAZE_DAY                     0x45
#define SCE_CASTLE_MAZE_NIGHT                   0x46
#define SCE_CUTSCENE_MAP                        0x47
#define SCE_TOMB_DAMPE_WINDMILL                 0x48
#define SCE_FISHING_POND                        0x49
#define SCE_CASTLE_COURTYARD                    0x4a
#define SCE_BOMBCHU_BOWLING_ALLEY               0x4b
#define SCE_RANCH_HOUSE_SILO                    0x4c
#define SCE_GUARD_HOUSE                         0x4d
#define SCE_GRANNY_POTION_SHOP                  0x4e
#define SCE_GANON_BATTLE_ARENA                  0x4f
#define SCE_HOUSE_OF_SKULLTULA                  0x50
#define SCE_HYRULE_FIELD                        0x51
#define SCE_KAKARIKO_VILLAGE                    0x52
#define SCE_GRAVEYARD                           0x53
#define SCE_ZORA_RIVER                          0x54
#define SCE_KOKIRI_FOREST                       0x55
#define SCE_SACRED_FOREST_MEADOW                0x56
#define SCE_LAKE_HYLIA                          0x57
#define SCE_ZORA_DOMAIN                         0x58
#define SCE_ZORA_FOUNTAIN                       0x59
#define SCE_GERUDO_VALLEY                       0x5a
#define SCE_LOST_WOODS                          0x5b
#define SCE_DESERT_COLOSSUS                     0x5c
#define SCE_GERUDO_FORTRESS                     0x5d
#define SCE_HAUNTED_WASTELAND                   0x5e
#define SCE_HYRULE_CASTLE                       0x5f
#define SCE_DEATH_MOUNTAIN_TRAIL                0x60
#define SCE_DEATH_MOUNTAIN_CRATER               0x61
#define SCE_GORON_CITY                          0x62
#define SCE_LON_LON_RANCH                       0x63
#define SCE_GANON_CASTLE_EXTERIOR               0x64

#endif
