import { Settings } from '@ootmm/core';
import { Confvar } from '../confvars';
import { isEntranceShuffle } from '../logic/helpers';
import { mustStartWithMasterSword } from '../logic/master-sword';
import { World } from '../logic/world';

export function worldConfig(world: World, settings: Settings): Set<Confvar> {
  const config = new Set<Confvar>;

  const exprs: { [k in Confvar]: boolean } = {
    GANON_NO_BOSS_KEY: settings.ganonBossKey === 'removed',
    SMALL_KEY_SHUFFLE: settings.smallKeyShuffleOot === 'anywhere',
    CSMC: settings.csmc === 'always',
    CSMC_SKULLTULA: settings.csmcSkulltula,
    CSMC_COW: settings.csmcCow,
    CSMC_AGONY: settings.csmc === 'agony',
    OOT_PROGRESSIVE_SHIELDS: settings.progressiveShieldsOot === 'progressive',
    OOT_PROGRESSIVE_SWORDS: settings.progressiveSwordsOot === 'progressive',
    OOT_PROGRESSIVE_SWORDS_GORON: settings.progressiveSwordsOot === 'goron',
    MM_PROGRESSIVE_SHIELDS: settings.progressiveShieldsMm === 'progressive',
    MM_PROGRESSIVE_LULLABY: settings.progressiveGoronLullabyMm === 'progressive',
    OOT_PROGRESSIVE_LULLABY: settings.progressiveGoronLullabyOot === 'progressive',
    DOOR_OF_TIME_OPEN: settings.doorOfTime === 'open',
    OOT_OPEN_DEKU: settings.dekuTree === 'open',
    OOT_CLOSED_DEKU: settings.dekuTree === 'closed',
    OOT_ADULT_DEKU: world.resolvedFlags.openDungeonsOot.has('dekuTreeAdult'),
    ER_DUNGEONS: settings.erDungeons !== 'none',
    ER_MAJOR_DUNGEONS: settings.erMajorDungeons,
    ER_BOSS: settings.erBoss !== 'none',
    ER_ANY: isEntranceShuffle(settings),
    SHARED_SWORDS: settings.sharedSwords,
    SHARED_BOWS: settings.sharedBows,
    SHARED_BOMB_BAGS: settings.sharedBombBags,
    SHARED_MAGIC: settings.sharedMagic,
    SHARED_MAGIC_ARROW_FIRE: settings.sharedMagicArrowFire,
    SHARED_MAGIC_ARROW_ICE: settings.sharedMagicArrowIce,
    SHARED_MAGIC_ARROW_LIGHT: settings.sharedMagicArrowLight,
    SHARED_SONG_EPONA: settings.sharedSongEpona,
    SHARED_SONG_STORMS: settings.sharedSongStorms,
    SHARED_SONG_TIME: settings.sharedSongTime,
    SHARED_SONG_ZELDA: settings.sharedSongZeldaLullaby,
    SHARED_SONG_SARIA: settings.sharedSongSarias,
    SHARED_SONG_SUN: settings.sharedSongSun,
    SHARED_SONG_TP_FOREST: settings.sharedSongMinuet,
    SHARED_SONG_TP_FIRE: settings.sharedSongBolero,
    SHARED_SONG_TP_WATER: settings.sharedSongSerenade,
    SHARED_SONG_TP_SPIRIT: settings.sharedSongRequiem,
    SHARED_SONG_TP_SHADOW: settings.sharedSongNocturne,
    SHARED_SONG_TP_LIGHT: settings.sharedSongPrelude,
    SHARED_NUTS_STICKS: settings.sharedNutsSticks,
    SHARED_HOOKSHOT: settings.sharedHookshot,
    SHARED_LENS: settings.sharedLens,
    SHARED_OCARINA: settings.sharedOcarina,
    SHARED_MASK_GORON: settings.sharedMaskGoron,
    SHARED_MASK_ZORA: settings.sharedMaskZora,
    SHARED_MASK_BUNNY: settings.sharedMaskBunny,
    SHARED_MASK_TRUTH: settings.sharedMaskTruth,
    SHARED_MASK_KEATON: settings.sharedMaskKeaton,
    SHARED_WALLETS: settings.sharedWallets,
    SHARED_HEALTH: settings.sharedHealth,
    SHARED_SOULS_ENEMY: settings.sharedSoulsEnemy,
    SHARED_SOULS_MISC: settings.sharedSoulsMisc,
    SHARED_SOULS_NPC: settings.sharedSoulsNpc,
    SHARED_SOULS_ANIMAL: settings.sharedSoulsAnimal,
    SHARED_OCARINA_BUTTONS: settings.sharedOcarinaButtons,
    SHARED_SHIELDS: settings.sharedShields,
    SHARED_SPELL_FIRE: settings.sharedSpellFire,
    SHARED_SPELL_WIND: settings.sharedSpellWind,
    SHARED_SPELL_LOVE: settings.sharedSpellLove,
    SHARED_BOOTS_IRON: settings.sharedBootsIron,
    SHARED_BOOTS_HOVER: settings.sharedBootsHover,
    SHARED_TUNIC_GORON: settings.sharedTunicGoron,
    SHARED_TUNIC_ZORA: settings.sharedTunicZora,
    SHARED_SCALES: settings.sharedScales,
    SHARED_STRENGTH: settings.sharedStrength,
    SHARED_BOTTLES: settings.sharedBottles,
    MM_CROSS_AGE: settings.crossAge,
    MM_OCARINA_FAIRY: settings.fairyOcarinaMm,
    MM_HOOKSHOT_SHORT: settings.shortHookshotMm,
    MM_SONG_ZELDA: settings.songZeldaLullabyMm,
    MM_SONG_SARIA: settings.songSariasMm,
    MM_SONG_SUN: settings.songSunMm,
    MM_SONG_TP_FOREST: settings.songMinuetMm,
    MM_SONG_TP_FIRE: settings.songBoleroMm,
    MM_SONG_TP_WATER: settings.songSerenadeMm,
    MM_SONG_TP_SPIRIT: settings.songRequiemMm,
    MM_SONG_TP_SHADOW: settings.songNocturneMm,
    MM_SONG_TP_LIGHT: settings.songPreludeMm,
    OOT_SKIP_ZELDA: settings.skipZelda,
    OOT_ADULT_KAKARIKO_GATE: settings.kakarikoGate === 'closed',
    OOT_OPEN_KAKARIKO_GATE: settings.kakarikoGate === 'open',
    OOT_LACS_CUSTOM: settings.lacs === 'custom',
    OOT_GANON_BK_CUSTOM: settings.ganonBossKey === 'custom',
    OOT_KZ_OPEN: settings.zoraKing === 'open',
    OOT_KZ_OPEN_ADULT: settings.zoraKing === 'adult',
    GOAL_GANON: settings.goal === 'ganon' || settings.goal === 'both',
    GOAL_MAJORA: settings.goal === 'majora' || settings.goal === 'both',
    GOAL_TRIFORCE: settings.goal === 'triforce',
    GOAL_TRIFORCE3: settings.goal === 'triforce3',
    MM_MAJORA_CHILD_CUSTOM: settings.majoraChild === 'custom',
    FILL_WALLETS: settings.fillWallets,
    CHILD_WALLET: settings.childWallets,
    OOT_ADULT_WELL: world.resolvedFlags.openDungeonsOot.has('wellAdult'),
    COLOSSAL_WALLET: settings.colossalWallets,
    BOTTOMLESS_WALLET: settings.bottomlessWallets,
    OOT_AGELESS_STICKS: settings.agelessSticks,
    OOT_AGELESS_BOW: settings.agelessBow,
    OOT_AGELESS_SLINGSHOT: settings.agelessSlingshot,
    OOT_AGELESS_BOOTS: settings.agelessBoots,
    OOT_AGELESS_STRENGTH: settings.agelessStrength,
    OOT_AGELESS_SWORDS: settings.agelessSwords,
    OOT_AGELESS_SOARING: settings.agelessSoaring,
    MM_OWL_SHUFFLE: settings.owlShuffle === 'anywhere',
    OOT_CARPENTERS_ONE: settings.gerudoFortress === 'single',
    OOT_CARPENTERS_NONE: settings.gerudoFortress === 'open',
    OOT_NO_BOSS_KEY: settings.bossKeyShuffleOot === 'removed',
    OOT_NO_SMALL_KEY: settings.smallKeyShuffleOot === 'removed',
    MM_NO_BOSS_KEY: settings.bossKeyShuffleMm === 'removed',
    MM_NO_SMALL_KEY: settings.smallKeyShuffleMm === 'removed',
    CSMC_HEARTS: settings.csmcHearts,
    CSMC_MAP_COMPASS: settings.csmcMapCompass,
    OOT_BLUE_FIRE_ARROWS: settings.blueFireArrows,
    OOT_SUNLIGHT_ARROWS: settings.sunlightArrows,
    OOT_SILVER_RUPEE_SHUFFLE: settings.silverRupeeShuffle !== 'vanilla',
    OOT_FREE_SCARECROW: settings.freeScarecrowOot,
    OOT_SOULS_ENEMY: settings.soulsEnemyOot,
    OOT_SOULS_BOSS: settings.soulsBossOot,
    OOT_SOULS_NPC: settings.soulsNpcOot,
    OOT_SOULS_ANIMAL: settings.soulsAnimalOot,
    OOT_SOULS_MISC: settings.soulsMiscOot,
    MM_SOULS_ENEMY: settings.soulsEnemyMm,
    MM_SOULS_BOSS: settings.soulsBossMm,
    MM_SOULS_NPC: settings.soulsNpcMm,
    MM_SOULS_ANIMAL: settings.soulsAnimalMm,
    MM_SOULS_MISC: settings.soulsMiscMm,
    MM_REMOVED_FAIRIES: settings.strayFairyOtherShuffle === 'removed',
    SHARED_SKELETON_KEY: settings.sharedSkeletonKey,
    SHARED_PLATINUM_TOKEN: settings.sharedPlatinumToken,
    OOT_SHUFFLE_MASK_TRADES: settings.shuffleMaskTrades,
    MENU_NOTEBOOK: settings.menuNotebook,
    OOT_AGELESS_CHILD_TRADE: settings.agelessChildTrade,
    OOT_START_ADULT: settings.startingAge === 'adult',
    HINT_IMPORTANCE: settings.hintImportance && settings.logic !== 'none',
    OOT_OCARINA_BUTTONS: settings.ocarinaButtonsShuffleOot,
    MM_OCARINA_BUTTONS: settings.ocarinaButtonsShuffleMm,
    OOT_AGE_CHANGE: settings.ageChange !== 'none',
    OOT_AGE_CHANGE_NEEDS_OOT: settings.ageChange === 'oot',
    MM_PROGRESSIVE_GFS: settings.progressiveGFS === 'progressive',
    OOT_CHEST_GAME_SHUFFLE: settings.smallKeyShuffleChestGame !== 'vanilla',
    MM_CLIMB_MOST_SURFACES: settings.climbMostSurfacesMm,
    OOT_TRIAL_LIGHT: world.resolvedFlags.ganonTrials.has('Light'),
    OOT_TRIAL_FOREST: world.resolvedFlags.ganonTrials.has('Forest'),
    OOT_TRIAL_FIRE: world.resolvedFlags.ganonTrials.has('Fire'),
    OOT_TRIAL_WATER: world.resolvedFlags.ganonTrials.has('Water'),
    OOT_TRIAL_SHADOW: world.resolvedFlags.ganonTrials.has('Shadow'),
    OOT_TRIAL_SPIRIT: world.resolvedFlags.ganonTrials.has('Spirit'),
    ER_MOON: settings.erMoon,
    MM_OPEN_MOON: settings.openMoon,
    NO_BROKEN_ACTORS: !settings.restoreBrokenActors,
    SHARED_BOMBCHU: settings.sharedBombchu,
    ER_WALLMASTERS: settings.erWallmasters !== 'none',
    OOT_OPEN_MASK_SHOP: settings.openMaskShop,
    OOT_BRIDGE_VANILLA: settings.rainbowBridge === 'vanilla',
    OOT_BRIDGE_MEDALLIONS: settings.rainbowBridge === 'medallions',
    OOT_BRIDGE_CUSTOM: settings.rainbowBridge === 'custom',
    MULTIPLAYER: settings.mode !== 'single',
    MM_OPEN_WF: world.resolvedFlags.openDungeonsMm.has('WF'),
    MM_OPEN_SH: world.resolvedFlags.openDungeonsMm.has('SH'),
    MM_OPEN_GB: world.resolvedFlags.openDungeonsMm.has('GB'),
    MM_OPEN_ST: world.resolvedFlags.openDungeonsMm.has('ST'),
    MM_CLEAR_OPEN_WF: settings.clearStateDungeonsMm === 'WF' || settings.clearStateDungeonsMm === 'both',
    MM_CLEAR_OPEN_GB: settings.clearStateDungeonsMm === 'GB' || settings.clearStateDungeonsMm === 'both',
    MM_SPELL_FIRE: settings.spellFireMm,
    MM_SPELL_WIND: settings.spellWindMm,
    MM_SPELL_LOVE: settings.spellLoveMm,
    MM_BOOTS_IRON: settings.bootsIronMm,
    MM_BOOTS_HOVER: settings.bootsHoverMm,
    MM_TUNIC_GORON: settings.tunicGoronMm,
    MM_TUNIC_ZORA: settings.tunicZoraMm,
    MM_SCALES: settings.scalesMm,
    MM_STRENGTH: settings.strengthMm,
    MM_KEG_STRENGTH_3: settings.kegStrength3,
    OOT_GANON_BOSS_KEY_HINT: settings.ganonBossKey === 'anywhere',
    BLAST_MASK_DELAY_INSTANT: settings.blastMaskCooldown === 'instant',
    BLAST_MASK_DELAY_VERYSHORT: settings.blastMaskCooldown === 'veryshort',
    BLAST_MASK_DELAY_SHORT: settings.blastMaskCooldown === 'short',
    BLAST_MASK_DELAY_LONG: settings.blastMaskCooldown === 'long',
    BLAST_MASK_DELAY_VERYLONG: settings.blastMaskCooldown === 'verylong',
    OOT_MASK_BLAST: settings.blastMaskOot,
    SHARED_MASK_BLAST: settings.sharedMaskBlast,
    OOT_MASK_STONE: settings.stoneMaskOot,
    SHARED_MASK_STONE: settings.sharedMaskStone,
    OOT_SONG_EMPTINESS: settings.elegyOot,
    SHARED_SONG_EMPTINESS: settings.sharedSongElegy,
    OOT_SONG_HEALING: settings.songHealingOot,
    SHARED_SONG_HEALING: settings.sharedSongHealing,
    OOT_SONG_SOARING: settings.songSoaringOot,
    SHARED_SONG_SOARING: settings.sharedSongSoaring,
    OOT_SONG_AWAKENING: settings.songAwakeningOot,
    OOT_SONG_GORON: settings.songGoronOot,
    OOT_SONG_ZORA: settings.songZoraOot,
    OOT_SONG_ORDER: settings.songOrderOot,
    SHARED_SONG_AWAKENING: settings.sharedSongAwakening,
    SHARED_SONG_GORON: settings.sharedSongGoron,
    SHARED_SONG_ZORA: settings.sharedSongZora,
    SHARED_SONG_ORDER: settings.sharedSongOrder,
    MM_FD_ANYWHERE: settings.fierceDeityAnywhere,
    MM_CLOCK_SPEED_VERYSLOW: settings.clockSpeed === 'veryslow',
    MM_CLOCK_SPEED_SLOW: settings.clockSpeed === 'slow',
    MM_CLOCK_SPEED_FAST: settings.clockSpeed === 'fast',
    MM_CLOCK_SPEED_VERYFAST: settings.clockSpeed === 'veryfast',
    MM_CLOCK_SPEED_SUPERFAST: settings.clockSpeed === 'superfast',
    MM_AUTO_INVERT_ALWAYS: settings.autoInvert === 'always',
    MM_AUTO_INVERT_FIRST_CYCLE: settings.autoInvert === 'firstCycle',
    MM_MOON_CRASH_CYCLE: settings.moonCrash === 'cycle',
    MM_KEEP_ITEMS_RESET: settings.keepItemsReset,
    MM_KEEP_BOTTLES_RESET: settings.keepBottlesReset,
    MM_FAST_MASKS: settings.fastMasks,
    OOT_OPEN_ZD_SHORTCUT: settings.openZdShortcut,
    MM_CLOCKS: settings.clocks,
    MM_CLOCKS_PROGRESSIVE: settings.progressiveClocks !== 'separate',
    MM_CLOCKS_PROGRESSIVE_REVERSE: settings.progressiveClocks === 'descending',
    ER_GROTTOS: settings.erGrottos !== 'none',
    ER_OVERWORLD: settings.erOverworld !== 'none',
    ER_INDOORS: settings.erIndoors !== 'none',
    ER_REGIONS_OVERWORLD: settings.erRegions !== 'none' || settings.erOverworld !== 'none',
    CROSS_GAME_FW: settings.crossGameFw,
    RUPEE_SCALING: settings.rupeeScaling,
    OOT_SWORDLESS_ADULT: settings.swordlessAdult,
    OOT_TIME_TRAVEL_REQUIRES_MS: settings.timeTravelSword,
    OOT_EXTRA_CHILD_SWORDS: settings.extraChildSwordsOot,
    MM_DEKU_SHIELD: settings.dekuShieldMm,
    BRONZE_SCALE: settings.bronzeScale,
    ONLY_OOT: settings.games === 'oot',
    ONLY_MM: settings.games === 'mm',
    OOT_PLANTED_BEANS: settings.ootPreplantedBeans,
    OOT_OPEN_JABU_JABU: world.resolvedFlags.openDungeonsOot.has('JJ'),
    OOT_OPEN_SHADOW_TEMPLE: world.resolvedFlags.openDungeonsOot.has('Shadow'),
    OOT_OPEN_DODONGO_CAVERN: world.resolvedFlags.openDungeonsOot.has('DC'),
    OOT_OPEN_WATER_TEMPLE: world.resolvedFlags.openDungeonsOot.has('Water'),
    OOT_OPEN_WELL: world.resolvedFlags.openDungeonsOot.has('BotW'),
    OOT_SONG_OF_DOUBLE_TIME: settings.songOfDoubleTimeOot,
    MM_PRE_ACTIVATED_OWL_CT: world.resolvedFlags.mmPreActivatedOwls.has('clocktown'),
    MM_PRE_ACTIVATED_OWL_MR: world.resolvedFlags.mmPreActivatedOwls.has('milkroad'),
    MM_PRE_ACTIVATED_OWL_SS: world.resolvedFlags.mmPreActivatedOwls.has('swamp'),
    MM_PRE_ACTIVATED_OWL_WF: world.resolvedFlags.mmPreActivatedOwls.has('woodfall'),
    MM_PRE_ACTIVATED_OWL_MV: world.resolvedFlags.mmPreActivatedOwls.has('mountain'),
    MM_PRE_ACTIVATED_OWL_SH: world.resolvedFlags.mmPreActivatedOwls.has('snowhead'),
    MM_PRE_ACTIVATED_OWL_GB: world.resolvedFlags.mmPreActivatedOwls.has('greatbay'),
    MM_PRE_ACTIVATED_OWL_ZC: world.resolvedFlags.mmPreActivatedOwls.has('zoracape'),
    MM_PRE_ACTIVATED_OWL_IC: world.resolvedFlags.mmPreActivatedOwls.has('canyon'),
    MM_PRE_ACTIVATED_OWL_ST: world.resolvedFlags.mmPreActivatedOwls.has('tower'),
    MM_WELL_OPEN: settings.beneathWell === 'open',
    MM_HAMMER: settings.hammerMm,
    SHARED_HAMMER: settings.sharedHammer,
    MM_UPGRADES_STICKS_NUTS: settings.sticksNutsUpgradesMm,
    OOT_SHUFFLE_EGGS: settings.eggShuffle,
    MM_STONE_OF_AGONY: settings.stoneAgonyMm,
    SHARED_STONE_OF_AGONY: settings.sharedStoneAgony,
    OOT_MUST_START_WITH_MS: mustStartWithMasterSword(settings),
    OOT_SPIN_UPGRADE: settings.spinUpgradeOot,
    SHARED_SPIN_UPGRADE: settings.sharedSpinUpgrade,
    MM_JP_LAYOUT_DEKU_PALACE: world.resolvedFlags.jpLayouts.has('DekuPalace'),
    REGION_STATE_DUNGEONS: settings.regionState === 'dungeonBeaten',
    REGION_STATE_REWARDS: settings.regionState === 'reward',
    REGION_STATE_FREE: settings.regionState === 'free',
    MM_EASY_LIGHTBLOCKS: settings.mmEasierLightblock,
    SONG_NOTES: settings.songs === 'notes',
    OOT_ICE_ARROW_PLATFORMS: settings.iceArrowPlatformsOot,
    OOT_SONG_EVENTS_SHUFFLE: settings.songEventsShuffleOot,
    MM_SONG_EVENTS_SHUFFLE: settings.songEventsShuffleMm,
    OOT_DMG_MULT_2: settings.damageMultiplierOot === 'double',
    OOT_DMG_MULT_4: settings.damageMultiplierOot === 'quadruple',
    OOT_DMG_MULT_8: settings.damageMultiplierOot === 'octuple',
    OOT_DMG_MULT_OHKO: settings.damageMultiplierOot === 'ohko',
    MM_DMG_MULT_2: settings.damageMultiplierMm === 'double',
    MM_DMG_MULT_4: settings.damageMultiplierMm === 'quadruple',
    MM_DMG_MULT_8: settings.damageMultiplierMm === 'octuple',
    MM_DMG_MULT_OHKO: settings.damageMultiplierMm === 'ohko',
  };

  for (const v in exprs) {
    if (exprs[v as Confvar]) {
      config.add(v as Confvar);
    }
  }

  return config;
}
