#ifndef COMBO_ACTOR_ID_H
#define COMBO_ACTOR_ID_H

#if defined(GAME_OOT)
# define ACTOR_PLAYER                  0x000
# define ACTOR_EN_TEST                 0x002
# define ACTOR_EN_GIRLA                0x004
# define ACTOR_CUSTOM_WARP             0x005
# define ACTOR_CUSTOM_TRIGGERS         0x006
# define ACTOR_EN_PART                 0x007
# define ACTOR_EN_LIGHT                0x008
# define ACTOR_EN_DOOR                 0x009
# define ACTOR_EN_BOX                  0x00a
# define ACTOR_BG_DY_YOSEIZO           0x00b
# define ACTOR_BG_HIDAN_FIREWALL       0x00c
# define ACTOR_EN_POH                  0x00d
# define ACTOR_EN_OKUTA                0x00e
# define ACTOR_BG_YDAN_SP              0x00f
# define ACTOR_EN_BOM                  0x010
# define ACTOR_EN_WALLMAS              0x011
# define ACTOR_EN_DODONGO              0x012
# define ACTOR_EN_FIREFLY              0x013
# define ACTOR_EN_HORSE                0x014
# define ACTOR_EN_ITEM00               0x015
# define ACTOR_EN_ARROW                0x016
# define ACTOR_CUSTOM_TORCH2           0x017
# define ACTOR_EN_ELF                  0x018
# define ACTOR_EN_NIW                  0x019
# define ACTOR_ITEM_DECOY              0x01a
# define ACTOR_EN_TITE                 0x01b
# define ACTOR_EN_REEBA                0x01c
# define ACTOR_EN_PEEHAT               0x01d
# define ACTOR_EN_BUTTE                0x01e
# define ACTOR_EN_INSECT               0x020
# define ACTOR_EN_FISH                 0x021
# define ACTOR_EN_HOLL                 0x023
# define ACTOR_EN_SCENE_CHANGE         0x024
# define ACTOR_EN_ZF                   0x025
# define ACTOR_EN_HATA                 0x026
# define ACTOR_BOSS_DODONGO            0x027
# define ACTOR_BOSS_GOMA               0x028
# define ACTOR_EN_ZL1                  0x029
# define ACTOR_EN_VIEWER               0x02a
# define ACTOR_EN_GOMA                 0x02b
# define ACTOR_BG_PUSHBOX              0x02c
# define ACTOR_EN_BUBBLE               0x02d
# define ACTOR_DOOR_SHUTTER            0x02e
# define ACTOR_EN_DODOJR               0x02f
# define ACTOR_EN_BDFIRE               0x030
# define ACTOR_EN_BOOM                 0x032
# define ACTOR_EN_TORCH2               0x033
# define ACTOR_EN_BILI                 0x034
# define ACTOR_EN_TP                   0x035
# define ACTOR_EN_ST                   0x037
# define ACTOR_EN_BW                   0x038
# define ACTOR_EN_A_OBJ                0x039
# define ACTOR_EN_EIYER                0x03a
# define ACTOR_EN_RIVER_SOUND          0x03b
# define ACTOR_EN_HORSE_NORMAL         0x03c
# define ACTOR_EN_OSSAN                0x03d
# define ACTOR_BG_TREEMOUTH            0x03e
# define ACTOR_BG_DODOAGO              0x03f
# define ACTOR_BG_HIDAN_DALM           0x040
# define ACTOR_BG_HIDAN_HROCK          0x041
# define ACTOR_EN_HORSE_GANON          0x042
# define ACTOR_BG_HIDAN_ROCK           0x043
# define ACTOR_BG_HIDAN_RSEKIZOU       0x044
# define ACTOR_BG_HIDAN_SEKIZOU        0x045
# define ACTOR_BG_HIDAN_SIMA           0x046
# define ACTOR_BG_HIDAN_SYOKU          0x047
# define ACTOR_EN_XC                   0x048
# define ACTOR_BG_HIDAN_CURTAIN        0x049
# define ACTOR_BG_SPOT00_HANEBASI      0x04a
# define ACTOR_EN_MB                   0x04b
# define ACTOR_EN_BOMBF                0x04c
# define ACTOR_EN_ZL2                  0x04d
# define ACTOR_BG_HIDAN_FSLIFT         0x04e
# define ACTOR_EN_OE2                  0x04f
# define ACTOR_BG_YDAN_HASI            0x050
# define ACTOR_BG_YDAN_MARUTA          0x051
# define ACTOR_BOSS_GANONDROF          0x052
# define ACTOR_EN_AM                   0x054
# define ACTOR_EN_DEKUBABA             0x055
# define ACTOR_EN_M_FIRE1              0x056
# define ACTOR_EN_M_THUNDER            0x057
# define ACTOR_BG_DDAN_JD              0x058
# define ACTOR_BG_BREAKWALL            0x059
# define ACTOR_EN_JJ                   0x05a
# define ACTOR_EN_HORSE_ZELDA          0x05b
# define ACTOR_BG_DDAN_KD              0x05c
# define ACTOR_DOOR_WARP1              0x05d
# define ACTOR_OBJ_SYOKUDAI            0x05e
# define ACTOR_ITEM_B_HEART            0x05f
# define ACTOR_EN_DEKUNUTS             0x060
# define ACTOR_BG_MENKURI_KAITEN       0x061
# define ACTOR_BG_MENKURI_EYE          0x062
# define ACTOR_EN_VALI                 0x063
# define ACTOR_BG_MIZU_MOVEBG          0x064
# define ACTOR_BG_MIZU_WATER           0x065
# define ACTOR_ARMS_HOOK               0x066
# define ACTOR_EN_FHG                  0x067
# define ACTOR_BG_MORI_HINERI          0x068
# define ACTOR_EN_BB                   0x069
# define ACTOR_BG_TOKI_HIKARI          0x06a
# define ACTOR_EN_YUKABYUN             0x06b
# define ACTOR_BG_TOKI_SWD             0x06c
# define ACTOR_EN_FHG_FIRE             0x06d
# define ACTOR_BG_MJIN                 0x06e
# define ACTOR_BG_HIDAN_KOUSI          0x06f
# define ACTOR_DOOR_TOKI               0x070
# define ACTOR_BG_HIDAN_HAMSTEP        0x071
# define ACTOR_EN_BIRD                 0x072
# define ACTOR_EN_WOOD02               0x077
# define ACTOR_EN_LIGHTBOX             0x07c
# define ACTOR_EN_PU_BOX               0x07d
# define ACTOR_EN_TRAP                 0x080
# define ACTOR_EN_AROW_TRAP            0x081
# define ACTOR_EN_VASE                 0x082
# define ACTOR_EN_TA                   0x084
# define ACTOR_EN_TK                   0x085
# define ACTOR_BG_MORI_BIGST           0x086
# define ACTOR_BG_MORI_ELEVATOR        0x087
# define ACTOR_BG_MORI_KAITENKABE      0x088
# define ACTOR_BG_MORI_RAKKATENJO      0x089
# define ACTOR_EN_VM                   0x08a
# define ACTOR_DEMO_EFFECT             0x08b
# define ACTOR_DEMO_KANKYO             0x08c
# define ACTOR_BG_HIDAN_FWBIG          0x08d
# define ACTOR_EN_FLOORMAS             0x08e
# define ACTOR_EN_HEISHI1              0x08f
# define ACTOR_EN_RD                   0x090
# define ACTOR_EN_PO_SISTERS           0x091
# define ACTOR_BG_HEAVY_BLOCK          0x092
# define ACTOR_BG_PO_EVENT             0x093
# define ACTOR_OBJ_MURE                0x094
# define ACTOR_EN_SW                   0x095
# define ACTOR_BOSS_FD                 0x096
# define ACTOR_OBJECT_KANKYO           0x097
# define ACTOR_EN_DU                   0x098
# define ACTOR_EN_FD                   0x099
# define ACTOR_EN_HORSE_LINK_CHILD     0x09a
# define ACTOR_DOOR_ANA                0x09b
# define ACTOR_BG_SPOT02_OBJECTS       0x09c
# define ACTOR_BG_HAKA                 0x09d
# define ACTOR_MAGIC_WIND              0x09e
# define ACTOR_MAGIC_FIRE              0x09f
# define ACTOR_EN_RU1                  0x0a1
# define ACTOR_BOSS_FD2                0x0a2
# define ACTOR_EN_FD_FIRE              0x0a3
# define ACTOR_EN_DH                   0x0a4
# define ACTOR_EN_DHA                  0x0a5
# define ACTOR_EN_RL                   0x0a6
# define ACTOR_EN_ENCOUNT1             0x0a7
# define ACTOR_DEMO_DU                 0x0a8
# define ACTOR_DEMO_IM                 0x0a9
# define ACTOR_DEMO_TRE_LGT            0x0aa
# define ACTOR_EN_FW                   0x0ab
# define ACTOR_BG_VB_SIMA              0x0ac
# define ACTOR_EN_VB_BALL              0x0ad
# define ACTOR_BG_HAKA_MEGANE          0x0ae
# define ACTOR_BG_HAKA_MEGANEBG        0x0af
# define ACTOR_BG_HAKA_SHIP            0x0b0
# define ACTOR_BG_HAKA_SGAMI           0x0b1
# define ACTOR_EN_HEISHI2              0x0b3
# define ACTOR_EN_ENCOUNT2             0x0b4
# define ACTOR_EN_FIRE_ROCK            0x0b5
# define ACTOR_EN_BROB                 0x0b6
# define ACTOR_MIR_RAY                 0x0b7
# define ACTOR_BG_SPOT09_OBJ           0x0b8
# define ACTOR_BG_SPOT18_OBJ           0x0b9
# define ACTOR_BOSS_VA                 0x0ba
# define ACTOR_BG_HAKA_TUBO            0x0bb
# define ACTOR_BG_HAKA_TRAP            0x0bc
# define ACTOR_BG_HAKA_HUTA            0x0bd
# define ACTOR_BG_HAKA_ZOU             0x0be
# define ACTOR_BG_SPOT17_FUNEN         0x0bf
# define ACTOR_EN_SYATEKI_ITM          0x0c0
# define ACTOR_EN_SYATEKI_MAN          0x0c1
# define ACTOR_EN_TANA                 0x0c2
# define ACTOR_EN_NB                   0x0c3
# define ACTOR_BOSS_MO                 0x0c4
# define ACTOR_EN_SB                   0x0c5
# define ACTOR_EN_BIGOKUTA             0x0c6
# define ACTOR_EN_KAREBABA             0x0c7
# define ACTOR_BG_BDAN_OBJECTS         0x0c8
# define ACTOR_DEMO_SA                 0x0c9
# define ACTOR_DEMO_GO                 0x0ca
# define ACTOR_EN_IN                   0x0cb
# define ACTOR_EN_TR                   0x0cc
# define ACTOR_BG_SPOT16_BOMBSTONE     0x0cd
# define ACTOR_BG_HIDAN_KOWARERUKABE   0x0cf
# define ACTOR_BG_BOMBWALL             0x0d0
# define ACTOR_BG_SPOT08_ICEBLOCK      0x0d1
# define ACTOR_EN_RU2                  0x0d2
# define ACTOR_OBJ_DEKUJR              0x0d3
# define ACTOR_BG_MIZU_UZU             0x0d4
# define ACTOR_BG_SPOT06_OBJECTS       0x0d5
# define ACTOR_BG_ICE_OBJECTS          0x0d6
# define ACTOR_BG_HAKA_WATER           0x0d7
# define ACTOR_EN_MA2                  0x0d9
# define ACTOR_EN_BOM_CHU              0x0da
# define ACTOR_EN_HORSE_GAME_CHECK     0x0db
# define ACTOR_BOSS_TW                 0x0dc
# define ACTOR_EN_RR                   0x0dd
# define ACTOR_EN_BA                   0x0de
# define ACTOR_EN_BX                   0x0df
# define ACTOR_EN_ANUBICE              0x0e0
# define ACTOR_EN_ANUBICE_FIRE         0x0e1
# define ACTOR_BG_MORI_HASHIGO         0x0e2
# define ACTOR_BG_MORI_HASHIRA4        0x0e3
# define ACTOR_BG_MORI_IDOMIZU         0x0e4
# define ACTOR_BG_SPOT16_DOUGHNUT      0x0e5
# define ACTOR_BG_BDAN_SWITCH          0x0e6
# define ACTOR_EN_MA1                  0x0e7
# define ACTOR_BOSS_GANON              0x0e8
# define ACTOR_BOSS_SST                0x0e9
# define ACTOR_EN_NY                   0x0ec
# define ACTOR_EN_FR                   0x0ed
# define ACTOR_ITEM_SHIELD             0x0ee
# define ACTOR_BG_ICE_SHELTER          0x0ef
# define ACTOR_EN_ICE_HONO             0x0f0
# define ACTOR_ITEM_OCARINA            0x0f1
# define ACTOR_MAGIC_DARK              0x0f4
# define ACTOR_DEMO_6K                 0x0f5
# define ACTOR_EN_ANUBICE_TAG          0x0f6
# define ACTOR_BG_HAKA_GATE            0x0f7
# define ACTOR_BG_SPOT15_SAKU          0x0f8
# define ACTOR_BG_JYA_GOROIWA          0x0f9
# define ACTOR_BG_JYA_ZURERUKABE       0x0fa
# define ACTOR_BG_JYA_COBRA            0x0fc
# define ACTOR_BG_JYA_KANAAMI          0x0fd
# define ACTOR_EN_FISHING              0x0fe
# define ACTOR_OBJ_OSHIHIKI            0x0ff
# define ACTOR_BG_GATE_SHUTTER         0x100
# define ACTOR_EFF_DUST                0x101
# define ACTOR_BG_SPOT01_FUSYA         0x102
# define ACTOR_BG_SPOT01_IDOHASHIRA    0x103
# define ACTOR_BG_SPOT01_IDOMIZU       0x104
# define ACTOR_BG_PO_SYOKUDAI          0x105
# define ACTOR_BG_GANON_OTYUKA         0x106
# define ACTOR_BG_SPOT15_RRBOX         0x107
# define ACTOR_BG_UMAJUMP              0x108
# define ACTOR_ARROW_FIRE              0x10a
# define ACTOR_ARROW_ICE               0x10b
# define ACTOR_ARROW_LIGHT             0x10c
# define ACTOR_ITEM_ETCETERA           0x10f
# define ACTOR_OBJ_KIBAKO              0x110
# define ACTOR_OBJ_TSUBO               0x111
# define ACTOR_EN_WONDER_ITEM          0x112
# define ACTOR_EN_IK                   0x113
# define ACTOR_DEMO_IK                 0x114
# define ACTOR_EN_SKJ                  0x115
# define ACTOR_EN_SKJNEEDLE            0x116
# define ACTOR_EN_G_SWITCH             0x117
# define ACTOR_DEMO_EXT                0x118
# define ACTOR_DEMO_SHD                0x119
# define ACTOR_EN_DNS                  0x11a
# define ACTOR_ELF_MSG                 0x11b
# define ACTOR_EN_HONOTRAP             0x11c
# define ACTOR_EN_TUBO_TRAP            0x11d
# define ACTOR_OBJ_ICE_POLY            0x11e
# define ACTOR_BG_SPOT03_TAKI          0x11f
# define ACTOR_BG_SPOT07_TAKI          0x120
# define ACTOR_EN_FZ                   0x121
# define ACTOR_EN_PO_RELAY             0x122
# define ACTOR_BG_RELAY_OBJECTS        0x123
# define ACTOR_EN_DIVING_GAME          0x124
# define ACTOR_EN_KUSA                 0x125
# define ACTOR_OBJ_BEAN                0x126
# define ACTOR_OBJ_BOMBIWA             0x127
# define ACTOR_OBJ_SWITCH              0x12a
# define ACTOR_OBJ_ELEVATOR            0x12b
# define ACTOR_OBJ_LIFT                0x12c
# define ACTOR_OBJ_HSBLOCK             0x12d
# define ACTOR_EN_OKARINA_TAG          0x12e
# define ACTOR_EN_YABUSAME_MARK        0x12f
# define ACTOR_EN_GOROIWA              0x130
# define ACTOR_EN_EX_RUPPY             0x131
# define ACTOR_EN_TORYO                0x132
# define ACTOR_EN_DAIKU                0x133
# define ACTOR_EN_NWC                  0x135
# define ACTOR_EN_BLKOBJ               0x136
# define ACTOR_ITEM_INBOX              0x137
# define ACTOR_EN_GE1                  0x138
# define ACTOR_OBJ_BLOCKSTOP           0x139
# define ACTOR_EN_SDA                  0x13a
# define ACTOR_EN_CLEAR_TAG            0x13b
# define ACTOR_EN_NIW_LADY             0x13c
# define ACTOR_EN_GM                   0x13d
# define ACTOR_EN_MS                   0x13e
# define ACTOR_EN_HS                   0x13f
# define ACTOR_BG_INGATE               0x140
# define ACTOR_EN_KANBAN               0x141
# define ACTOR_EN_HEISHI3              0x142
# define ACTOR_EN_SYATEKI_NIW          0x143
# define ACTOR_EN_ATTACK_NIW           0x144
# define ACTOR_BG_SPOT01_IDOSOKO       0x145
# define ACTOR_EN_SA                   0x146
# define ACTOR_EN_WONDER_TALK          0x147
# define ACTOR_BG_GJYO_BRIDGE          0x148
# define ACTOR_EN_DS                   0x149
# define ACTOR_EN_MK                   0x14a
# define ACTOR_EN_BOM_BOWL_MAN         0x14b
# define ACTOR_EN_BOM_BOWL_PIT         0x14c
# define ACTOR_EN_OWL                  0x14d
# define ACTOR_EN_ISHI                 0x14e
# define ACTOR_OBJ_HANA                0x14f
# define ACTOR_OBJ_LIGHTSWITCH         0x150
# define ACTOR_OBJ_MURE2               0x151
# define ACTOR_EN_GO                   0x152
# define ACTOR_EN_FU                   0x153
# define ACTOR_EN_CHANGER              0x155
# define ACTOR_BG_JYA_MEGAMI           0x156
# define ACTOR_BG_JYA_LIFT             0x157
# define ACTOR_BG_JYA_BIGMIRROR        0x158
# define ACTOR_BG_JYA_BOMBCHUIWA       0x159
# define ACTOR_BG_JYA_AMISHUTTER       0x15a
# define ACTOR_BG_JYA_BOMBIWA          0x15b
# define ACTOR_BG_SPOT18_BASKET        0x15c
# define ACTOR_EN_GANON_ORGAN          0x15e
# define ACTOR_EN_SIOFUKI              0x15f
# define ACTOR_EN_STREAM               0x160
# define ACTOR_EN_MM                   0x162
# define ACTOR_EN_KO                   0x163
# define ACTOR_EN_KZ                   0x164
# define ACTOR_EN_WEATHER_TAG          0x165
# define ACTOR_BG_SST_FLOOR            0x166
# define ACTOR_EN_ANI                  0x167
# define ACTOR_EN_EX_ITEM              0x168
# define ACTOR_BG_JYA_IRONOBJ          0x169
# define ACTOR_EN_JS                   0x16a
# define ACTOR_EN_JSJUTAN              0x16b
# define ACTOR_EN_CS                   0x16c
# define ACTOR_EN_MD                   0x16d
# define ACTOR_EN_HY                   0x16e
# define ACTOR_EN_GANON_MANT           0x16f
# define ACTOR_EN_OKARINA_EFFECT       0x170
# define ACTOR_EN_MAG                  0x171
# define ACTOR_DOOR_GERUDO             0x172
# define ACTOR_ELF_MSG2                0x173
# define ACTOR_DEMO_GT                 0x174
# define ACTOR_EN_PO_FIELD             0x175
# define ACTOR_EFC_ERUPC               0x176
# define ACTOR_BG_ZG                   0x177
# define ACTOR_EN_HEISHI4              0x178
# define ACTOR_EN_ZL3                  0x179
# define ACTOR_BOSS_GANON2             0x17a
# define ACTOR_EN_KAKASI               0x17b
# define ACTOR_EN_TAKARA_MAN           0x17c
# define ACTOR_OBJ_MAKEOSHIHIKI        0x17d
# define ACTOR_OCEFF_SPOT              0x17e
# define ACTOR_END_TITLE               0x17f
# define ACTOR_EN_TORCH                0x181
# define ACTOR_DEMO_EC                 0x182
# define ACTOR_SHOT_SUN                0x183
# define ACTOR_EN_DY_EXTRA             0x184
# define ACTOR_EN_WONDER_TALK2         0x185
# define ACTOR_EN_GE2                  0x186
# define ACTOR_OBJ_ROOMTIMER           0x187
# define ACTOR_EN_SSH                  0x188
# define ACTOR_EN_STH                  0x189
# define ACTOR_OCEFF_WIPE              0x18a
# define ACTOR_OCEFF_STORM             0x18b
# define ACTOR_EN_WEIYER               0x18c
# define ACTOR_BG_SPOT05_SOKO          0x18d
# define ACTOR_BG_JYA_1FLIFT           0x18e
# define ACTOR_BG_JYA_HAHENIRON        0x18f
# define ACTOR_BG_SPOT12_GATE          0x190
# define ACTOR_BG_SPOT12_SAKU          0x191
# define ACTOR_EN_HINTNUTS             0x192
# define ACTOR_EN_NUTSBALL             0x193
# define ACTOR_BG_SPOT00_BREAK         0x194
# define ACTOR_EN_SHOPNUTS             0x195
# define ACTOR_EN_IT                   0x196
# define ACTOR_EN_GELDB                0x197
# define ACTOR_OCEFF_WIPE2             0x198
# define ACTOR_OCEFF_WIPE3             0x199
# define ACTOR_EN_NIW_GIRL             0x19a
# define ACTOR_EN_DOG                  0x19b
# define ACTOR_EN_SI                   0x19c
# define ACTOR_BG_SPOT01_OBJECTS2      0x19d
# define ACTOR_OBJ_COMB                0x19e
# define ACTOR_BG_SPOT11_BAKUDANKABE   0x19f
# define ACTOR_OBJ_KIBAKO2             0x1a0
# define ACTOR_EN_DNT_DEMO             0x1a1
# define ACTOR_EN_DNT_JIJI             0x1a2
# define ACTOR_EN_DNT_NOMAL            0x1a3
# define ACTOR_EN_GUEST                0x1a4
# define ACTOR_BG_BOM_GUARD            0x1a5
# define ACTOR_EN_HS2                  0x1a6
# define ACTOR_DEMO_KEKKAI             0x1a7
# define ACTOR_BG_SPOT08_BAKUDANKABE   0x1a8
# define ACTOR_BG_SPOT17_BAKUDANKABE   0x1a9
# define ACTOR_OBJ_MURE3               0x1ab
# define ACTOR_EN_TG                   0x1ac
# define ACTOR_EN_MU                   0x1ad
# define ACTOR_EN_GO2                  0x1ae
# define ACTOR_EN_WF                   0x1af
# define ACTOR_EN_SKB                  0x1b0
# define ACTOR_DEMO_GJ                 0x1b1
# define ACTOR_DEMO_GEFF               0x1b2
# define ACTOR_BG_GND_FIREMEIRO        0x1b3
# define ACTOR_BG_GND_DARKMEIRO        0x1b4
# define ACTOR_BG_GND_SOULMEIRO        0x1b5
# define ACTOR_BG_GND_NISEKABE         0x1b6
# define ACTOR_BG_GND_ICEBLOCK         0x1b7
# define ACTOR_EN_GB                   0x1b8
# define ACTOR_EN_GS                   0x1b9
# define ACTOR_BG_MIZU_BWALL           0x1ba
# define ACTOR_BG_MIZU_SHUTTER         0x1bb
# define ACTOR_EN_DAIKU_KAKARIKO       0x1bc
# define ACTOR_BG_BOWL_WALL            0x1bd
# define ACTOR_EN_WALL_TUBO            0x1be
# define ACTOR_EN_PO_DESERT            0x1bf
# define ACTOR_EN_CROW                 0x1c0
# define ACTOR_DOOR_KILLER             0x1c1
# define ACTOR_BG_SPOT11_OASIS         0x1c2
# define ACTOR_BG_SPOT18_FUTA          0x1c3
# define ACTOR_BG_SPOT18_SHUTTER       0x1c4
# define ACTOR_EN_MA3                  0x1c5
# define ACTOR_EN_COW                  0x1c6
# define ACTOR_BG_ICE_TURARA           0x1c7
# define ACTOR_BG_ICE_SHUTTER          0x1c8
# define ACTOR_EN_KAKASI2              0x1c9
# define ACTOR_EN_KAKASI3              0x1ca
# define ACTOR_OCEFF_WIPE4             0x1cb
# define ACTOR_EN_EG                   0x1cc
# define ACTOR_BG_MENKURI_NISEKABE     0x1cd
# define ACTOR_EN_ZO                   0x1ce
# define ACTOR_OBJ_MAKEKINSUTA         0x1cf
# define ACTOR_EN_GE3                  0x1d0
# define ACTOR_OBJ_TIMEBLOCK           0x1d1
# define ACTOR_OBJ_HAMISHI             0x1d2
# define ACTOR_EN_ZL4                  0x1d3
# define ACTOR_EN_MM2                  0x1d4
# define ACTOR_BG_JYA_BLOCK            0x1d5
# define ACTOR_OBJ_WARP2BLOCK          0x1d6
#endif

#if defined(GAME_MM)
# define ACTOR_PLAYER              0x000
# define ACTOR_EN_TEST             0x001
# define ACTOR_EN_GIRLA            0x002
# define ACTOR_EN_PART             0x003
# define ACTOR_EN_LIGHT            0x004
# define ACTOR_EN_DOOR             0x005
# define ACTOR_EN_BOX              0x006
# define ACTOR_EN_PAMETFROG        0x007
# define ACTOR_EN_OKUTA            0x008
# define ACTOR_EN_BOM              0x009
# define ACTOR_EN_WALLMAS          0x00a
# define ACTOR_EN_DODONGO          0x00b
# define ACTOR_EN_FIREFLY          0x00c
# define ACTOR_EN_HORSE            0x00d
# define ACTOR_EN_ITEM00           0x00e
# define ACTOR_EN_ARROW            0x00f
# define ACTOR_EN_ELF              0x010
# define ACTOR_EN_NIW              0x011
# define ACTOR_EN_TITE             0x012
# define ACTOR_EN_PEEHAT           0x014
# define ACTOR_EN_BUTTE            0x015
# define ACTOR_EN_INSECT           0x016
# define ACTOR_EN_FISH             0x017
# define ACTOR_EN_HOLL             0x018
# define ACTOR_EN_DINOFOS          0x019
# define ACTOR_EN_HATA             0x01a
# define ACTOR_EN_ZL1              0x01b
# define ACTOR_EN_VIEWER           0x01c
# define ACTOR_EN_BUBBLE           0x01d
# define ACTOR_DOOR_SHUTTER        0x01e
# define ACTOR_EN_BOOM             0x020
# define ACTOR_EN_TORCH2           0x021
# define ACTOR_EN_MINIFROG         0x022
# define ACTOR_CUSTOM_WARP         0x023
# define ACTOR_CUSTOM_TRIGGERS     0x025
# define ACTOR_ITEM_DECOY          0x029
# define ACTOR_EN_ST               0x024
# define ACTOR_EN_A_OBJ            0x026
# define ACTOR_OBJ_WTURN           0x027
# define ACTOR_EN_RIVER_SOUND      0x028
# define ACTOR_EN_OSSAN            0x02a
# define ACTOR_CUSTOM_SPELL_FIRE   0x02b
# define ACTOR_CUSTOM_SPELL_WIND   0x02c
# define ACTOR_EN_FAMOS            0x02d
# define ACTOR_CUSTOM_SPELL_LOVE   0x02e
# define ACTOR_EN_BOMBF            0x02f
# define ACTOR_EN_AM               0x032
# define ACTOR_EN_DEKUBABA         0x033
# define ACTOR_EN_M_FIRE1          0x034
# define ACTOR_EN_M_THUNDER        0x035
# define ACTOR_BG_BREAKWALL        0x036
# define ACTOR_DOOR_WARP1          0x038
# define ACTOR_OBJ_SYOKUDAI        0x039
# define ACTOR_ITEM_B_HEART        0x03a
# define ACTOR_EN_DEKUNUTS         0x03b
# define ACTOR_EN_BBFALL           0x03c
# define ACTOR_ARMS_HOOK           0x03d
# define ACTOR_EN_BB               0x03e
# define ACTOR_BG_KEIKOKU_SPR      0x03f
# define ACTOR_EN_WOOD02           0x041
# define ACTOR_EN_DEATH            0x043
# define ACTOR_EN_MINIDEATH        0x044
# define ACTOR_EN_VM               0x047
# define ACTOR_DEMO_EFFECT         0x048
# define ACTOR_DEMO_KANKYO         0x049
# define ACTOR_EN_FLOORMAS         0x04a
# define ACTOR_EN_RD               0x04c
# define ACTOR_BG_F40_FLIFT        0x04d
# define ACTOR_BG_HEAVY_BLOCK      0x04e
# define ACTOR_OBJ_MURE            0x04f
# define ACTOR_EN_SW               0x050
# define ACTOR_OBJECT_KANKYO       0x051
# define ACTOR_EN_HORSE_LINK_CHILD 0x054
# define ACTOR_DOOR_ANA            0x055
# define ACTOR_EN_ENCOUNT1         0x05b
# define ACTOR_DEMO_TRE_LGT        0x05c
# define ACTOR_EN_ENCOUNT2         0x05f
# define ACTOR_EN_FIRE_ROCK        0x060
# define ACTOR_BG_CTOWER_ROT       0x061
# define ACTOR_MIR_RAY             0x062
# define ACTOR_EN_SB               0x064
# define ACTOR_EN_BIGSLIME         0x065
# define ACTOR_EN_KAREBABA         0x066
# define ACTOR_EN_IN               0x067
# define ACTOR_EN_RU               0x069
# define ACTOR_EN_BOM_CHU          0x06a
# define ACTOR_EN_HORSE_GAME_CHECK 0x06b
# define ACTOR_EN_RR               0x06c
# define ACTOR_EN_FR               0x073
# define ACTOR_EN_FISHING          0x079
# define ACTOR_OBJ_OSHIHIKI        0x07a
# define ACTOR_EFF_DUST            0x07b
# define ACTOR_BG_UMAJUMP          0x07c
# define ACTOR_ARROW_FIRE          0x07d
# define ACTOR_ARROW_ICE           0x07e
# define ACTOR_ARROW_LIGHT         0x07f
# define ACTOR_ITEM_ETCETERA       0x080
# define ACTOR_OBJ_KIBAKO          0x081
# define ACTOR_OBJ_TSUBO           0x082
# define ACTOR_EN_IK               0x084
# define ACTOR_DEMO_SHD            0x089
# define ACTOR_EN_DNS              0x08a
# define ACTOR_ELF_MSG             0x08b
# define ACTOR_EN_HONOTRAP         0x08c
# define ACTOR_EN_TUBO_TRAP        0x08d
# define ACTOR_OBJ_ICE_POLY        0x08e
# define ACTOR_EN_FZ               0x08f
# define ACTOR_EN_KUSA             0x090
# define ACTOR_OBJ_BEAN            0x091
# define ACTOR_OBJ_BOMBIWA         0x092
# define ACTOR_OBJ_SWITCH          0x093
# define ACTOR_OBJ_LIFT            0x095
# define ACTOR_OBJ_HSBLOCK         0x096
# define ACTOR_EN_OKARINA_TAG      0x097
# define ACTOR_EN_GOROIWA          0x099
# define ACTOR_EN_DAIKU            0x09c
# define ACTOR_EN_NWC              0x09d
# define ACTOR_ITEM_INBOX          0x09e
# define ACTOR_EN_GE1              0x09f
# define ACTOR_OBJ_BLOCKSTOP       0x0a0
# define ACTOR_EN_SDA              0x0a1
# define ACTOR_EN_CLEAR_TAG        0x0a2
# define ACTOR_EN_GM               0x0a4
# define ACTOR_EN_MS               0x0a5
# define ACTOR_EN_HS               0x0a6
# define ACTOR_BG_INGATE           0x0a7
# define ACTOR_EN_KANBAN           0x0a8
# define ACTOR_EN_ATTACK_NIW       0x0aa
# define ACTOR_EN_MK               0x0ae
# define ACTOR_EN_OWL              0x0af
# define ACTOR_EN_ISHI             0x0b0
# define ACTOR_OBJ_HANA            0x0b1
# define ACTOR_OBJ_LIGHTSWITCH     0x0b2
# define ACTOR_OBJ_MURE2           0x0b3
# define ACTOR_EN_FU               0x0b5
# define ACTOR_EN_STREAM           0x0b8
# define ACTOR_EN_MM               0x0b9
# define ACTOR_EN_WEATHER_TAG      0x0bc
# define ACTOR_EN_ANI              0x0bd
# define ACTOR_EN_JS               0x0bf
# define ACTOR_EN_OKARINA_EFFECT   0x0c4
# define ACTOR_EN_MAG              0x0c5
# define ACTOR_ELF_MSG2            0x0c6
# define ACTOR_BG_F40_SWLIFT       0x0c7
# define ACTOR_EN_KAKASI           0x0ca
# define ACTOR_OBJ_MAKEOSHIHIKI    0x0cb
# define ACTOR_OCEFF_SPOT          0x0cc
# define ACTOR_EN_TORCH            0x0ce
# define ACTOR_SHOT_SUN            0x0d0
# define ACTOR_OBJ_ROOMTIMER       0x0d3
# define ACTOR_EN_SSH              0x0d4
# define ACTOR_OCEFF_WIPE          0x0d6
# define ACTOR_OCEFF_STORM         0x0d7
# define ACTOR_OBJ_DEMO            0x0d8
# define ACTOR_EN_MINISLIME        0x0d9
# define ACTOR_EN_NUTSBALL         0x0da
# define ACTOR_OCEFF_WIPE2         0x0df
# define ACTOR_OCEFF_WIPE3         0x0e0
# define ACTOR_EN_DG               0x0e2
# define ACTOR_EN_SI               0x0e3
# define ACTOR_OBJ_COMB            0x0e4
# define ACTOR_OBJ_KIBAKO2         0x0e5
# define ACTOR_EN_HS2              0x0e7
# define ACTOR_OBJ_MURE3           0x0e8
# define ACTOR_EN_TG               0x0e9
# define ACTOR_EN_WF               0x0ec
# define ACTOR_EN_SKB              0x0ed
# define ACTOR_EN_GS               0x0ef
# define ACTOR_OBJ_SOUND           0x0f0
# define ACTOR_EN_CROW             0x0f1
# define ACTOR_EN_COW              0x0f3
# define ACTOR_OCEFF_WIPE4         0x0f6
# define ACTOR_EN_ZO               0x0f8
# define ACTOR_OBJ_MAKEKINSUTA     0x0f9
# define ACTOR_EN_GE3              0x0fa
# define ACTOR_OBJ_HAMISHI         0x0fc
# define ACTOR_EN_ZL4              0x0fd
# define ACTOR_EN_MM2              0x0fe
# define ACTOR_DOOR_SPIRAL         0x100
# define ACTOR_OBJ_PZLBLOCK        0x102
# define ACTOR_OBJ_TOGE            0x103
# define ACTOR_OBJ_ARMOS           0x105
# define ACTOR_OBJ_BOYO            0x106
# define ACTOR_EN_GRASSHOPPER      0x109
# define ACTOR_OBJ_GRASS           0x10b
# define ACTOR_OBJ_GRASS_CARRY     0x10c
# define ACTOR_OBJ_GRASS_UNIT      0x10d
# define ACTOR_BG_FIRE_WALL        0x110
# define ACTOR_EN_BU               0x111
# define ACTOR_EN_ENCOUNT3         0x112
# define ACTOR_EN_JSO              0x113
# define ACTOR_OBJ_CHIKUWA         0x114
# define ACTOR_EN_KNIGHT           0x115
# define ACTOR_EN_WARP_TAG         0x116
# define ACTOR_EN_AOB_01           0x117
# define ACTOR_EN_BOJ_01           0x118
# define ACTOR_EN_BOJ_02           0x119
# define ACTOR_EN_BOJ_03           0x11a
# define ACTOR_EN_ENCOUNT4         0x11b
# define ACTOR_EN_BOM_BOWL_MAN     0x11c
# define ACTOR_EN_SYATEKI_MAN      0x11d
# define ACTOR_BG_ICICLE           0x11f
# define ACTOR_EN_SYATEKI_CROW     0x120
# define ACTOR_EN_BOJ_04           0x121
# define ACTOR_EN_CNE_01           0x122
# define ACTOR_EN_BBA_01           0x123
# define ACTOR_EN_BJI_01           0x124
# define ACTOR_BG_SPDWEB           0x125
# define ACTOR_EN_MT_TAG           0x128
# define ACTOR_BOSS_01             0x129
# define ACTOR_BOSS_02             0x12a
# define ACTOR_BOSS_03             0x12b
# define ACTOR_BOSS_04             0x12c
# define ACTOR_BOSS_05             0x12d
# define ACTOR_BOSS_06             0x12e
# define ACTOR_BOSS_07             0x12f
# define ACTOR_BG_DY_YOSEIZO       0x130
# define ACTOR_EN_BOJ_05           0x132
# define ACTOR_EN_SOB1             0x135
# define ACTOR_EN_GO               0x138
# define ACTOR_EN_RAF              0x13a
# define ACTOR_OBJ_FUNEN           0x13b
# define ACTOR_OBJ_RAILLIFT        0x13c
# define ACTOR_BG_NUMA_HANA        0x13d
# define ACTOR_OBJ_FLOWERPOT       0x13e
# define ACTOR_OBJ_SPINYROLL       0x13f
# define ACTOR_DM_HINA             0x140
# define ACTOR_EN_SYATEKI_WF       0x141
# define ACTOR_OBJ_SKATEBLOCK      0x142
# define ACTOR_OBJ_ICEBLOCK        0x143
# define ACTOR_EN_BIGPAMET         0x144
# define ACTOR_EN_SYATEKI_DEKUNUTS 0x145
# define ACTOR_ELF_MSG3            0x146
# define ACTOR_EN_FG               0x147
# define ACTOR_DM_RAVINE           0x148
# define ACTOR_DM_SA               0x149
# define ACTOR_EN_SLIME            0x14a
# define ACTOR_EN_PR               0x14b
# define ACTOR_OBJ_TOUDAI          0x14c
# define ACTOR_OBJ_ENTOTU          0x14d
# define ACTOR_OBJ_BELL            0x14e
# define ACTOR_EN_SYATEKI_OKUTA    0x14f
# define ACTOR_OBJ_SHUTTER         0x151
# define ACTOR_DM_ZL               0x152
# define ACTOR_EN_ELFGRP           0x153
# define ACTOR_DM_TSG              0x154
# define ACTOR_EN_BAGUO            0x155
# define ACTOR_OBJ_VSPINYROLL      0x156
# define ACTOR_OBJ_SMORK           0x157
# define ACTOR_EN_TEST2            0x158
# define ACTOR_EN_TEST3            0x159
# define ACTOR_EN_TEST4            0x15a
# define ACTOR_EN_BAT              0x15b
# define ACTOR_EN_SEKIHI           0x15c
# define ACTOR_EN_WIZ              0x15d
# define ACTOR_EN_WIZ_BROCK        0x15e
# define ACTOR_EN_WIZ_FIRE         0x15f
# define ACTOR_EFF_CHANGE          0x160
# define ACTOR_DM_STATUE           0x161
# define ACTOR_OBJ_FIRESHIELD      0x162
# define ACTOR_BG_LADDER           0x163
# define ACTOR_EN_MKK              0x164
# define ACTOR_DEMO_GETITEM        0x165
# define ACTOR_EN_DNB              0x167
# define ACTOR_EN_DNH              0x168
# define ACTOR_EN_DNK              0x169
# define ACTOR_EN_DNQ              0x16a
# define ACTOR_BG_KEIKOKU_SAKU     0x16c
# define ACTOR_OBJ_HUGEBOMBIWA     0x16d
# define ACTOR_EN_FIREFLY2         0x16e
# define ACTOR_EN_RAT              0x16f
# define ACTOR_EN_WATER_EFFECT     0x170
# define ACTOR_EN_KUSA2            0x171
# define ACTOR_BG_SPOUT_FIRE       0x172
# define ACTOR_BG_DBLUE_MOVEBG     0x174
# define ACTOR_EN_DY_EXTRA         0x175
# define ACTOR_EN_BAL              0x176
# define ACTOR_EN_GINKO_MAN        0x177
# define ACTOR_EN_WARP_UZU         0x178
# define ACTOR_OBJ_DRIFTICE        0x179
# define ACTOR_EN_LOOK_NUTS        0x17a
# define ACTOR_EN_MUSHI2           0x17b
# define ACTOR_EN_FALL             0x17c
# define ACTOR_EN_MM3              0x17d
# define ACTOR_BG_CRACE_MOVEBG     0x17e
# define ACTOR_EN_DNO              0x17f
# define ACTOR_EN_PR2              0x180
# define ACTOR_EN_PRZ              0x181
# define ACTOR_EN_JSO2             0x182
# define ACTOR_OBJ_ETCETERA        0x183
# define ACTOR_EN_EGOL             0x184
# define ACTOR_OBJ_MINE            0x185
# define ACTOR_OBJ_PURIFY          0x186
# define ACTOR_EN_TRU              0x187
# define ACTOR_EN_TRT              0x188
# define ACTOR_EN_TEST5            0x18b
# define ACTOR_EN_TEST6            0x18c
# define ACTOR_EN_AZ               0x18d
# define ACTOR_EN_ESTONE           0x18e
# define ACTOR_BG_HAKUGIN_POST     0x18f
# define ACTOR_DM_OPSTAGE          0x190
# define ACTOR_DM_STK              0x191
# define ACTOR_DM_CHAR00           0x192
# define ACTOR_DM_CHAR01           0x193
# define ACTOR_DM_CHAR02           0x194
# define ACTOR_DM_CHAR03           0x195
# define ACTOR_DM_CHAR04           0x196
# define ACTOR_DM_CHAR05           0x197
# define ACTOR_DM_CHAR06           0x198
# define ACTOR_DM_CHAR07           0x199
# define ACTOR_DM_CHAR08           0x19a
# define ACTOR_DM_CHAR09           0x19b
# define ACTOR_OBJ_TOKEIDAI        0x19c
# define ACTOR_EN_MNK              0x19e
# define ACTOR_EN_EGBLOCK          0x19f
# define ACTOR_EN_GUARD_NUTS       0x1a0
# define ACTOR_BG_HAKUGIN_BOMBWALL 0x1a1
# define ACTOR_OBJ_TOKEI_TOBIRA    0x1a2
# define ACTOR_BG_HAKUGIN_ELVPOLE  0x1a3
# define ACTOR_EN_MA4              0x1a4
# define ACTOR_EN_TWIG             0x1a5
# define ACTOR_EN_PO_FUSEN         0x1a6
# define ACTOR_EN_DOOR_ETC         0x1a7
# define ACTOR_EN_BIGOKUTA         0x1a8
# define ACTOR_BG_ICEFLOE          0x1a9
# define ACTOR_OBJ_OCARINALIFT     0x1aa
# define ACTOR_EN_TIME_TAG         0x1ab
# define ACTOR_BG_OPEN_SHUTTER     0x1ac
# define ACTOR_BG_OPEN_SPOT        0x1ad
# define ACTOR_BG_FU_KAITEN        0x1ae
# define ACTOR_OBJ_AQUA            0x1af
# define ACTOR_EN_ELFORG           0x1b0
# define ACTOR_EN_ELFBUB           0x1b1
# define ACTOR_EN_FU_MATO          0x1b3
# define ACTOR_EN_FU_KAGO          0x1b4
# define ACTOR_EN_OSN              0x1b5
# define ACTOR_BG_CTOWER_GEAR      0x1b6
# define ACTOR_EN_TRT2             0x1b7
# define ACTOR_OBJ_TOKEI_STEP      0x1b8
# define ACTOR_BG_LOTUS            0x1b9
# define ACTOR_EN_KAME             0x1ba
# define ACTOR_OBJ_TAKARAYA_WALL   0x1bb
# define ACTOR_BG_FU_MIZU          0x1bc
# define ACTOR_EN_SELLNUTS         0x1bd
# define ACTOR_BG_DKJAIL_IVY       0x1be
# define ACTOR_OBJ_VISIBLOCK       0x1c0
# define ACTOR_EN_TAKARAYA         0x1c1
# define ACTOR_EN_TSN              0x1c2
# define ACTOR_EN_DS2N             0x1c3
# define ACTOR_EN_FSN              0x1c4
# define ACTOR_EN_SHN              0x1c5
# define ACTOR_EN_STOP_HEISHI      0x1c7
# define ACTOR_OBJ_BIGICICLE       0x1c8
# define ACTOR_EN_LIFT_NUTS        0x1c9
# define ACTOR_EN_TK               0x1ca
# define ACTOR_BG_MARKET_STEP      0x1cc
# define ACTOR_OBJ_LUPYGAMELIFT    0x1cd
# define ACTOR_EN_TEST7            0x1ce
# define ACTOR_MIR_RAY2            0x1d0
# define ACTOR_EN_WDHAND           0x1d1
# define ACTOR_EN_GAMELUPY         0x1d2
# define ACTOR_BG_DANPEI_MOVEBG    0x1d3
# define ACTOR_EN_SNOWWD           0x1d4
# define ACTOR_EN_PM               0x1d5
# define ACTOR_EN_GAKUFU           0x1d6
# define ACTOR_ELF_MSG4            0x1d7
# define ACTOR_ELF_MSG5            0x1d8
# define ACTOR_EN_COL_MAN          0x1d9
# define ACTOR_EN_TALK_GIBUD       0x1da
# define ACTOR_EN_GIANT            0x1db
# define ACTOR_OBJ_SNOWBALL        0x1dc
# define ACTOR_BOSS_HAKUGIN        0x1dd
# define ACTOR_EN_GB2              0x1de
# define ACTOR_EN_ONPUMAN          0x1df
# define ACTOR_BG_TOBIRA01         0x1e0
# define ACTOR_EN_TAG_OBJ          0x1e1
# define ACTOR_OBJ_DHOUSE          0x1e2
# define ACTOR_OBJ_HAKAISI         0x1e3
# define ACTOR_BG_HAKUGIN_SWITCH   0x1e4
# define ACTOR_EN_SNOWMAN          0x1e6
# define ACTOR_TG_SW               0x1e7
# define ACTOR_EN_PO_SISTERS       0x1e8
# define ACTOR_EN_PP               0x1e9
# define ACTOR_EN_HAKUROCK         0x1ea
# define ACTOR_EN_HANABI           0x1eb
# define ACTOR_OBJ_DOWSING         0x1ec
# define ACTOR_OBJ_WIND            0x1ed
# define ACTOR_EN_RACEDOG          0x1ee
# define ACTOR_EN_KENDO_JS         0x1ef
# define ACTOR_BG_BOTIHASIRA       0x1f0
# define ACTOR_EN_FISH2            0x1f1
# define ACTOR_EN_PST              0x1f2
# define ACTOR_EN_POH              0x1f3
# define ACTOR_OBJ_SPIDERTENT      0x1f4
# define ACTOR_EN_ZORAEGG          0x1f5
# define ACTOR_EN_KBT              0x1f6
# define ACTOR_EN_GG               0x1f7
# define ACTOR_EN_MARUTA           0x1f8
# define ACTOR_OBJ_SNOWBALL2       0x1f9
# define ACTOR_EN_GG2              0x1fa
# define ACTOR_OBJ_GHAKA           0x1fb
# define ACTOR_EN_DNP              0x1fc
# define ACTOR_EN_DAI              0x1fd
# define ACTOR_BG_GORON_OYU        0x1fe
# define ACTOR_EN_KGY              0x1ff
# define ACTOR_EN_INVADEPOH        0x200
# define ACTOR_EN_GK               0x201
# define ACTOR_EN_AN               0x202
# define ACTOR_EN_BEE              0x204
# define ACTOR_EN_OT               0x205
# define ACTOR_EN_DRAGON           0x206
# define ACTOR_OBJ_DORA            0x207
# define ACTOR_EN_BIGPO            0x208
# define ACTOR_OBJ_KENDO_KANBAN    0x209
# define ACTOR_OBJ_HARIKO          0x20a
# define ACTOR_EN_STH              0x20b
# define ACTOR_BG_SINKAI_KABE      0x20c
# define ACTOR_BG_HAKA_CURTAIN     0x20d
# define ACTOR_BG_KIN2_BOMBWALL    0x20e
# define ACTOR_BG_KIN2_FENCE       0x20f
# define ACTOR_BG_KIN2_PICTURE     0x210
# define ACTOR_BG_KIN2_SHELF       0x211
# define ACTOR_EN_RAIL_SKB         0x212
# define ACTOR_EN_JG               0x213
# define ACTOR_EN_TRU_MT           0x214
# define ACTOR_OBJ_UM              0x215
# define ACTOR_EN_NEO_REEBA        0x216
# define ACTOR_BG_MBAR_CHAIR       0x217
# define ACTOR_BG_IKANA_BLOCK      0x218
# define ACTOR_BG_IKANA_MIRROR     0x219
# define ACTOR_BG_IKANA_ROTARYROOM 0x21a
# define ACTOR_BG_DBLUE_BALANCE    0x21b
# define ACTOR_BG_DBLUE_WATERFALL  0x21c
# define ACTOR_EN_KAIZOKU          0x21d
# define ACTOR_EN_GE2              0x21e
# define ACTOR_EN_MA_YTS           0x21f
# define ACTOR_EN_MA_YTO           0x220
# define ACTOR_OBJ_TOKEI_TURRET    0x221
# define ACTOR_BG_DBLUE_ELEVATOR   0x222
# define ACTOR_OBJ_WARPSTONE       0x223
# define ACTOR_EN_ZOG              0x224
# define ACTOR_OBJ_ROTLIFT         0x225
# define ACTOR_OBJ_JG_GAKKI        0x226
# define ACTOR_BG_INIBS_MOVEBG     0x227
# define ACTOR_EN_ZOT              0x228
# define ACTOR_OBJ_TREE            0x229
# define ACTOR_OBJ_Y2LIFT          0x22a
# define ACTOR_OBJ_Y2SHUTTER       0x22b
# define ACTOR_OBJ_BOAT            0x22c
# define ACTOR_OBJ_TARU            0x22d
# define ACTOR_OBJ_HUNSUI          0x22e
# define ACTOR_EN_JC_MATO          0x22f
# define ACTOR_MIR_RAY3            0x230
# define ACTOR_EN_ZOB              0x231
# define ACTOR_ELF_MSG6            0x232
# define ACTOR_OBJ_NOZOKI          0x233
# define ACTOR_EN_TOTO             0x234
# define ACTOR_EN_RAILGIBUD        0x235
# define ACTOR_EN_BABA             0x236
# define ACTOR_EN_SUTTARI          0x237
# define ACTOR_EN_ZOD              0x238
# define ACTOR_EN_KUJIYA           0x239
# define ACTOR_EN_GEG              0x23a
# define ACTOR_OBJ_KINOKO          0x23b
# define ACTOR_OBJ_YASI            0x23c
# define ACTOR_EN_TANRON1          0x23d
# define ACTOR_EN_TANRON2          0x23e
# define ACTOR_EN_TANRON3          0x23f
# define ACTOR_OBJ_CHAN            0x240
# define ACTOR_EN_ZOS              0x241
# define ACTOR_EN_S_GORO           0x242
# define ACTOR_EN_NB               0x243
# define ACTOR_EN_JA               0x244
# define ACTOR_BG_F40_BLOCK        0x245
# define ACTOR_BG_F40_SWITCH       0x246
# define ACTOR_EN_PO_COMPOSER      0x247
# define ACTOR_EN_GURUGURU         0x248
# define ACTOR_OCEFF_WIPE5         0x249
# define ACTOR_EN_STONE_HEISHI     0x24a
# define ACTOR_OCEFF_WIPE6         0x24b
# define ACTOR_EN_SCOPENUTS        0x24c
# define ACTOR_EN_SCOPECROW        0x24d
# define ACTOR_OCEFF_WIPE7         0x24e
# define ACTOR_EFF_KAMEJIMA_WAVE   0x24f
# define ACTOR_EN_HG               0x250
# define ACTOR_EN_HGO              0x251
# define ACTOR_EN_ZOV              0x252
# define ACTOR_EN_AH               0x253
# define ACTOR_OBJ_HGDOOR          0x254
# define ACTOR_BG_IKANA_BOMBWALL   0x255
# define ACTOR_BG_IKANA_RAY        0x256
# define ACTOR_BG_IKANA_SHUTTER    0x257
# define ACTOR_BG_HAKA_BOMBWALL    0x258
# define ACTOR_BG_HAKA_TOMB        0x259
# define ACTOR_EN_SC_RUPPE         0x25a
# define ACTOR_BG_IKNV_DOUKUTU     0x25b
# define ACTOR_BG_IKNV_OBJ         0x25c
# define ACTOR_EN_PAMERA           0x25d
# define ACTOR_OBJ_HSSTUMP         0x25e
# define ACTOR_EN_HIDDEN_NUTS      0x25f
# define ACTOR_EN_ZOW              0x260
# define ACTOR_EN_TALK             0x261
# define ACTOR_EN_AL               0x262
# define ACTOR_EN_TAB              0x263
# define ACTOR_EN_NIMOTSU          0x264
# define ACTOR_EN_HIT_TAG          0x265
# define ACTOR_EN_RUPPECROW        0x266
# define ACTOR_EN_TANRON4          0x267
# define ACTOR_EN_TANRON5          0x268
# define ACTOR_EN_TANRON6          0x269
# define ACTOR_EN_DAIKU2           0x26a
# define ACTOR_EN_MUTO             0x26b
# define ACTOR_EN_BAISEN           0x26c
# define ACTOR_EN_HEISHI           0x26d
# define ACTOR_EN_DEMO_HEISHI      0x26e
# define ACTOR_EN_DT               0x26f
# define ACTOR_EN_CHA              0x270
# define ACTOR_OBJ_DINNER          0x271
# define ACTOR_EFF_LASTDAY         0x272
# define ACTOR_BG_IKANA_DHARMA     0x273
# define ACTOR_EN_AKINDONUTS       0x274
# define ACTOR_EFF_STK             0x275
# define ACTOR_EN_IG               0x276
# define ACTOR_EN_RG               0x277
# define ACTOR_EN_OSK              0x278
# define ACTOR_EN_STH2             0x279
# define ACTOR_EN_YB               0x27a
# define ACTOR_EN_RZ               0x27b
# define ACTOR_EN_SCOPECOIN        0x27c
# define ACTOR_EN_BJT              0x27d
# define ACTOR_EN_BOMJIMA          0x27e
# define ACTOR_EN_BOMJIMB          0x27f
# define ACTOR_EN_BOMBERS          0x280
# define ACTOR_EN_BOMBERS2         0x281
# define ACTOR_EN_BOMBAL           0x282
# define ACTOR_OBJ_MOON_STONE      0x283
# define ACTOR_OBJ_MU_PICT         0x284
# define ACTOR_BG_IKNINSIDE        0x285
# define ACTOR_EFF_ZORABAND        0x286
# define ACTOR_OBJ_KEPN_KOYA       0x287
# define ACTOR_OBJ_USIYANE         0x288
# define ACTOR_EN_NNH              0x289
# define ACTOR_OBJ_KZSAKU          0x28a
# define ACTOR_OBJ_MILK_BIN        0x28b
# define ACTOR_EN_KITAN            0x28c
# define ACTOR_BG_ASTR_BOMBWALL    0x28d
# define ACTOR_BG_IKNIN_SUSCEIL    0x28e
# define ACTOR_EN_BSB              0x28f
# define ACTOR_EN_RECEPGIRL        0x290
# define ACTOR_EN_THIEFBIRD        0x291
# define ACTOR_EN_JGAME_TSN        0x292
# define ACTOR_OBJ_JGAME_LIGHT     0x293
# define ACTOR_OBJ_YADO            0x294
# define ACTOR_DEMO_SYOTEN         0x295
# define ACTOR_DEMO_MOONEND        0x296
# define ACTOR_BG_LBFSHOT          0x297
# define ACTOR_BG_LAST_BWALL       0x298
# define ACTOR_EN_AND              0x299
# define ACTOR_EN_INVADEPOH_DEMO   0x29a
# define ACTOR_OBJ_DANPEILIFT      0x29b
# define ACTOR_EN_FALL2            0x29c
# define ACTOR_DM_AL               0x29d
# define ACTOR_DM_AN               0x29e
# define ACTOR_DM_AH               0x29f
# define ACTOR_DM_NB               0x2a0
# define ACTOR_EN_DRS              0x2a1
# define ACTOR_EN_ENDING_HERO      0x2a2
# define ACTOR_DM_BAL              0x2a3
# define ACTOR_EN_PAPER            0x2a4
# define ACTOR_EN_HINT_SKB         0x2a5
# define ACTOR_DM_TAG              0x2a6
# define ACTOR_EN_BH               0x2a7
# define ACTOR_EN_ENDING_HERO2     0x2a8
# define ACTOR_EN_ENDING_HERO3     0x2a9
# define ACTOR_EN_ENDING_HERO4     0x2aa
# define ACTOR_EN_ENDING_HERO5     0x2ab
# define ACTOR_EN_ENDING_HERO6     0x2ac
# define ACTOR_DM_GM               0x2ad
# define ACTOR_OBJ_SWPRIZE         0x2ae
# define ACTOR_EN_INVISIBLE_RUPPE  0x2af
# define ACTOR_OBJ_ENDING          0x2b0
# define ACTOR_EN_RSN              0x2b1
#endif

#endif
