#ifndef COMBO_OBJECT_ID_H
#define COMBO_OBJECT_ID_H

#if defined(GAME_OOT)
# define OBJECT_INVALID                 0x000
# define OBJECT_GAMEPLAY_KEEP           0x001
# define OBJECT_GAMEPLAY_FIELD_KEEP     0x002
# define OBJECT_GAMEPLAY_DANGEON_KEEP   0x003
# define OBJECT_UNSET_4                 0x004
# define OBJECT_UNSET_5                 0x005
# define OBJECT_HUMAN                   0x006
# define OBJECT_OKUTA                   0x007
# define OBJECT_CROW                    0x008
# define OBJECT_POH                     0x009
# define OBJECT_DY_OBJ                  0x00a
# define OBJECT_WALLMASTER              0x00b
# define OBJECT_DODONGO                 0x00c
# define OBJECT_FIREFLY                 0x00d
# define OBJECT_BOX                     0x00e
# define OBJECT_FIRE                    0x00f
# define OBJECT_UNSET_10                0x010
# define OBJECT_UNSET_11                0x011
# define OBJECT_BUBBLE                  0x012
# define OBJECT_NIW                     0x013
# define OBJECT_LINK_BOY                0x014
# define OBJECT_LINK_CHILD              0x015
# define OBJECT_TITE                    0x016
# define OBJECT_REEBA                   0x017
# define OBJECT_PEEHAT                  0x018
# define OBJECT_KINGDODONGO             0x019
# define OBJECT_HORSE                   0x01a
# define OBJECT_ZF                      0x01b
# define OBJECT_GOMA                    0x01c
# define OBJECT_ZL1                     0x01d
# define OBJECT_GOL                     0x01e
# define OBJECT_DODOJR                  0x01f
# define OBJECT_TORCH2                  0x020
# define OBJECT_BL                      0x021
# define OBJECT_TP                      0x022
# define OBJECT_OA1                     0x023
# define OBJECT_ST                      0x024
# define OBJECT_BW                      0x025
# define OBJECT_EI                      0x026
# define OBJECT_HORSE_NORMAL            0x027
# define OBJECT_OB1                     0x028
# define OBJECT_O_ANIME                 0x029
# define OBJECT_SPOT04_OBJECTS          0x02a
# define OBJECT_DDAN_OBJECTS            0x02b
# define OBJECT_HIDAN_OBJECTS           0x02c
# define OBJECT_HORSE_GANON             0x02d
# define OBJECT_OA2                     0x02e
# define OBJECT_SPOT00_OBJECTS          0x02f
# define OBJECT_MB                      0x030
# define OBJECT_BOMBF                   0x031
# define OBJECT_SK2                     0x032
# define OBJECT_OE1                     0x033
# define OBJECT_OE_ANIME                0x034
# define OBJECT_OE2                     0x035
# define OBJECT_YDAN_OBJECTS            0x036
# define OBJECT_GND                     0x037
# define OBJECT_AM                      0x038
# define OBJECT_DEKUBABA                0x039
# define OBJECT_UNSET_3A                0x03a
# define OBJECT_OA3                     0x03b
# define OBJECT_OA4                     0x03c
# define OBJECT_OA5                     0x03d
# define OBJECT_OA6                     0x03e
# define OBJECT_OA7                     0x03f
# define OBJECT_JJ                      0x040
# define OBJECT_OA8                     0x041
# define OBJECT_OA9                     0x042
# define OBJECT_OB2                     0x043
# define OBJECT_OB3                     0x044
# define OBJECT_OB4                     0x045
# define OBJECT_HORSE_ZELDA             0x046
# define OBJECT_OPENING_DEMO1           0x047
# define OBJECT_WARP1                   0x048
# define OBJECT_B_HEART                 0x049
# define OBJECT_DEKUNUTS                0x04a
# define OBJECT_OE3                     0x04b
# define OBJECT_OE4                     0x04c
# define OBJECT_MENKURI_OBJECTS         0x04d
# define OBJECT_OE5                     0x04e
# define OBJECT_OE6                     0x04f
# define OBJECT_OE7                     0x050
# define OBJECT_OE8                     0x051
# define OBJECT_OE9                     0x052
# define OBJECT_OE10                    0x053
# define OBJECT_OE11                    0x054
# define OBJECT_OE12                    0x055
# define OBJECT_VALI                    0x056
# define OBJECT_OA10                    0x057
# define OBJECT_OA11                    0x058
# define OBJECT_MIZU_OBJECTS            0x059
# define OBJECT_FHG                     0x05a
# define OBJECT_OSSAN                   0x05b
# define OBJECT_MORI_HINERI1            0x05c
# define OBJECT_BB                      0x05d
# define OBJECT_TOKI_OBJECTS            0x05e
# define OBJECT_YUKABYUN                0x05f
# define OBJECT_ZL2                     0x060
# define OBJECT_MJIN                    0x061
# define OBJECT_MJIN_FLASH              0x062
# define OBJECT_MJIN_DARK               0x063
# define OBJECT_MJIN_FLAME              0x064
# define OBJECT_MJIN_ICE                0x065
# define OBJECT_MJIN_SOUL               0x066
# define OBJECT_MJIN_WIND               0x067
# define OBJECT_MJIN_OKA                0x068
# define OBJECT_HAKA_OBJECTS            0x069
# define OBJECT_SPOT06_OBJECTS          0x06a
# define OBJECT_ICE_OBJECTS             0x06b
# define OBJECT_RELAY_OBJECTS           0x06c
# define OBJECT_PO_FIELD                0x06d
# define OBJECT_PO_COMPOSER             0x06e
# define OBJECT_MORI_HINERI1A           0x06f
# define OBJECT_MORI_HINERI2            0x070
# define OBJECT_MORI_HINERI2A           0x071
# define OBJECT_MORI_OBJECTS            0x072
# define OBJECT_MORI_TEX                0x073
# define OBJECT_SPOT08_OBJ              0x074
# define OBJECT_WARP2                   0x075
# define OBJECT_HATA                    0x076
# define OBJECT_BIRD                    0x077
# define OBJECT_UNSET_78                0x078
# define OBJECT_UNSET_79                0x079
# define OBJECT_UNSET_7A                0x07a
# define OBJECT_UNSET_7B                0x07b
# define OBJECT_WOOD02                  0x07c
# define OBJECT_UNSET_7D                0x07d
# define OBJECT_UNSET_7E                0x07e
# define OBJECT_UNSET_7F                0x07f
# define OBJECT_UNSET_80                0x080
# define OBJECT_LIGHTBOX                0x081
# define OBJECT_PU_BOX                  0x082
# define OBJECT_UNSET_83                0x083
# define OBJECT_UNSET_84                0x084
# define OBJECT_TRAP                    0x085
# define OBJECT_VASE                    0x086
# define OBJECT_IM                      0x087
# define OBJECT_TA                      0x088
# define OBJECT_TK                      0x089
# define OBJECT_XC                      0x08a
# define OBJECT_VM                      0x08b
# define OBJECT_BV                      0x08c
# define OBJECT_HAKACH_OBJECTS          0x08d
# define OBJECT_EFC_CRYSTAL_LIGHT       0x08e
# define OBJECT_EFC_FIRE_BALL           0x08f
# define OBJECT_EFC_FLASH               0x090
# define OBJECT_EFC_LGT_SHOWER          0x091
# define OBJECT_EFC_STAR_FIELD          0x092
# define OBJECT_GOD_LGT                 0x093
# define OBJECT_LIGHT_RING              0x094
# define OBJECT_TRIFORCE_SPOT           0x095
# define OBJECT_BDAN_OBJECTS            0x096
# define OBJECT_SD                      0x097
# define OBJECT_RD                      0x098
# define OBJECT_PO_SISTERS              0x099
# define OBJECT_HEAVY_OBJECT            0x09a
# define OBJECT_GNDD                    0x09b
# define OBJECT_FD                      0x09c
# define OBJECT_DU                      0x09d
# define OBJECT_FW                      0x09e
# define OBJECT_MEDAL                   0x09f
# define OBJECT_HORSE_LINK_CHILD        0x0a0
# define OBJECT_SPOT02_OBJECTS          0x0a1
# define OBJECT_HAKA                    0x0a2
# define OBJECT_RU1                     0x0a3
# define OBJECT_SYOKUDAI                0x0a4
# define OBJECT_FD2                     0x0a5
# define OBJECT_DH                      0x0a6
# define OBJECT_RL                      0x0a7
# define OBJECT_EFC_TW                  0x0a8
# define OBJECT_DEMO_TRE_LGT            0x0a9
# define OBJECT_GI_KEY                  0x0aa
# define OBJECT_MIR_RAY                 0x0ab
# define OBJECT_BROB                    0x0ac
# define OBJECT_GI_JEWEL                0x0ad
# define OBJECT_SPOT09_OBJ              0x0ae
# define OBJECT_SPOT18_OBJ              0x0af
# define OBJECT_BDOOR                   0x0b0
# define OBJECT_SPOT17_OBJ              0x0b1
# define OBJECT_SHOP_DUNGEN             0x0b2
# define OBJECT_NB                      0x0b3
# define OBJECT_MO                      0x0b4
# define OBJECT_SB                      0x0b5
# define OBJECT_GI_MELODY               0x0b6
# define OBJECT_GI_HEART                0x0b7
# define OBJECT_GI_COMPASS              0x0b8
# define OBJECT_GI_BOSSKEY              0x0b9
# define OBJECT_GI_MEDAL                0x0ba
# define OBJECT_GI_NUTS                 0x0bb
# define OBJECT_SA                      0x0bc
# define OBJECT_GI_HEARTS               0x0bd
# define OBJECT_GI_ARROWCASE            0x0be
# define OBJECT_GI_BOMBPOUCH            0x0bf
# define OBJECT_IN                      0x0c0
# define OBJECT_TR                      0x0c1
# define OBJECT_SPOT16_OBJ              0x0c2
# define OBJECT_OE1S                    0x0c3
# define OBJECT_OE4S                    0x0c4
# define OBJECT_OS_ANIME                0x0c5
# define OBJECT_GI_BOTTLE               0x0c6
# define OBJECT_GI_STICK                0x0c7
# define OBJECT_GI_MAP                  0x0c8
# define OBJECT_OF1D_MAP                0x0c9
# define OBJECT_RU2                     0x0ca
# define OBJECT_GI_SHIELD_1             0x0cb
# define OBJECT_DEKUJR                  0x0cc
# define OBJECT_GI_MAGICPOT             0x0cd
# define OBJECT_GI_BOMB_1               0x0ce
# define OBJECT_OF1S                    0x0cf
# define OBJECT_MA2                     0x0d0
# define OBJECT_GI_PURSE                0x0d1
# define OBJECT_HNI                     0x0d2
# define OBJECT_TW                      0x0d3
# define OBJECT_RR                      0x0d4
# define OBJECT_BXA                     0x0d5
# define OBJECT_ANUBICE                 0x0d6
# define OBJECT_GI_GERUDO               0x0d7
# define OBJECT_GI_ARROW                0x0d8
# define OBJECT_GI_BOMB_2               0x0d9
# define OBJECT_GI_EGG                  0x0da
# define OBJECT_GI_SCALE                0x0db
# define OBJECT_GI_SHIELD_2             0x0dc
# define OBJECT_GI_HOOKSHOT             0x0dd
# define OBJECT_GI_OCARINA              0x0de
# define OBJECT_GI_MILK                 0x0df
# define OBJECT_MA1                     0x0e0
# define OBJECT_GANON                   0x0e1
# define OBJECT_SST                     0x0e2
# define OBJECT_NY_UNUSED               0x0e3
# define OBJECT_UNSET_E4                0x0e4
# define OBJECT_NY                      0x0e5
# define OBJECT_FR                      0x0e6
# define OBJECT_GI_PACHINKO             0x0e7
# define OBJECT_GI_BOOMERANG            0x0e8
# define OBJECT_GI_BOW                  0x0e9
# define OBJECT_GI_GLASSES              0x0ea
# define OBJECT_GI_LIQUID               0x0eb
# define OBJECT_ANI                     0x0ec
# define OBJECT_DEMO_6K                 0x0ed
# define OBJECT_GI_SHIELD_3             0x0ee
# define OBJECT_GI_LETTER               0x0ef
# define OBJECT_SPOT15_OBJ              0x0f0
# define OBJECT_JYA_OBJ                 0x0f1
# define OBJECT_GI_CLOTHES              0x0f2
# define OBJECT_GI_BEAN                 0x0f3
# define OBJECT_GI_FISH                 0x0f4
# define OBJECT_GI_SAW                  0x0f5
# define OBJECT_GI_HAMMER               0x0f6
# define OBJECT_GI_GRASS                0x0f7
# define OBJECT_GI_LONGSWORD            0x0f8
# define OBJECT_SPOT01_OBJECTS          0x0f9
# define OBJECT_MD_UNUSED               0x0fa
# define OBJECT_MD                      0x0fb
# define OBJECT_KM1                     0x0fc
# define OBJECT_KW1                     0x0fd
# define OBJECT_ZO                      0x0fe
# define OBJECT_KZ                      0x0ff
# define OBJECT_UMAJUMP                 0x100
# define OBJECT_MASTERKOKIRI            0x101
# define OBJECT_MASTERKOKIRIHEAD        0x102
# define OBJECT_MASTERGOLON             0x103
# define OBJECT_MASTERZOORA             0x104
# define OBJECT_AOB                     0x105
# define OBJECT_IK                      0x106
# define OBJECT_AHG                     0x107
# define OBJECT_CNE                     0x108
# define OBJECT_GI_NIWATORI             0x109
# define OBJECT_SKJ                     0x10a
# define OBJECT_GI_BOTTLE_LETTER        0x10b
# define OBJECT_BJI                     0x10c
# define OBJECT_BBA                     0x10d
# define OBJECT_GI_OCARINA_0            0x10e
# define OBJECT_DS                      0x10f
# define OBJECT_ANE                     0x110
# define OBJECT_BOJ                     0x111
# define OBJECT_SPOT03_OBJECT           0x112
# define OBJECT_SPOT07_OBJECT           0x113
# define OBJECT_FZ                      0x114
# define OBJECT_BOB                     0x115
# define OBJECT_GE1                     0x116
# define OBJECT_YABUSAME_POINT          0x117
# define OBJECT_GI_BOOTS_2              0x118
# define OBJECT_GI_SEED                 0x119
# define OBJECT_GND_MAGIC               0x11a
# define OBJECT_D_ELEVATOR              0x11b
# define OBJECT_D_HSBLOCK               0x11c
# define OBJECT_D_LIFT                  0x11d
# define OBJECT_MAMENOKI                0x11e
# define OBJECT_GOROIWA                 0x11f
# define OBJECT_UNSET_120               0x120
# define OBJECT_TORYO                   0x121
# define OBJECT_DAIKU                   0x122
# define OBJECT_UNSET_123               0x123
# define OBJECT_NWC                     0x124
# define OBJECT_BLKOBJ                  0x125
# define OBJECT_GM                      0x126
# define OBJECT_MS                      0x127
# define OBJECT_HS                      0x128
# define OBJECT_INGATE                  0x129
# define OBJECT_LIGHTSWITCH             0x12a
# define OBJECT_KUSA                    0x12b
# define OBJECT_TSUBO                   0x12c
# define OBJECT_GI_GLOVES               0x12d
# define OBJECT_GI_COIN                 0x12e
# define OBJECT_KANBAN                  0x12f
# define OBJECT_GJYO_OBJECTS            0x130
# define OBJECT_OWL                     0x131
# define OBJECT_MK                      0x132
# define OBJECT_FU                      0x133
# define OBJECT_GI_KI_TAN_MASK          0x134
# define OBJECT_GI_REDEAD_MASK          0x135
# define OBJECT_GI_SKJ_MASK             0x136
# define OBJECT_GI_RABIT_MASK           0x137
# define OBJECT_GI_TRUTH_MASK           0x138
# define OBJECT_GANON_OBJECTS           0x139
# define OBJECT_SIOFUKI                 0x13a
# define OBJECT_STREAM                  0x13b
# define OBJECT_MM                      0x13c
# define OBJECT_FA                      0x13d
# define OBJECT_OS                      0x13e
# define OBJECT_GI_EYE_LOTION           0x13f
# define OBJECT_GI_POWDER               0x140
# define OBJECT_GI_MUSHROOM             0x141
# define OBJECT_GI_TICKETSTONE          0x142
# define OBJECT_GI_BROKENSWORD          0x143
# define OBJECT_JS                      0x144
# define OBJECT_CS                      0x145
# define OBJECT_GI_PRESCRIPTION         0x146
# define OBJECT_GI_BRACELET             0x147
# define OBJECT_GI_SOLDOUT              0x148
# define OBJECT_GI_FROG                 0x149
# define OBJECT_MAG                     0x14a
# define OBJECT_DOOR_GERUDO             0x14b
# define OBJECT_GT                      0x14c
# define OBJECT_EFC_ERUPC               0x14d
# define OBJECT_ZL2_ANIME1              0x14e
# define OBJECT_ZL2_ANIME2              0x14f
# define OBJECT_GI_GOLONMASK            0x150
# define OBJECT_GI_ZORAMASK             0x151
# define OBJECT_GI_GERUDOMASK           0x152
# define OBJECT_GANON2                  0x153
# define OBJECT_KA                      0x154
# define OBJECT_TS                      0x155
# define OBJECT_ZG                      0x156
# define OBJECT_GI_HOVERBOOTS           0x157
# define OBJECT_GI_M_ARROW              0x158
# define OBJECT_DS2                     0x159
# define OBJECT_EC                      0x15a
# define OBJECT_FISH                    0x15b
# define OBJECT_GI_SUTARU               0x15c
# define OBJECT_GI_GODDESS              0x15d
# define OBJECT_SSH                     0x15e
# define OBJECT_BIGOKUTA                0x15f
# define OBJECT_BG                      0x160
# define OBJECT_SPOT05_OBJECTS          0x161
# define OBJECT_SPOT12_OBJ              0x162
# define OBJECT_BOMBIWA                 0x163
# define OBJECT_HINTNUTS                0x164
# define OBJECT_RS                      0x165
# define OBJECT_SPOT00_BREAK            0x166
# define OBJECT_GLA                     0x167
# define OBJECT_SHOPNUTS                0x168
# define OBJECT_GELDB                   0x169
# define OBJECT_GR                      0x16a
# define OBJECT_DOG                     0x16b
# define OBJECT_JYA_IRON                0x16c
# define OBJECT_JYA_DOOR                0x16d
# define OBJECT_UNSET_16E               0x16e
# define OBJECT_SPOT11_OBJ              0x16f
# define OBJECT_KIBAKO2                 0x170
# define OBJECT_DNS                     0x171
# define OBJECT_DNK                     0x172
# define OBJECT_GI_FIRE                 0x173
# define OBJECT_GI_INSECT               0x174
# define OBJECT_GI_BUTTERFLY            0x175
# define OBJECT_GI_GHOST                0x176
# define OBJECT_GI_SOUL                 0x177
# define OBJECT_BOWL                    0x178
# define OBJECT_DEMO_KEKKAI             0x179
# define OBJECT_EFC_DOUGHNUT            0x17a
# define OBJECT_GI_DEKUPOUCH            0x17b
# define OBJECT_GANON_ANIME1            0x17c
# define OBJECT_GANON_ANIME2            0x17d
# define OBJECT_GANON_ANIME3            0x17e
# define OBJECT_GI_RUPY                 0x17f
# define OBJECT_SPOT01_MATOYA           0x180
# define OBJECT_SPOT01_MATOYAB          0x181
# define OBJECT_MU                      0x182
# define OBJECT_WF                      0x183
# define OBJECT_SKB                     0x184
# define OBJECT_GJ                      0x185
# define OBJECT_GEFF                    0x186
# define OBJECT_HAKA_DOOR               0x187
# define OBJECT_GS                      0x188
# define OBJECT_PS                      0x189
# define OBJECT_BWALL                   0x18a
# define OBJECT_COW                     0x18b
# define OBJECT_COB                     0x18c
# define OBJECT_GI_SWORD_1              0x18d
# define OBJECT_DOOR_KILLER             0x18e
# define OBJECT_OUKE_HAKA               0x18f
# define OBJECT_TIMEBLOCK               0x190
# define OBJECT_ZL4                     0x191
#endif

#endif
