#ifndef COMBO_OBJECT_ID_H
#define COMBO_OBJECT_ID_H

#if defined(GAME_OOT)
# define OBJECT_INVALID                 0x000
# define OBJECT_GAMEPLAY_KEEP           0x001
# define OBJECT_GAMEPLAY_FIELD_KEEP     0x002
# define OBJECT_GAMEPLAY_DANGEON_KEEP   0x003
# define OBJECT_UNSET_4                 0x004
# define OBJECT_UNSET_5                 0x005
# define OBJECT_HUMAN                   0x006
# define OBJECT_OKUTA                   0x007
# define OBJECT_CROW                    0x008
# define OBJECT_POH                     0x009
# define OBJECT_DY_OBJ                  0x00a
# define OBJECT_WALLMASTER              0x00b
# define OBJECT_DODONGO                 0x00c
# define OBJECT_FIREFLY                 0x00d
# define OBJECT_BOX                     0x00e
# define OBJECT_FIRE                    0x00f
# define OBJECT_UNSET_10                0x010
# define OBJECT_UNSET_11                0x011
# define OBJECT_BUBBLE                  0x012
# define OBJECT_NIW                     0x013
# define OBJECT_LINK_BOY                0x014
# define OBJECT_LINK_CHILD              0x015
# define OBJECT_TITE                    0x016
# define OBJECT_REEBA                   0x017
# define OBJECT_PEEHAT                  0x018
# define OBJECT_KINGDODONGO             0x019
# define OBJECT_HORSE                   0x01a
# define OBJECT_ZF                      0x01b
# define OBJECT_GOMA                    0x01c
# define OBJECT_ZL1                     0x01d
# define OBJECT_GOL                     0x01e
# define OBJECT_DODOJR                  0x01f
# define OBJECT_TORCH2                  0x020
# define OBJECT_BL                      0x021
# define OBJECT_TP                      0x022
# define OBJECT_OA1                     0x023
# define OBJECT_ST                      0x024
# define OBJECT_BW                      0x025
# define OBJECT_EI                      0x026
# define OBJECT_HORSE_NORMAL            0x027
# define OBJECT_OB1                     0x028
# define OBJECT_O_ANIME                 0x029
# define OBJECT_SPOT04_OBJECTS          0x02a
# define OBJECT_DDAN_OBJECTS            0x02b
# define OBJECT_HIDAN_OBJECTS           0x02c
# define OBJECT_HORSE_GANON             0x02d
# define OBJECT_OA2                     0x02e
# define OBJECT_SPOT00_OBJECTS          0x02f
# define OBJECT_MB                      0x030
# define OBJECT_BOMBF                   0x031
# define OBJECT_SK2                     0x032
# define OBJECT_OE1                     0x033
# define OBJECT_OE_ANIME                0x034
# define OBJECT_OE2                     0x035
# define OBJECT_YDAN_OBJECTS            0x036
# define OBJECT_GND                     0x037
# define OBJECT_AM                      0x038
# define OBJECT_DEKUBABA                0x039
# define OBJECT_UNSET_3A                0x03a
# define OBJECT_OA3                     0x03b
# define OBJECT_OA4                     0x03c
# define OBJECT_OA5                     0x03d
# define OBJECT_OA6                     0x03e
# define OBJECT_OA7                     0x03f
# define OBJECT_JJ                      0x040
# define OBJECT_OA8                     0x041
# define OBJECT_OA9                     0x042
# define OBJECT_OB2                     0x043
# define OBJECT_OB3                     0x044
# define OBJECT_OB4                     0x045
# define OBJECT_HORSE_ZELDA             0x046
# define OBJECT_OPENING_DEMO1           0x047
# define OBJECT_WARP1                   0x048
# define OBJECT_B_HEART                 0x049
# define OBJECT_DEKUNUTS                0x04a
# define OBJECT_OE3                     0x04b
# define OBJECT_OE4                     0x04c
# define OBJECT_MENKURI_OBJECTS         0x04d
# define OBJECT_OE5                     0x04e
# define OBJECT_OE6                     0x04f
# define OBJECT_OE7                     0x050
# define OBJECT_OE8                     0x051
# define OBJECT_OE9                     0x052
# define OBJECT_OE10                    0x053
# define OBJECT_OE11                    0x054
# define OBJECT_OE12                    0x055
# define OBJECT_VALI                    0x056
# define OBJECT_OA10                    0x057
# define OBJECT_OA11                    0x058
# define OBJECT_MIZU_OBJECTS            0x059
# define OBJECT_FHG                     0x05a
# define OBJECT_OSSAN                   0x05b
# define OBJECT_MORI_HINERI1            0x05c
# define OBJECT_BB                      0x05d
# define OBJECT_TOKI_OBJECTS            0x05e
# define OBJECT_YUKABYUN                0x05f
# define OBJECT_ZL2                     0x060
# define OBJECT_MJIN                    0x061
# define OBJECT_MJIN_FLASH              0x062
# define OBJECT_MJIN_DARK               0x063
# define OBJECT_MJIN_FLAME              0x064
# define OBJECT_MJIN_ICE                0x065
# define OBJECT_MJIN_SOUL               0x066
# define OBJECT_MJIN_WIND               0x067
# define OBJECT_MJIN_OKA                0x068
# define OBJECT_HAKA_OBJECTS            0x069
# define OBJECT_SPOT06_OBJECTS          0x06a
# define OBJECT_ICE_OBJECTS             0x06b
# define OBJECT_RELAY_OBJECTS           0x06c
# define OBJECT_PO_FIELD                0x06d
# define OBJECT_PO_COMPOSER             0x06e
# define OBJECT_MORI_HINERI1A           0x06f
# define OBJECT_MORI_HINERI2            0x070
# define OBJECT_MORI_HINERI2A           0x071
# define OBJECT_MORI_OBJECTS            0x072
# define OBJECT_MORI_TEX                0x073
# define OBJECT_SPOT08_OBJ              0x074
# define OBJECT_WARP2                   0x075
# define OBJECT_HATA                    0x076
# define OBJECT_BIRD                    0x077
# define OBJECT_UNSET_78                0x078
# define OBJECT_UNSET_79                0x079
# define OBJECT_UNSET_7A                0x07a
# define OBJECT_UNSET_7B                0x07b
# define OBJECT_WOOD02                  0x07c
# define OBJECT_UNSET_7D                0x07d
# define OBJECT_UNSET_7E                0x07e
# define OBJECT_UNSET_7F                0x07f
# define OBJECT_UNSET_80                0x080
# define OBJECT_LIGHTBOX                0x081
# define OBJECT_PU_BOX                  0x082
# define OBJECT_UNSET_83                0x083
# define OBJECT_UNSET_84                0x084
# define OBJECT_TRAP                    0x085
# define OBJECT_VASE                    0x086
# define OBJECT_IM                      0x087
# define OBJECT_TA                      0x088
# define OBJECT_TK                      0x089
# define OBJECT_XC                      0x08a
# define OBJECT_VM                      0x08b
# define OBJECT_BV                      0x08c
# define OBJECT_HAKACH_OBJECTS          0x08d
# define OBJECT_EFC_CRYSTAL_LIGHT       0x08e
# define OBJECT_EFC_FIRE_BALL           0x08f
# define OBJECT_EFC_FLASH               0x090
# define OBJECT_EFC_LGT_SHOWER          0x091
# define OBJECT_EFC_STAR_FIELD          0x092
# define OBJECT_GOD_LGT                 0x093
# define OBJECT_LIGHT_RING              0x094
# define OBJECT_TRIFORCE_SPOT           0x095
# define OBJECT_BDAN_OBJECTS            0x096
# define OBJECT_SD                      0x097
# define OBJECT_RD                      0x098
# define OBJECT_PO_SISTERS              0x099
# define OBJECT_HEAVY_OBJECT            0x09a
# define OBJECT_GNDD                    0x09b
# define OBJECT_FD                      0x09c
# define OBJECT_DU                      0x09d
# define OBJECT_FW                      0x09e
# define OBJECT_MEDAL                   0x09f
# define OBJECT_HORSE_LINK_CHILD        0x0a0
# define OBJECT_SPOT02_OBJECTS          0x0a1
# define OBJECT_HAKA                    0x0a2
# define OBJECT_RU1                     0x0a3
# define OBJECT_SYOKUDAI                0x0a4
# define OBJECT_FD2                     0x0a5
# define OBJECT_DH                      0x0a6
# define OBJECT_RL                      0x0a7
# define OBJECT_EFC_TW                  0x0a8
# define OBJECT_DEMO_TRE_LGT            0x0a9
# define OBJECT_GI_KEY                  0x0aa
# define OBJECT_MIR_RAY                 0x0ab
# define OBJECT_BROB                    0x0ac
# define OBJECT_GI_JEWEL                0x0ad
# define OBJECT_SPOT09_OBJ              0x0ae
# define OBJECT_SPOT18_OBJ              0x0af
# define OBJECT_BDOOR                   0x0b0
# define OBJECT_SPOT17_OBJ              0x0b1
# define OBJECT_SHOP_DUNGEN             0x0b2
# define OBJECT_NB                      0x0b3
# define OBJECT_MO                      0x0b4
# define OBJECT_SB                      0x0b5
# define OBJECT_GI_MELODY               0x0b6
# define OBJECT_GI_HEART                0x0b7
# define OBJECT_GI_COMPASS              0x0b8
# define OBJECT_GI_BOSSKEY              0x0b9
# define OBJECT_GI_MEDAL                0x0ba
# define OBJECT_GI_NUTS                 0x0bb
# define OBJECT_SA                      0x0bc
# define OBJECT_GI_HEARTS               0x0bd
# define OBJECT_GI_ARROWCASE            0x0be
# define OBJECT_GI_BOMBPOUCH            0x0bf
# define OBJECT_IN                      0x0c0
# define OBJECT_TR                      0x0c1
# define OBJECT_SPOT16_OBJ              0x0c2
# define OBJECT_OE1S                    0x0c3
# define OBJECT_OE4S                    0x0c4
# define OBJECT_OS_ANIME                0x0c5
# define OBJECT_GI_BOTTLE               0x0c6
# define OBJECT_GI_STICK                0x0c7
# define OBJECT_GI_MAP                  0x0c8
# define OBJECT_OF1D_MAP                0x0c9
# define OBJECT_RU2                     0x0ca
# define OBJECT_GI_SHIELD_1             0x0cb
# define OBJECT_DEKUJR                  0x0cc
# define OBJECT_GI_MAGICPOT             0x0cd
# define OBJECT_GI_BOMB_1               0x0ce
# define OBJECT_OF1S                    0x0cf
# define OBJECT_MA2                     0x0d0
# define OBJECT_GI_PURSE                0x0d1
# define OBJECT_HNI                     0x0d2
# define OBJECT_TW                      0x0d3
# define OBJECT_RR                      0x0d4
# define OBJECT_BXA                     0x0d5
# define OBJECT_ANUBICE                 0x0d6
# define OBJECT_GI_GERUDO               0x0d7
# define OBJECT_GI_ARROW                0x0d8
# define OBJECT_GI_BOMB_2               0x0d9
# define OBJECT_GI_EGG                  0x0da
# define OBJECT_GI_SCALE                0x0db
# define OBJECT_GI_SHIELD_2             0x0dc
# define OBJECT_GI_HOOKSHOT             0x0dd
# define OBJECT_GI_OCARINA              0x0de
# define OBJECT_GI_MILK                 0x0df
# define OBJECT_MA1                     0x0e0
# define OBJECT_GANON                   0x0e1
# define OBJECT_SST                     0x0e2
# define OBJECT_NY_UNUSED               0x0e3
# define OBJECT_UNSET_E4                0x0e4
# define OBJECT_NY                      0x0e5
# define OBJECT_FR                      0x0e6
# define OBJECT_GI_PACHINKO             0x0e7
# define OBJECT_GI_BOOMERANG            0x0e8
# define OBJECT_GI_BOW                  0x0e9
# define OBJECT_GI_GLASSES              0x0ea
# define OBJECT_GI_LIQUID               0x0eb
# define OBJECT_ANI                     0x0ec
# define OBJECT_DEMO_6K                 0x0ed
# define OBJECT_GI_SHIELD_3             0x0ee
# define OBJECT_GI_LETTER               0x0ef
# define OBJECT_SPOT15_OBJ              0x0f0
# define OBJECT_JYA_OBJ                 0x0f1
# define OBJECT_GI_CLOTHES              0x0f2
# define OBJECT_GI_BEAN                 0x0f3
# define OBJECT_GI_FISH                 0x0f4
# define OBJECT_GI_SAW                  0x0f5
# define OBJECT_GI_HAMMER               0x0f6
# define OBJECT_GI_GRASS                0x0f7
# define OBJECT_GI_LONGSWORD            0x0f8
# define OBJECT_SPOT01_OBJECTS          0x0f9
# define OBJECT_MD_UNUSED               0x0fa
# define OBJECT_MD                      0x0fb
# define OBJECT_KM1                     0x0fc
# define OBJECT_KW1                     0x0fd
# define OBJECT_ZO                      0x0fe
# define OBJECT_KZ                      0x0ff
# define OBJECT_UMAJUMP                 0x100
# define OBJECT_MASTERKOKIRI            0x101
# define OBJECT_MASTERKOKIRIHEAD        0x102
# define OBJECT_MASTERGOLON             0x103
# define OBJECT_MASTERZOORA             0x104
# define OBJECT_AOB                     0x105
# define OBJECT_IK                      0x106
# define OBJECT_AHG                     0x107
# define OBJECT_CNE                     0x108
# define OBJECT_GI_NIWATORI             0x109
# define OBJECT_SKJ                     0x10a
# define OBJECT_GI_BOTTLE_LETTER        0x10b
# define OBJECT_BJI                     0x10c
# define OBJECT_BBA                     0x10d
# define OBJECT_GI_OCARINA_0            0x10e
# define OBJECT_DS                      0x10f
# define OBJECT_ANE                     0x110
# define OBJECT_BOJ                     0x111
# define OBJECT_SPOT03_OBJECT           0x112
# define OBJECT_SPOT07_OBJECT           0x113
# define OBJECT_FZ                      0x114
# define OBJECT_BOB                     0x115
# define OBJECT_GE1                     0x116
# define OBJECT_YABUSAME_POINT          0x117
# define OBJECT_GI_BOOTS_2              0x118
# define OBJECT_GI_SEED                 0x119
# define OBJECT_GND_MAGIC               0x11a
# define OBJECT_D_ELEVATOR              0x11b
# define OBJECT_D_HSBLOCK               0x11c
# define OBJECT_D_LIFT                  0x11d
# define OBJECT_MAMENOKI                0x11e
# define OBJECT_GOROIWA                 0x11f
# define OBJECT_UNSET_120               0x120
# define OBJECT_TORYO                   0x121
# define OBJECT_DAIKU                   0x122
# define OBJECT_UNSET_123               0x123
# define OBJECT_NWC                     0x124
# define OBJECT_BLKOBJ                  0x125
# define OBJECT_GM                      0x126
# define OBJECT_MS                      0x127
# define OBJECT_HS                      0x128
# define OBJECT_INGATE                  0x129
# define OBJECT_LIGHTSWITCH             0x12a
# define OBJECT_KUSA                    0x12b
# define OBJECT_TSUBO                   0x12c
# define OBJECT_GI_GLOVES               0x12d
# define OBJECT_GI_COIN                 0x12e
# define OBJECT_KANBAN                  0x12f
# define OBJECT_GJYO_OBJECTS            0x130
# define OBJECT_OWL                     0x131
# define OBJECT_MK                      0x132
# define OBJECT_FU                      0x133
# define OBJECT_GI_KI_TAN_MASK          0x134
# define OBJECT_GI_REDEAD_MASK          0x135
# define OBJECT_GI_SKJ_MASK             0x136
# define OBJECT_GI_RABIT_MASK           0x137
# define OBJECT_GI_TRUTH_MASK           0x138
# define OBJECT_GANON_OBJECTS           0x139
# define OBJECT_SIOFUKI                 0x13a
# define OBJECT_STREAM                  0x13b
# define OBJECT_MM                      0x13c
# define OBJECT_FA                      0x13d
# define OBJECT_OS                      0x13e
# define OBJECT_GI_EYE_LOTION           0x13f
# define OBJECT_GI_POWDER               0x140
# define OBJECT_GI_MUSHROOM             0x141
# define OBJECT_GI_TICKETSTONE          0x142
# define OBJECT_GI_BROKENSWORD          0x143
# define OBJECT_JS                      0x144
# define OBJECT_CS                      0x145
# define OBJECT_GI_PRESCRIPTION         0x146
# define OBJECT_GI_BRACELET             0x147
# define OBJECT_GI_SOLDOUT              0x148
# define OBJECT_GI_FROG                 0x149
# define OBJECT_MAG                     0x14a
# define OBJECT_DOOR_GERUDO             0x14b
# define OBJECT_GT                      0x14c
# define OBJECT_EFC_ERUPC               0x14d
# define OBJECT_ZL2_ANIME1              0x14e
# define OBJECT_ZL2_ANIME2              0x14f
# define OBJECT_GI_GOLONMASK            0x150
# define OBJECT_GI_ZORAMASK             0x151
# define OBJECT_GI_GERUDOMASK           0x152
# define OBJECT_GANON2                  0x153
# define OBJECT_KA                      0x154
# define OBJECT_TS                      0x155
# define OBJECT_ZG                      0x156
# define OBJECT_GI_HOVERBOOTS           0x157
# define OBJECT_GI_M_ARROW              0x158
# define OBJECT_DS2                     0x159
# define OBJECT_EC                      0x15a
# define OBJECT_FISH                    0x15b
# define OBJECT_GI_SUTARU               0x15c
# define OBJECT_GI_GODDESS              0x15d
# define OBJECT_SSH                     0x15e
# define OBJECT_BIGOKUTA                0x15f
# define OBJECT_BG                      0x160
# define OBJECT_SPOT05_OBJECTS          0x161
# define OBJECT_SPOT12_OBJ              0x162
# define OBJECT_BOMBIWA                 0x163
# define OBJECT_HINTNUTS                0x164
# define OBJECT_RS                      0x165
# define OBJECT_SPOT00_BREAK            0x166
# define OBJECT_GLA                     0x167
# define OBJECT_SHOPNUTS                0x168
# define OBJECT_GELDB                   0x169
# define OBJECT_GR                      0x16a
# define OBJECT_DOG                     0x16b
# define OBJECT_JYA_IRON                0x16c
# define OBJECT_JYA_DOOR                0x16d
# define OBJECT_UNSET_16E               0x16e
# define OBJECT_SPOT11_OBJ              0x16f
# define OBJECT_KIBAKO2                 0x170
# define OBJECT_DNS                     0x171
# define OBJECT_DNK                     0x172
# define OBJECT_GI_FIRE                 0x173
# define OBJECT_GI_INSECT               0x174
# define OBJECT_GI_BUTTERFLY            0x175
# define OBJECT_GI_GHOST                0x176
# define OBJECT_GI_SOUL                 0x177
# define OBJECT_BOWL                    0x178
# define OBJECT_DEMO_KEKKAI             0x179
# define OBJECT_EFC_DOUGHNUT            0x17a
# define OBJECT_GI_DEKUPOUCH            0x17b
# define OBJECT_GANON_ANIME1            0x17c
# define OBJECT_GANON_ANIME2            0x17d
# define OBJECT_GANON_ANIME3            0x17e
# define OBJECT_GI_RUPY                 0x17f
# define OBJECT_SPOT01_MATOYA           0x180
# define OBJECT_SPOT01_MATOYAB          0x181
# define OBJECT_MU                      0x182
# define OBJECT_WF                      0x183
# define OBJECT_SKB                     0x184
# define OBJECT_GJ                      0x185
# define OBJECT_GEFF                    0x186
# define OBJECT_HAKA_DOOR               0x187
# define OBJECT_GS                      0x188
# define OBJECT_PS                      0x189
# define OBJECT_BWALL                   0x18a
# define OBJECT_COW                     0x18b
# define OBJECT_COB                     0x18c
# define OBJECT_GI_SWORD_1              0x18d
# define OBJECT_DOOR_KILLER             0x18e
# define OBJECT_OUKE_HAKA               0x18f
# define OBJECT_TIMEBLOCK               0x190
# define OBJECT_ZL4                     0x191
#endif

#if defined(GAME_MM)
# define OBJECT_INVALID                 0x000
# define OBJECT_GAMEPLAY_KEEP           0x001
# define OBJECT_GAMEPLAY_FIELD_KEEP     0x002
# define OBJECT_GAMEPLAY_DANGEON_KEEP   0x003
# define OBJECT_NB                      0x004
# define OBJECT_OKUTA                   0x005
# define OBJECT_CROW                    0x006
# define OBJECT_AH                      0x007
# define OBJECT_DY_OBJ                  0x008
# define OBJECT_WALLMASTER              0x009
# define OBJECT_DODONGO                 0x00a
# define OBJECT_FIREFLY                 0x00b
# define OBJECT_BOX                     0x00c
# define OBJECT_AL                      0x00d
# define OBJECT_BUBBLE                  0x00e
# define OBJECT_NIW                     0x00f
# define OBJECT_LINK_BOY                0x010
# define OBJECT_LINK_CHILD              0x011
# define OBJECT_TITE                    0x012
# define OBJECT_TAB                     0x013
# define OBJECT_PH                      0x014
# define OBJECT_AND                     0x015
# define OBJECT_MSMO                    0x016
# define OBJECT_DINOFOS                 0x017
# define OBJECT_DRS                     0x018
# define OBJECT_ZL1                     0x019
# define OBJECT_AN4                     0x01a
# define OBJECT_UNSET_1B                0x01b
# define OBJECT_TEST3                   0x01c
# define OBJECT_FAMOS                   0x01d
# define OBJECT_UNSET_1E                0x01e
# define OBJECT_UNSET_1F                0x01f
# define OBJECT_ST                      0x020
# define OBJECT_UNSET_21                0x021
# define OBJECT_THIEFBIRD               0x022
# define OBJECT_UNSET_23                0x023
# define OBJECT_UNSET_24                0x024
# define OBJECT_UNSET_25                0x025
# define OBJECT_UNSET_26                0x026
# define OBJECT_UNSET_27                0x027
# define OBJECT_UNSET_28                0x028
# define OBJECT_UNSET_29                0x029
# define OBJECT_BOMBF                   0x02a
# define OBJECT_UNSET_2B                0x02b
# define OBJECT_UNSET_2C                0x02c
# define OBJECT_UNSET_2D                0x02d
# define OBJECT_UNSET_2E                0x02e
# define OBJECT_UNSET_2F                0x02f
# define OBJECT_AM                      0x030
# define OBJECT_DEKUBABA                0x031
# define OBJECT_UNSET_32                0x032
# define OBJECT_UNSET_33                0x033
# define OBJECT_UNSET_34                0x034
# define OBJECT_UNSET_35                0x035
# define OBJECT_UNSET_36                0x036
# define OBJECT_UNSET_37                0x037
# define OBJECT_UNSET_38                0x038
# define OBJECT_UNSET_39                0x039
# define OBJECT_UNSET_3A                0x03a
# define OBJECT_UNSET_3B                0x03b
# define OBJECT_UNSET_3C                0x03c
# define OBJECT_UNSET_3D                0x03d
# define OBJECT_WARP1                   0x03e
# define OBJECT_B_HEART                 0x03f
# define OBJECT_DEKUNUTS                0x040
# define OBJECT_UNSET_41                0x041
# define OBJECT_UNSET_42                0x042
# define OBJECT_UNSET_43                0x043
# define OBJECT_UNSET_44                0x044
# define OBJECT_UNSET_45                0x045
# define OBJECT_UNSET_46                0x046
# define OBJECT_UNSET_47                0x047
# define OBJECT_UNSET_48                0x048
# define OBJECT_UNSET_49                0x049
# define OBJECT_UNSET_4A                0x04a
# define OBJECT_UNSET_4B                0x04b
# define OBJECT_UNSET_4C                0x04c
# define OBJECT_UNSET_4D                0x04d
# define OBJECT_UNSET_4E                0x04e
# define OBJECT_UNSET_4F                0x04f
# define OBJECT_UNSET_50                0x050
# define OBJECT_BB                      0x051
# define OBJECT_DEATH                   0x052
# define OBJECT_UNSET_53                0x053
# define OBJECT_UNSET_54                0x054
# define OBJECT_UNSET_55                0x055
# define OBJECT_UNSET_56                0x056
# define OBJECT_UNSET_57                0x057
# define OBJECT_UNSET_58                0x058
# define OBJECT_UNSET_59                0x059
# define OBJECT_UNSET_5A                0x05a
# define OBJECT_UNSET_5B                0x05b
# define OBJECT_F40_OBJ                 0x05c
# define OBJECT_PO_COMPOSER             0x05d
# define OBJECT_UNSET_5E                0x05e
# define OBJECT_HATA                    0x05f
# define OBJECT_UNSET_60                0x060
# define OBJECT_WOOD02                  0x061
# define OBJECT_UNSET_62                0x062
# define OBJECT_UNSET_63                0x063
# define OBJECT_TRAP                    0x064
# define OBJECT_UNSET_65                0x065
# define OBJECT_UNSET_66                0x066
# define OBJECT_UNSET_67                0x067
# define OBJECT_UNSET_68                0x068
# define OBJECT_UNSET_69                0x069
# define OBJECT_VM                      0x06a
# define OBJECT_UNSET_6B                0x06b
# define OBJECT_UNSET_6C                0x06c
# define OBJECT_UNSET_6D                0x06d
# define OBJECT_UNSET_6E                0x06e
# define OBJECT_UNSET_6F                0x06f
# define OBJECT_EFC_STAR_FIELD          0x070
# define OBJECT_UNSET_71                0x071
# define OBJECT_UNSET_72                0x072
# define OBJECT_UNSET_73                0x073
# define OBJECT_UNSET_74                0x074
# define OBJECT_RD                      0x075
# define OBJECT_YUKIMURA_OBJ            0x076
# define OBJECT_HEAVY_OBJECT            0x077
# define OBJECT_UNSET_78                0x078
# define OBJECT_UNSET_79                0x079
# define OBJECT_UNSET_7A                0x07a
# define OBJECT_UNSET_7B                0x07b
# define OBJECT_UNSET_7C                0x07c
# define OBJECT_HORSE_LINK_CHILD        0x07d
# define OBJECT_UNSET_7E                0x07e
# define OBJECT_UNSET_7F                0x07f
# define OBJECT_SYOKUDAI                0x080
# define OBJECT_UNSET_81                0x081
# define OBJECT_UNSET_82                0x082
# define OBJECT_UNSET_83                0x083
# define OBJECT_EFC_TW                  0x084
# define OBJECT_UNSET_85                0x085
# define OBJECT_GI_KEY                  0x086
# define OBJECT_MIR_RAY                 0x087
# define OBJECT_CTOWER_ROT              0x088
# define OBJECT_UNSET_89                0x089
# define OBJECT_BDOOR                   0x08a
# define OBJECT_UNSET_8B                0x08b
# define OBJECT_UNSET_8C                0x08c
# define OBJECT_UNSET_8D                0x08d
# define OBJECT_SB                      0x08e
# define OBJECT_GI_MELODY               0x08f
# define OBJECT_GI_HEART                0x090
# define OBJECT_GI_COMPASS              0x091
# define OBJECT_GI_BOSSKEY              0x092
# define OBJECT_UNSET_93                0x093
# define OBJECT_GI_NUTS                 0x094
# define OBJECT_UNSET_95                0x095
# define OBJECT_GI_HEARTS               0x096
# define OBJECT_GI_ARROWCASE            0x097
# define OBJECT_GI_BOMBPOUCH            0x098
# define OBJECT_IN                      0x099
# define OBJECT_UNSET_9A                0x09a
# define OBJECT_UNSET_9B                0x09b
# define OBJECT_UNSET_9C                0x09c
# define OBJECT_OS_ANIME                0x09d
# define OBJECT_GI_BOTTLE               0x09e
# define OBJECT_GI_STICK                0x09f
# define OBJECT_GI_MAP                  0x0a0
# define OBJECT_OF1D_MAP                0x0a1
# define OBJECT_RU2                     0x0a2
# define OBJECT_UNSET_A3                0x0a3
# define OBJECT_GI_MAGICPOT             0x0a4
# define OBJECT_GI_BOMB_1               0x0a5
# define OBJECT_UNSET_A6                0x0a6
# define OBJECT_MA2                     0x0a7
# define OBJECT_GI_PURSE                0x0a8
# define OBJECT_UNSET_A9                0x0a9
# define OBJECT_UNSET_AA                0x0aa
# define OBJECT_RR                      0x0ab
# define OBJECT_UNSET_AC                0x0ac
# define OBJECT_UNSET_AD                0x0ad
# define OBJECT_UNSET_AE                0x0ae
# define OBJECT_GI_ARROW                0x0af
# define OBJECT_GI_BOMB_2               0x0b0
# define OBJECT_UNSET_B1                0x0b1
# define OBJECT_UNSET_B2                0x0b2
# define OBJECT_GI_SHIELD_2             0x0b3
# define OBJECT_GI_HOOKSHOT             0x0b4
# define OBJECT_GI_OCARINA              0x0b5
# define OBJECT_GI_MILK                 0x0b6
# define OBJECT_MA1                     0x0b7
# define OBJECT_UNSET_B8                0x0b8
# define OBJECT_UNSET_B9                0x0b9
# define OBJECT_UNSET_BA                0x0ba
# define OBJECT_NY                      0x0bb
# define OBJECT_FR                      0x0bc
# define OBJECT_UNSET_BD                0x0bd
# define OBJECT_UNSET_BE                0x0be
# define OBJECT_GI_BOW                  0x0bf
# define OBJECT_GI_GLASSES              0x0c0
# define OBJECT_GI_LIQUID               0x0c1
# define OBJECT_ANI                     0x0c2
# define OBJECT_GI_SHIELD_3             0x0c3
# define OBJECT_UNSET_C4                0x0c4
# define OBJECT_UNSET_C5                0x0c5
# define OBJECT_GI_BEAN                 0x0c6
# define OBJECT_GI_FISH                 0x0c7
# define OBJECT_UNSET_C8                0x0c8
# define OBJECT_UNSET_C9                0x0c9
# define OBJECT_UNSET_CA                0x0ca
# define OBJECT_GI_LONGSWORD            0x0cb
# define OBJECT_UNSET_CC                0x0cc
# define OBJECT_UNSET_CD                0x0cd
# define OBJECT_UNSET_CE                0x0ce
# define OBJECT_UNSET_CF                0x0cf
# define OBJECT_ZO                      0x0d0
# define OBJECT_UNSET_D1                0x0d1
# define OBJECT_UMAJUMP                 0x0d2
# define OBJECT_UNSET_D3                0x0d3
# define OBJECT_UNSET_D4                0x0d4
# define OBJECT_MASTERGOLON             0x0d5
# define OBJECT_MASTERZOORA             0x0d6
# define OBJECT_AOB                     0x0d7
# define OBJECT_IK                      0x0d8
# define OBJECT_AHG                     0x0d9
# define OBJECT_CNE                     0x0da
# define OBJECT_UNSET_DB                0x0db
# define OBJECT_UNSET_DC                0x0dc
# define OBJECT_AN3                     0x0dd
# define OBJECT_BJI                     0x0de
# define OBJECT_BBA                     0x0df
# define OBJECT_AN2                     0x0e0
# define OBJECT_UNSET_E1                0x0e1
# define OBJECT_AN1                     0x0e2
# define OBJECT_BOJ                     0x0e3
# define OBJECT_FZ                      0x0e4
# define OBJECT_BOB                     0x0e5
# define OBJECT_GE1                     0x0e6
# define OBJECT_YABUSAME_POINT          0x0e7
# define OBJECT_UNSET_E8                0x0e8
# define OBJECT_UNSET_E9                0x0e9
# define OBJECT_UNSET_EA                0x0ea
# define OBJECT_UNSET_EB                0x0eb
# define OBJECT_D_HSBLOCK               0x0ec
# define OBJECT_D_LIFT                  0x0ed
# define OBJECT_MAMENOKI                0x0ee
# define OBJECT_GOROIWA                 0x0ef
# define OBJECT_TORYO                   0x0f0
# define OBJECT_DAIKU                   0x0f1
# define OBJECT_NWC                     0x0f2
# define OBJECT_GM                      0x0f3
# define OBJECT_MS                      0x0f4
# define OBJECT_HS                      0x0f5
# define OBJECT_UNSET_F6                0x0f6
# define OBJECT_LIGHTSWITCH             0x0f7
# define OBJECT_KUSA                    0x0f8
# define OBJECT_TSUBO                   0x0f9
# define OBJECT_UNSET_FA                0x0fa
# define OBJECT_UNSET_FB                0x0fb
# define OBJECT_KANBAN                  0x0fc
# define OBJECT_OWL                     0x0fd
# define OBJECT_MK                      0x0fe
# define OBJECT_FU                      0x0ff
# define OBJECT_GI_KI_TAN_MASK          0x100
# define OBJECT_UNSET_101               0x101
# define OBJECT_GI_MASK18               0x102
# define OBJECT_GI_RABIT_MASK           0x103
# define OBJECT_GI_TRUTH_MASK           0x104
# define OBJECT_UNSET_105               0x105
# define OBJECT_STREAM                  0x106
# define OBJECT_MM                      0x107
# define OBJECT_UNSET_108               0x108
# define OBJECT_UNSET_109               0x109
# define OBJECT_UNSET_10A               0x10a
# define OBJECT_UNSET_10B               0x10b
# define OBJECT_UNSET_10C               0x10c
# define OBJECT_UNSET_10D               0x10d
# define OBJECT_UNSET_10E               0x10e
# define OBJECT_JS                      0x10f
# define OBJECT_CS                      0x110
# define OBJECT_UNSET_111               0x111
# define OBJECT_UNSET_112               0x112
# define OBJECT_GI_SOLDOUT              0x113
# define OBJECT_UNSET_114               0x114
# define OBJECT_MAG                     0x115
# define OBJECT_UNSET_116               0x116
# define OBJECT_UNSET_117               0x117
# define OBJECT_UNSET_118               0x118
# define OBJECT_GI_GOLONMASK            0x119
# define OBJECT_GI_ZORAMASK             0x11a
# define OBJECT_UNSET_11B               0x11b
# define OBJECT_UNSET_11C               0x11c
# define OBJECT_KA                      0x11d
# define OBJECT_UNSET_11E               0x11e
# define OBJECT_ZG                      0x11f
# define OBJECT_UNSET_120               0x120
# define OBJECT_GI_M_ARROW              0x121
# define OBJECT_DS2                     0x122
# define OBJECT_UNSET_123               0x123
# define OBJECT_FISH                    0x124
# define OBJECT_GI_SUTARU               0x125
# define OBJECT_UNSET_126               0x126
# define OBJECT_SSH                     0x127
# define OBJECT_BIGSLIME                0x128
# define OBJECT_BG                      0x129
# define OBJECT_BOMBIWA                 0x12a
# define OBJECT_HINTNUTS                0x12b
# define OBJECT_RSN                     0x12c
# define OBJECT_UNSET_12D               0x12d
# define OBJECT_GLA                     0x12e
# define OBJECT_UNSET_12F               0x12f
# define OBJECT_GELDB                   0x130
# define OBJECT_UNSET_131               0x131
# define OBJECT_DOG                     0x132
# define OBJECT_KIBAKO2                 0x133
# define OBJECT_DNS                     0x134
# define OBJECT_DNK                     0x135
# define OBJECT_UNSET_136               0x136
# define OBJECT_GI_INSECT               0x137
# define OBJECT_UNSET_138               0x138
# define OBJECT_GI_GHOST                0x139
# define OBJECT_GI_SOUL                 0x13a
# define OBJECT_UNSET_13B               0x13b
# define OBJECT_UNSET_13C               0x13c
# define OBJECT_UNSET_13D               0x13d
# define OBJECT_UNSET_13E               0x13e
# define OBJECT_GI_RUPY                 0x13f
# define OBJECT_MU                      0x140
# define OBJECT_WF                      0x141
# define OBJECT_SKB                     0x142
# define OBJECT_GS                      0x143
# define OBJECT_PS                      0x144
# define OBJECT_OMOYA_OBJ               0x145
# define OBJECT_COW                     0x146
# define OBJECT_UNSET_147               0x147
# define OBJECT_GI_SWORD_1              0x148
# define OBJECT_UNSET_149               0x149
# define OBJECT_UNSET_14A               0x14a
# define OBJECT_ZL4                     0x14b
# define OBJECT_LINK_GORON              0x14c
# define OBJECT_LINK_ZORA               0x14d
# define OBJECT_GRASSHOPPER             0x14e
# define OBJECT_BOYO                    0x14f
# define OBJECT_UNSET_150               0x150
# define OBJECT_UNSET_151               0x151
# define OBJECT_UNSET_152               0x152
# define OBJECT_FWALL                   0x153
# define OBJECT_LINK_NUTS               0x154
# define OBJECT_JSO                     0x155
# define OBJECT_KNIGHT                  0x156
# define OBJECT_ICICLE                  0x157
# define OBJECT_SPDWEB                  0x158
# define OBJECT_UNSET_159               0x159
# define OBJECT_BOSS01                  0x15a
# define OBJECT_BOSS02                  0x15b
# define OBJECT_BOSS03                  0x15c
# define OBJECT_BOSS04                  0x15d
# define OBJECT_BOSS05                  0x15e
# define OBJECT_BOSS06                  0x15f
# define OBJECT_BOSS07                  0x160
# define OBJECT_RAF                     0x161
# define OBJECT_FUNEN                   0x162
# define OBJECT_RAILLIFT                0x163
# define OBJECT_NUMA_OBJ                0x164
# define OBJECT_FLOWERPOT               0x165
# define OBJECT_SPINYROLL               0x166
# define OBJECT_ICE_BLOCK               0x167
# define OBJECT_UNSET_168               0x168
# define OBJECT_KEIKOKU_DEMO            0x169
# define OBJECT_SLIME                   0x16a
# define OBJECT_PR                      0x16b
# define OBJECT_F52_OBJ                 0x16c
# define OBJECT_F53_OBJ                 0x16d
# define OBJECT_UNSET_16E               0x16e
# define OBJECT_KIBAKO                  0x16f
# define OBJECT_SEK                     0x170
# define OBJECT_GMO                     0x171
# define OBJECT_BAT                     0x172
# define OBJECT_SEKIHIL                 0x173
# define OBJECT_SEKIHIG                 0x174
# define OBJECT_SEKIHIN                 0x175
# define OBJECT_SEKIHIZ                 0x176
# define OBJECT_UNSET_177               0x177
# define OBJECT_WIZ                     0x178
# define OBJECT_LADDER                  0x179
# define OBJECT_MKK                     0x17a
# define OBJECT_UNSET_17B               0x17b
# define OBJECT_UNSET_17C               0x17c
# define OBJECT_UNSET_17D               0x17d
# define OBJECT_KEIKOKU_OBJ             0x17e
# define OBJECT_SICHITAI_OBJ            0x17f
# define OBJECT_DEKUCITY_ANA_OBJ        0x180
# define OBJECT_RAT                     0x181
# define OBJECT_WATER_EFFECT            0x182
# define OBJECT_UNSET_183               0x183
# define OBJECT_DBLUE_OBJECT            0x184
# define OBJECT_BAL                     0x185
# define OBJECT_WARP_UZU                0x186
# define OBJECT_DRIFTICE                0x187
# define OBJECT_FALL                    0x188
# define OBJECT_HANAREYAMA_OBJ          0x189
# define OBJECT_CRACE_OBJECT            0x18a
# define OBJECT_DNQ                     0x18b
# define OBJECT_OBJ_TOKEIDAI            0x18c
# define OBJECT_EG                      0x18d
# define OBJECT_TRU                     0x18e
# define OBJECT_TRT                     0x18f
# define OBJECT_HAKUGIN_OBJ             0x190
# define OBJECT_HORSE_GAME_CHECK        0x191
# define OBJECT_STK                     0x192
# define OBJECT_UNSET_193               0x193
# define OBJECT_UNSET_194               0x194
# define OBJECT_MNK                     0x195
# define OBJECT_GI_BOTTLE_RED           0x196
# define OBJECT_TOKEI_TOBIRA            0x197
# define OBJECT_AZ                      0x198
# define OBJECT_TWIG                    0x199
# define OBJECT_DEKUCITY_OBJ            0x19a
# define OBJECT_PO_FUSEN                0x19b
# define OBJECT_RACETSUBO               0x19c
# define OBJECT_HA                      0x19d
# define OBJECT_BIGOKUTA                0x19e
# define OBJECT_OPEN_OBJ                0x19f
# define OBJECT_FU_KAITEN               0x1a0
# define OBJECT_FU_MATO                 0x1a1
# define OBJECT_MTORIDE                 0x1a2
# define OBJECT_OSN                     0x1a3
# define OBJECT_TOKEI_STEP              0x1a4
# define OBJECT_LOTUS                   0x1a5
# define OBJECT_TL                      0x1a6
# define OBJECT_DKJAIL_OBJ              0x1a7
# define OBJECT_VISIBLOCK               0x1a8
# define OBJECT_TSN                     0x1a9
# define OBJECT_DS2N                    0x1aa
# define OBJECT_FSN                     0x1ab
# define OBJECT_SHN                     0x1ac
# define OBJECT_BIGICICLE               0x1ad
# define OBJECT_GI_BOTTLE_15            0x1ae
# define OBJECT_TK                      0x1af
# define OBJECT_MARKET_OBJ              0x1b0
# define OBJECT_GI_RESERVE00            0x1b1
# define OBJECT_GI_RESERVE01            0x1b2
# define OBJECT_LIGHTBLOCK              0x1b3
# define OBJECT_TAKARAYA_OBJECTS        0x1b4
# define OBJECT_WDHAND                  0x1b5
# define OBJECT_SDN                     0x1b6
# define OBJECT_SNOWWD                  0x1b7
# define OBJECT_GIANT                   0x1b8
# define OBJECT_COMB                    0x1b9
# define OBJECT_HANA                    0x1ba
# define OBJECT_BOSS_HAKUGIN            0x1bb
# define OBJECT_MEGANEANA_OBJ           0x1bc
# define OBJECT_GI_NUTSMASK             0x1bd
# define OBJECT_STK2                    0x1be
# define OBJECT_SPOT11_OBJ              0x1bf
# define OBJECT_DANPEI_OBJECT           0x1c0
# define OBJECT_DHOUSE                  0x1c1
# define OBJECT_HAKAISI                 0x1c2
# define OBJECT_PO                      0x1c3
# define OBJECT_SNOWMAN                 0x1c4
# define OBJECT_PO_SISTERS              0x1c5
# define OBJECT_PP                      0x1c6
# define OBJECT_GORONSWITCH             0x1c7
# define OBJECT_DELF                    0x1c8
# define OBJECT_BOTIHASIRA              0x1c9
# define OBJECT_GI_BIGBOMB              0x1ca
# define OBJECT_PST                     0x1cb
# define OBJECT_BSMASK                  0x1cc
# define OBJECT_SPIDERTENT              0x1cd
# define OBJECT_ZORAEGG                 0x1ce
# define OBJECT_KBT                     0x1cf
# define OBJECT_GG                      0x1d0
# define OBJECT_MARUTA                  0x1d1
# define OBJECT_GHAKA                   0x1d2
# define OBJECT_OYU                     0x1d3
# define OBJECT_DNP                     0x1d4
# define OBJECT_DAI                     0x1d5
# define OBJECT_KGY                     0x1d6
# define OBJECT_FB                      0x1d7
# define OBJECT_TAISOU                  0x1d8
# define OBJECT_MASK_BU_SAN             0x1d9
# define OBJECT_MASK_KI_TAN             0x1da
# define OBJECT_MASK_RABIT              0x1db
# define OBJECT_MASK_SKJ                0x1dc
# define OBJECT_MASK_BAKURETU           0x1dd
# define OBJECT_MASK_TRUTH              0x1de
# define OBJECT_GK                      0x1df
# define OBJECT_HAKA_OBJ                0x1e0
# define OBJECT_MASK_GORON              0x1e1
# define OBJECT_MASK_ZORA               0x1e2
# define OBJECT_MASK_NUTS               0x1e3
# define OBJECT_MASK_BOY                0x1e4
# define OBJECT_DNT                     0x1e5
# define OBJECT_YUKIYAMA                0x1e6
# define OBJECT_ICEFLOE                 0x1e7
# define OBJECT_GI_GOLD_DUST            0x1e8
# define OBJECT_GI_BOTTLE_16            0x1e9
# define OBJECT_GI_BOTTLE_22            0x1ea
# define OBJECT_BEE                     0x1eb
# define OBJECT_OT                      0x1ec
# define OBJECT_UTUBO                   0x1ed
# define OBJECT_DORA                    0x1ee
# define OBJECT_GI_LOACH                0x1ef
# define OBJECT_GI_SEAHORSE             0x1f0
# define OBJECT_BIGPO                   0x1f1
# define OBJECT_HARIKO                  0x1f2
# define OBJECT_DNO                     0x1f3
# define OBJECT_SINKAI_KABE             0x1f4
# define OBJECT_KIN2_OBJ                0x1f5
# define OBJECT_ISHI                    0x1f6
# define OBJECT_HAKUGIN_DEMO            0x1f7
# define OBJECT_JG                      0x1f8
# define OBJECT_GI_SWORD_2              0x1f9
# define OBJECT_GI_SWORD_3              0x1fa
# define OBJECT_GI_SWORD_4              0x1fb
# define OBJECT_UM                      0x1fc
# define OBJECT_MASK_GIBUDO             0x1fd
# define OBJECT_MASK_JSON               0x1fe
# define OBJECT_MASK_KERFAY             0x1ff
# define OBJECT_MASK_BIGELF             0x200
# define OBJECT_RB                      0x201
# define OBJECT_MBAR_OBJ                0x202
# define OBJECT_IKANA_OBJ               0x203
# define OBJECT_KZ                      0x204
# define OBJECT_TOKEI_TURRET            0x205
# define OBJECT_ZOG                     0x206
# define OBJECT_ROTLIFT                 0x207
# define OBJECT_POSTHOUSE_OBJ           0x208
# define OBJECT_GI_MASK09               0x209
# define OBJECT_GI_MASK14               0x20a
# define OBJECT_GI_MASK15               0x20b
# define OBJECT_INIBS_OBJECT            0x20c
# define OBJECT_TREE                    0x20d
# define OBJECT_KAIZOKU_OBJ             0x20e
# define OBJECT_GI_RESERVE_B_00         0x20f
# define OBJECT_GI_RESERVE_C_00         0x210
# define OBJECT_ZOB                     0x211
# define OBJECT_MILKBAR                 0x212
# define OBJECT_DMASK                   0x213
# define OBJECT_MASK_KYOJIN             0x214
# define OBJECT_GI_RESERVE_C_01         0x215
# define OBJECT_ZOD                     0x216
# define OBJECT_KUMO30                  0x217
# define OBJECT_OBJ_YASI                0x218
# define OBJECT_MASK_ROMERNY            0x219
# define OBJECT_TANRON1                 0x21a
# define OBJECT_TANRON2                 0x21b
# define OBJECT_TANRON3                 0x21c
# define OBJECT_GI_MAGICMUSHROOM        0x21d
# define OBJECT_OBJ_CHAN                0x21e
# define OBJECT_GI_MASK10               0x21f
# define OBJECT_ZOS                     0x220
# define OBJECT_MASK_POSTHAT            0x221
# define OBJECT_F40_SWITCH              0x222
# define OBJECT_LODMOON                 0x223
# define OBJECT_TRO                     0x224
# define OBJECT_GI_MASK12               0x225
# define OBJECT_GI_MASK23               0x226
# define OBJECT_GI_BOTTLE_21            0x227
# define OBJECT_GI_CAMERA               0x228
# define OBJECT_KAMEJIMA                0x229
# define OBJECT_HARFGIBUD               0x22a
# define OBJECT_ZOV                     0x22b
# define OBJECT_HGDOOR                  0x22c
# define OBJECT_UNSET_22D               0x22d
# define OBJECT_UNSET_22E               0x22e
# define OBJECT_UNSET_22F               0x22f
# define OBJECT_DOR01                   0x230
# define OBJECT_DOR02                   0x231
# define OBJECT_DOR03                   0x232
# define OBJECT_DOR04                   0x233
# define OBJECT_LAST_OBJ                0x234
# define OBJECT_REDEAD_OBJ              0x235
# define OBJECT_IKNINSIDE_OBJ           0x236
# define OBJECT_IKNV_OBJ                0x237
# define OBJECT_PAMERA                  0x238
# define OBJECT_HSSTUMP                 0x239
# define OBJECT_ZM                      0x23a
# define OBJECT_BIG_FWALL               0x23b
# define OBJECT_SECOM_OBJ               0x23c
# define OBJECT_HUNSUI                  0x23d
# define OBJECT_UCH                     0x23e
# define OBJECT_TANRON4                 0x23f
# define OBJECT_TANRON5                 0x240
# define OBJECT_DT                      0x241
# define OBJECT_GI_MASK03               0x242
# define OBJECT_CHA                     0x243
# define OBJECT_OBJ_DINNER              0x244
# define OBJECT_GI_RESERVE_B_01         0x245
# define OBJECT_LASTDAY                 0x246
# define OBJECT_BAI                     0x247
# define OBJECT_IN2                     0x248
# define OBJECT_IKN_DEMO                0x249
# define OBJECT_YB                      0x24a
# define OBJECT_RZ                      0x24b
# define OBJECT_MASK_ZACHO              0x24c
# define OBJECT_GI_FIELDMAP             0x24d
# define OBJECT_MASK_STONE              0x24e
# define OBJECT_BJT                     0x24f
# define OBJECT_TARU                    0x250
# define OBJECT_MOONSTON                0x251
# define OBJECT_MASK_BREE               0x252
# define OBJECT_GI_SCHEDULE             0x253
# define OBJECT_GI_STONEMASK            0x254
# define OBJECT_ZORABAND                0x255
# define OBJECT_KEPN_KOYA               0x256
# define OBJECT_OBJ_USIYANE             0x257
# define OBJECT_GI_MASK05               0x258
# define OBJECT_GI_MASK11               0x259
# define OBJECT_GI_MASK20               0x25a
# define OBJECT_NNH                     0x25b
# define OBJECT_MASK_GERO               0x25c
# define OBJECT_MASK_YOFUKASI           0x25d
# define OBJECT_MASK_MEOTO              0x25e
# define OBJECT_MASK_DANCER             0x25f
# define OBJECT_KZSAKU                  0x260
# define OBJECT_OBJ_MILK_BIN            0x261
# define OBJECT_RANDOM_OBJ              0x262
# define OBJECT_KUJIYA                  0x263
# define OBJECT_KITAN                   0x264
# define OBJECT_GI_MASK06               0x265
# define OBJECT_GI_MASK16               0x266
# define OBJECT_ASTR_OBJ                0x267
# define OBJECT_BSB                     0x268
# define OBJECT_FALL2                   0x269
# define OBJECT_STH                     0x26a
# define OBJECT_GI_MSSA                 0x26b
# define OBJECT_SMTOWER                 0x26c
# define OBJECT_GI_MASK21               0x26d
# define OBJECT_YADO_OBJ                0x26e
# define OBJECT_SYOTEN                  0x26f
# define OBJECT_MOONEND                 0x270
# define OBJECT_OB                      0x271
# define OBJECT_GI_BOTTLE_04            0x272
# define OBJECT_OBJ_DANPEILIFT          0x273
# define OBJECT_WDOR01                  0x274
# define OBJECT_WDOR02                  0x275
# define OBJECT_WDOR03                  0x276
# define OBJECT_STK3                    0x277
# define OBJECT_KINSTA1_OBJ             0x278
# define OBJECT_KINSTA2_OBJ             0x279
# define OBJECT_BH                      0x27a
# define OBJECT_WDOR04                  0x27b
# define OBJECT_WDOR05                  0x27c
# define OBJECT_GI_MASK17               0x27d
# define OBJECT_GI_MASK22               0x27e
# define OBJECT_LBFSHOT                 0x27f
# define OBJECT_FUSEN                   0x280
# define OBJECT_ENDING_OBJ              0x281
# define OBJECT_GI_MASK13               0x282
# define OBJECT_ID_MAX                  0x283
#endif

#endif
