#ifndef COMBO_SFX_ID_H
#define COMBO_SFX_ID_H

#if defined(GAME_OOT)
# define NA_SE_PL_WALK_GROUND                   0x800
# define NA_SE_PL_WALK_SAND                     0x801
# define NA_SE_PL_WALK_CONCRETE                 0x802
# define NA_SE_PL_WALK_DIRT                     0x803
# define NA_SE_PL_WALK_WATER0                   0x804
# define NA_SE_PL_WALK_WATER1                   0x805
# define NA_SE_PL_WALK_WATER2                   0x806
# define NA_SE_PL_WALK_MAGMA                    0x807
# define NA_SE_PL_WALK_GRASS                    0x808
# define NA_SE_PL_WALK_IRON                     0x809
# define NA_SE_PL_WALK_LADDER                   0x80a
# define NA_SE_PL_WALK_GLASS                    0x80b
# define NA_SE_PL_WALK_WALL                     0x80c
# define NA_SE_PL_WALK_HEAVYBOOTS               0x80d
# define NA_SE_PL_DUMMY_14                      0x80e
# define NA_SE_PL_WALK_ICE                      0x80f
# define NA_SE_PL_JUMP                          0x810
# define NA_SE_PL_JUMP_SAND                     0x811
# define NA_SE_PL_JUMP_CONCRETE                 0x812
# define NA_SE_PL_JUMP_DIRT                     0x813
# define NA_SE_PL_JUMP_WATER0                   0x814
# define NA_SE_PL_JUMP_WATER1                   0x815
# define NA_SE_PL_JUMP_WATER2                   0x816
# define NA_SE_PL_JUMP_MAGMA                    0x817
# define NA_SE_PL_JUMP_GRASS                    0x818
# define NA_SE_PL_JUMP_IRON                     0x819
# define NA_SE_PL_JUMP_LADDER                   0x81a
# define NA_SE_PL_JUMP_GLASS                    0x81b
# define NA_SE_PL_DUMMY28                       0x81c
# define NA_SE_PL_JUMP_HEAVYBOOTS               0x81d
# define NA_SE_PL_DUMMY30                       0x81e
# define NA_SE_PL_JUMP_ICE                      0x81f
# define NA_SE_PL_LAND                          0x820
# define NA_SE_PL_LAND_SAND                     0x821
# define NA_SE_PL_LAND_CONCRETE                 0x822
# define NA_SE_PL_LAND_DIRT                     0x823
# define NA_SE_PL_LAND_WATER0                   0x824
# define NA_SE_PL_LAND_WATER1                   0x825
# define NA_SE_PL_LAND_WATER2                   0x826
# define NA_SE_PL_LAND_MAGMA                    0x827
# define NA_SE_PL_LAND_GRASS                    0x828
# define NA_SE_PL_LAND_IRON                     0x829
# define NA_SE_PL_LAND_LADDER                   0x82a
# define NA_SE_PL_LAND_GLASS                    0x82b
# define NA_SE_PL_DUMMY_44                      0x82c
# define NA_SE_PL_LAND_HEAVYBOOTS               0x82d
# define NA_SE_PL_DUMMY_46                      0x82e
# define NA_SE_PL_LAND_ICE                      0x82f
# define NA_SE_PL_SLIPDOWN                      0x830
# define NA_SE_PL_CLIMB_CLIFF                   0x831
# define NA_SE_PL_SIT_ON_HORSE                  0x832
# define NA_SE_PL_GET_OFF_HORSE                 0x833
# define NA_SE_PL_TAKE_OUT_SHIELD               0x834
# define NA_SE_PL_CHANGE_ARMS                   0x835
# define NA_SE_PL_CATCH_BOOMERANG               0x836
# define NA_SE_PL_DUMMY_55                      0x837
# define NA_SE_PL_DUMMY_56                      0x838
# define NA_SE_PL_SWIM                          0x839
# define NA_SE_PL_THROW                         0x83a
# define NA_SE_PL_BODY_BOUND                    0x83b
# define NA_SE_PL_ROLL                          0x83c
# define NA_SE_PL_SKIP                          0x83d
# define NA_SE_PL_BODY_HIT                      0x83e
# define NA_SE_PL_DAMAGE                        0x83f
# define NA_SE_PL_SLIP                          0x840
# define NA_SE_PL_SLIP_SAND                     0x841
# define NA_SE_PL_SLIP_CONCRETE                 0x842
# define NA_SE_PL_SLIP_DIRT                     0x843
# define NA_SE_PL_SLIP_WATER0                   0x844
# define NA_SE_PL_SLIP_WATER1                   0x845
# define NA_SE_PL_SLIP_WATER2                   0x846
# define NA_SE_PL_SLIP_MAGMA                    0x847
# define NA_SE_PL_SLIP_GRASS                    0x848
# define NA_SE_PL_SLIP_IRON                     0x849
# define NA_SE_PL_SLIP_LADDER                   0x84a
# define NA_SE_PL_SLIP_GLASS                    0x84b
# define NA_SE_PL_DUMMY76                       0x84c
# define NA_SE_PL_SLIP_HEAVYBOOTS               0x84d
# define NA_SE_PL_DUMMY78                       0x84e
# define NA_SE_PL_SLIP_ICE                      0x84f
# define NA_SE_PL_BOUND                         0x850
# define NA_SE_PL_BOUND_SAND                    0x851
# define NA_SE_PL_BOUND_CONCRETE                0x852
# define NA_SE_PL_BOUND_DIRT                    0x853
# define NA_SE_PL_BOUND_WATER0                  0x854
# define NA_SE_PL_BOUND_WATER1                  0x855
# define NA_SE_PL_BOUND_WATER2                  0x856
# define NA_SE_PL_BOUND_MAGMA                   0x857
# define NA_SE_PL_BOUND_GRASS                   0x858
# define NA_SE_PL_BOUND_IRON                    0x859
# define NA_SE_PL_BOUND_LADDER                  0x85a
# define NA_SE_PL_BOUND_WOOD                    0x85b
# define NA_SE_PL_DUMMY_92                      0x85c
# define NA_SE_PL_BOUND_HEAVYBOOTS              0x85d
# define NA_SE_PL_DUMMY_94                      0x85e
# define NA_SE_PL_BOUND_ICE                     0x85f
# define NA_SE_PL_DUMMY_96                      0x860
# define NA_SE_PL_DUMMY_97                      0x861
# define NA_SE_PL_DUMMY_98                      0x862
# define NA_SE_PL_FACE_UP                       0x863
# define NA_SE_PL_DIVE_BUBBLE                   0x864
# define NA_SE_PL_MOVE_BUBBLE                   0x865
# define NA_SE_PL_METALEFFECT_KID               0x866
# define NA_SE_PL_METALEFFECT_ADULT             0x867
# define NA_SE_PL_SPARK                         0x868
# define NA_SE_PL_PULL_UP_PLANT                 0x869
# define NA_SE_PL_PULL_UP_ROCK                  0x86a
# define NA_SE_PL_IN_BUBBLE                     0x86b
# define NA_SE_PL_PULL_UP_BIGROCK               0x86c
# define NA_SE_PL_SWORD_CHARGE                  0x86d
# define NA_SE_PL_FREEZE                        0x86e
# define NA_SE_PL_PULL_UP_POT                   0x86f
# define NA_SE_PL_KNOCK                         0x870
# define NA_SE_PL_CALM_HIT                      0x871
# define NA_SE_PL_CALM_PAT                      0x872
# define NA_SE_PL_SUBMERGE                      0x873
# define NA_SE_PL_FREEZE_S                      0x874
# define NA_SE_PL_ICE_BROKEN                    0x875
# define NA_SE_PL_SLIP_ICE_LELEL                0x876
# define NA_SE_PL_PUT_OUT_ITEM                  0x877
# define NA_SE_PL_PULL_UP_WOODBOX               0x878
# define NA_SE_PL_MAGIC_FIRE                    0x879
# define NA_SE_PL_MAGIC_WIND_NORMAL             0x87a
# define NA_SE_PL_MAGIC_WIND_WARP               0x87b
# define NA_SE_PL_MAGIC_SOUL_NORMAL             0x87c
# define NA_SE_PL_ARROW_CHARGE_FIRE             0x87d
# define NA_SE_PL_ARROW_CHARGE_ICE              0x87e
# define NA_SE_PL_ARROW_CHARGE_LIGHT            0x87f
# define NA_SE_PL_DUMMY_128                     0x880
# define NA_SE_PL_DUMMY_129                     0x881
# define NA_SE_PL_DUMMY_130                     0x882
# define NA_SE_PL_PULL_UP_RUTO                  0x883
# define NA_SE_PL_DUMMY_132                     0x884
# define NA_SE_PL_DUMMY_133                     0x885
# define NA_SE_PL_DUMMY_134                     0x886
# define NA_SE_PL_DUMMY_135                     0x887
# define NA_SE_PL_DUMMY_136                     0x888
# define NA_SE_PL_DUMMY_137                     0x889
# define NA_SE_PL_DUMMY_138                     0x88a
# define NA_SE_PL_DUMMY_139                     0x88b
# define NA_SE_PL_DUMMY_140                     0x88c
# define NA_SE_PL_DUMMY_141                     0x88d
# define NA_SE_PL_DUMMY_142                     0x88e
# define NA_SE_PL_DUMMY_143                     0x88f
# define NA_SE_PL_DUMMY_144                     0x890
# define NA_SE_PL_DUMMY_145                     0x891
# define NA_SE_PL_DUMMY_146                     0x892
# define NA_SE_PL_DUMMY_147                     0x893
# define NA_SE_PL_DUMMY_148                     0x894
# define NA_SE_PL_DUMMY_149                     0x895
# define NA_SE_PL_DUMMY_150                     0x896
# define NA_SE_PL_DUMMY_151                     0x897
# define NA_SE_PL_DUMMY_152                     0x898
# define NA_SE_PL_DUMMY_153                     0x899
# define NA_SE_PL_DUMMY_154                     0x89a
# define NA_SE_PL_DUMMY_155                     0x89b
# define NA_SE_PL_DUMMY_156                     0x89c
# define NA_SE_PL_DUMMY_157                     0x89d
# define NA_SE_PL_DUMMY_158                     0x89e
# define NA_SE_PL_DUMMY_159                     0x89f
# define NA_SE_PL_DUMMY_160                     0x8a0
# define NA_SE_PL_DUMMY_161                     0x8a1
# define NA_SE_PL_DUMMY_162                     0x8a2
# define NA_SE_PL_DUMMY_163                     0x8a3
# define NA_SE_PL_DUMMY_164                     0x8a4
# define NA_SE_PL_DUMMY_165                     0x8a5
# define NA_SE_PL_DUMMY_166                     0x8a6
# define NA_SE_PL_DUMMY_167                     0x8a7
# define NA_SE_PL_DUMMY_168                     0x8a8
# define NA_SE_PL_DUMMY_169                     0x8a9
# define NA_SE_PL_DUMMY_170                     0x8aa
# define NA_SE_PL_DUMMY_171                     0x8ab
# define NA_SE_PL_DUMMY_172                     0x8ac
# define NA_SE_PL_DUMMY_173                     0x8ad
# define NA_SE_PL_DUMMY_174                     0x8ae
# define NA_SE_PL_DUMMY_175                     0x8af
# define NA_SE_PL_CRAWL                         0x8b0
# define NA_SE_PL_CRAWL_SAND                    0x8b1
# define NA_SE_PL_CRAWL_CONCRETE                0x8b2
# define NA_SE_PL_CRAWL_DIRT                    0x8b3
# define NA_SE_PL_CRAWL_WATER0                  0x8b4
# define NA_SE_PL_DUMMY_181                     0x8b5
# define NA_SE_PL_DUMMY_182                     0x8b6
# define NA_SE_PL_DUMMY_183                     0x8b7
# define NA_SE_PL_DUMMY_184                     0x8b8
# define NA_SE_PL_DUMMY_185                     0x8b9
# define NA_SE_PL_DUMMY_186                     0x8ba
# define NA_SE_PL_CRAWL_WOOD                    0x8bb
# define NA_SE_PL_CRAWL_ICE                     0x8bc
# define NA_SE_PL_DUMMY_189                     0x8bd
# define NA_SE_PL_DUMMY_190                     0x8be
# define NA_SE_PL_DUMMY_191                     0x8bf
# define NA_SE_PL_MAGIC_SOUL_FLASH              0x8c0
# define NA_SE_PL_ROLL_DUST                     0x8c1
# define NA_SE_PL_DUMMY_192                     0x8c2
# define NA_SE_PL_MAGIC_SOUL_BALL               0x8c3
# define NA_SE_PL_SPIRAL_HEAL_BEAM              0x8c4
# define NA_SE_PL_BOUND_NOWEAPON                0x8c5
# define NA_SE_PL_PLANT_GROW_UP                 0x8c6
# define NA_SE_PL_PLANT_TALLER                  0x8c7
# define NA_SE_PL_MAGIC_WIND_VANISH             0x8c8
# define NA_SE_PL_HOBBERBOOTS_LV                0x8c9
# define NA_SE_PL_PLANT_MOVE                    0x8ca
# define NA_SE_EV_WALL_MOVE_SP                  0x8cb
# define NA_SE_PL_DUMMY_204                     0x8cc
# define NA_SE_PL_DUMMY_205                     0x8cd
# define NA_SE_PL_DUMMY_206                     0x8ce
# define NA_SE_PL_DUMMY_207                     0x8cf
# define NA_SE_PL_SLIP_LEVEL                    0x8d0
# define NA_SE_PL_SLIP_SAND_LEVEL               0x8d1
# define NA_SE_PL_SLIP_CONCRETE_LEVEL           0x8d2
# define NA_SE_PL_SLIP_DIRT_LEVEL               0x8d3
# define NA_SE_PL_SLIP_WATER0_LEVEL             0x8d4
# define NA_SE_PL_SLIP_WATER1_LEVEL             0x8d5
# define NA_SE_PL_SLIP_WATER2_LEVEL             0x8d6
# define NA_SE_PL_SLIP_MAGMA_LEVEL              0x8d7
# define NA_SE_PL_SLIP_GRASS_LEVEL              0x8d8
# define NA_SE_PL_SLIP_IRON_LEVEL               0x8d9
# define NA_SE_PL_SLIP_GLASS_LEVEL              0x8da
# define NA_SE_PL_SLIP_WOOD_LEVEL               0x8db
# define NA_SE_PL_DUMMY_220                     0x8dc
# define NA_SE_PL_DUMMY_221                     0x8dd
# define NA_SE_PL_SLIP_HEAVYBOOTS_LEVEL         0x8de
# define NA_SE_PL_SLIP_ICE_LEVEL                0x8df

# define NA_SE_EV_DOOR_OPEN                      0x2800
# define NA_SE_EV_DOOR_CLOSE                     0x2801
# define NA_SE_EV_EXPLOSION                      0x2802
# define NA_SE_EV_HORSE_WALK                     0x2803
# define NA_SE_EV_HORSE_RUN                      0x2804
# define NA_SE_EV_HORSE_NEIGH                    0x2805
# define NA_SE_EV_RIVER_STREAM                   0x2806
# define NA_SE_EV_WATER_WALL_BIG                 0x2807
# define NA_SE_EV_OUT_OF_WATER                   0x2808
# define NA_SE_EV_DIVE_WATER                     0x2809
# define NA_SE_EV_ROCK_SLIDE                     0x280a
# define NA_SE_EV_MAGMA_LEVEL                    0x280b
# define NA_SE_EV_BRIDGE_OPEN                    0x280c
# define NA_SE_EV_BRIDGE_CLOSE                   0x280d
# define NA_SE_EV_BRIDGE_OPEN_STOP               0x280e
# define NA_SE_EV_BRIDGE_CLOSE_STOP              0x280f
# define NA_SE_EV_WALL_BROKEN                    0x2810
# define NA_SE_EV_CHICKEN_CRY_N                  0x2811
# define NA_SE_EV_CHICKEN_CRY_A                  0x2812
# define NA_SE_EV_CHICKEN_CRY_M                  0x2813
# define NA_SE_EV_SLIDE_DOOR_OPEN                0x2814
# define NA_SE_EV_FOOT_SWITCH                    0x2815
# define NA_SE_EV_HORSE_GROAN                    0x2816
# define NA_SE_EV_BOMB_DROP_WATER                0x2817
# define NA_SE_EV_HORSE_JUMP                     0x2818
# define NA_SE_EV_HORSE_LAND                     0x2819
# define NA_SE_EV_HORSE_SLIP                     0x281a
# define NA_SE_EV_FAIRY_DASH                     0x281b
# define NA_SE_EV_SLIDE_DOOR_CLOSE               0x281c
# define NA_SE_EV_STONE_BOUND                    0x281d
# define NA_SE_EV_STONE_STATUE_OPEN              0x281e
# define NA_SE_EV_TBOX_UNLOCK                    0x281f
# define NA_SE_EV_TBOX_OPEN                      0x2820
# define NA_SE_SY_TIMER                          0x2821
# define NA_SE_EV_FLAME_IGNITION                 0x2822
# define NA_SE_EV_SPEAR_HIT                      0x2823
# define NA_SE_EV_ELEVATOR_MOVE                  0x2824
# define NA_SE_EV_WARP_HOLE                      0x2825
# define NA_SE_EV_LINK_WARP                      0x2826
# define NA_SE_EV_PILLAR_SINK                    0x2827
# define NA_SE_EV_WATER_WALL                     0x2828
# define NA_SE_EV_RIVER_STREAM_S                 0x2829
# define NA_SE_EV_RIVER_STREAM_F                 0x282a
# define NA_SE_EV_HORSE_LAND2                    0x282b
# define NA_SE_EV_HORSE_SANDDUST                 0x282c
# define NA_SE_EV_DUMMY45                        0x282d
# define NA_SE_EV_LIGHTNING                      0x282e
# define NA_SE_EV_BOMB_BOUND                     0x282f
# define NA_SE_EV_WATERDROP                      0x2830
# define NA_SE_EV_TORCH                          0x2831
# define NA_SE_EV_MAGMA_LEVEL_M                  0x2832
# define NA_SE_EV_FIRE_PILLAR                    0x2833
# define NA_SE_EV_FIRE_PLATE                     0x2834
# define NA_SE_EV_BLOCK_BOUND                    0x2835
# define NA_SE_EV_METALDOOR_SLIDE                0x2836
# define NA_SE_EV_METALDOOR_STOP                 0x2837
# define NA_SE_EV_BLOCK_SHAKE                    0x2838
# define NA_SE_EV_BOX_BREAK                      0x2839
# define NA_SE_EV_HAMMER_SWITCH                  0x283a
# define NA_SE_EV_MAGMA_LEVEL_L                  0x283b
# define NA_SE_EV_SPEAR_FENCE                    0x283c
# define NA_SE_EV_GANON_HORSE_NEIGH              0x283d
# define NA_SE_EV_GANON_HORSE_GROAN              0x283e
# define NA_SE_EV_FANTOM_WARP_S                  0x283f
# define NA_SE_EV_FANTOM_WARP_L                  0x2840
# define NA_SE_EV_FOUNTAIN                       0x2841
# define NA_SE_EV_KID_HORSE_WALK                 0x2842
# define NA_SE_EV_KID_HORSE_RUN                  0x2843
# define NA_SE_EV_KID_HORSE_NEIGH                0x2844
# define NA_SE_EV_KID_HORSE_GROAN                0x2845
# define NA_SE_EV_WHITE_OUT                      0x2846
# define NA_SE_EV_LIGHT_GATHER                   0x2847
# define NA_SE_EV_TREE_CUT                       0x2848
# define NA_SE_EV_VOLCANO                        0x2849
# define NA_SE_EV_GUILLOTINE_UP                  0x284a
# define NA_SE_EV_GUILLOTINE_BOUND               0x284b
# define NA_SE_EV_ROLLCUTTER_MOTOR               0x284c
# define NA_SE_EV_CHINETRAP_DOWN                 0x284d
# define NA_SE_EV_PLANT_BROKEN                   0x284e
# define NA_SE_EV_SHIP_BELL                      0x284f
# define NA_SE_EV_FLUTTER_FLAG                   0x2850
# define NA_SE_EV_TRAP_BOUND                     0x2851
# define NA_SE_EV_ROCK_BROKEN                    0x2852
# define NA_SE_EV_FANTOM_WARP_S2                 0x2853
# define NA_SE_EV_FANTOM_WARP_L2                 0x2854
# define NA_SE_EV_COFFIN_CAP_OPEN                0x2855
# define NA_SE_EV_COFFIN_CAP_BOUND               0x2856
# define NA_SE_EV_WIND_TRAP                      0x2857
# define NA_SE_EV_TRAP_OBJ_SLIDE                 0x2858
# define NA_SE_EV_METALDOOR_OPEN                 0x2859
# define NA_SE_EV_METALDOOR_CLOSE                0x285a
# define NA_SE_EV_BURN_OUT                       0x285b
# define NA_SE_EV_BLOCKSINK                      0x285c
# define NA_SE_EV_CROWD                          0x285d
# define NA_SE_EV_WATER_LEVEL_DOWN               0x285e
# define NA_SE_EV_NAVY_VANISH                    0x285f
# define NA_SE_EV_LADDER_DOUND                   0x2860
# define NA_SE_EV_WEB_VIBRATION                  0x2861
# define NA_SE_EV_WEB_BROKEN                     0x2862
# define NA_SE_EV_ROLL_STAND                     0x2863
# define NA_SE_EV_BUYODOOR_OPEN                  0x2864
# define NA_SE_EV_BUYODOOR_CLOSE                 0x2865
# define NA_SE_EV_WOODDOOR_OPEN                  0x2866
# define NA_SE_EV_METALGATE_OPEN                 0x2867
# define NA_SE_IT_SCOOP_UP_WATER                 0x2868
# define NA_SE_EV_FISH_LEAP                      0x2869
# define NA_SE_EV_KAKASHI_SWING                  0x286a
# define NA_SE_EV_KAKASHI_ROLL                   0x286b
# define NA_SE_EV_BOTTLE_CAP_OPEN                0x286c
# define NA_SE_EV_JABJAB_BREATHE                 0x286d
# define NA_SE_EV_SPIRIT_STONE                   0x286e
# define NA_SE_EV_TRIFORCE_FLASH                 0x286f
# define NA_SE_EV_FALL_DOWN_DIRT                 0x2870
# define NA_SE_EV_NAVY_FLY                       0x2871
# define NA_SE_EV_NAVY_CRASH                     0x2872
# define NA_SE_EV_WOOD_HIT                       0x2873
# define NA_SE_EV_SCOOPUP_WATER                  0x2874
# define NA_SE_EV_DROP_FALL                      0x2875
# define NA_SE_EV_WOOD_GEAR                      0x2876
# define NA_SE_EV_TREE_SWING                     0x2877
# define NA_SE_EV_HORSE_RUN_LEVEL                0x2878
# define NA_SE_EV_ELEVATOR_MOVE2                 0x2879
# define NA_SE_EV_ELEVATOR_STOP                  0x287a
# define NA_SE_EV_TRE_BOX_APPEAR                 0x287b
# define NA_SE_EV_CHAIN_KEY_UNLOCK               0x287c
# define NA_SE_EV_SPINE_TRAP_MOVE                0x287d
# define NA_SE_EV_HEALING                        0x287e
# define NA_SE_EV_GREAT_FAIRY_APPEAR             0x287f
# define NA_SE_EV_GREAT_FAIRY_VANISH             0x2880
# define NA_SE_EV_RED_EYE                        0x2881
# define NA_SE_EV_ROLL_STAND_2                   0x2882
# define NA_SE_EV_WALL_SLIDE                     0x2883
# define NA_SE_EV_TRE_BOX_FLASH                  0x2884
# define NA_SE_EV_WINDMILL_LEVEL                 0x2885
# define NA_SE_EV_GOTO_HEAVEN                    0x2886
# define NA_SE_EV_POT_BROKEN                     0x2887
# define NA_SE_PL_PUT_DOWN_POT                   0x2888
# define NA_SE_EV_DIVE_INTO_WATER                0x2889
# define NA_SE_EV_JUMP_OUT_WATER                 0x288a
# define NA_SE_EV_GOD_FLYING                     0x288b
# define NA_SE_EV_TRIFORCE                       0x288c
# define NA_SE_EV_AURORA                         0x288d
# define NA_SE_EV_DEKU_DEATH                     0x288e
# define NA_SE_EV_BUYOSTAND_RISING               0x288f
# define NA_SE_EV_BUYOSTAND_FALL                 0x2890
# define NA_SE_EV_BUYOSHUTTER_OPEN               0x2891
# define NA_SE_EV_BUYOSHUTTER_CLOSE              0x2892
# define NA_SE_EV_STONEDOOR_STOP                 0x2893
# define NA_SE_EV_S_STONE_REVIVAL                0x2894
# define NA_SE_EV_MEDAL_APPEAR_S                 0x2895
# define NA_SE_EV_HUMAN_BOUND                    0x2896
# define NA_SE_EV_MEDAL_APPEAR_L                 0x2897
# define NA_SE_EV_EARTHQUAKE                     0x2898
# define NA_SE_EV_SHUT_BY_CRYSTAL                0x2899
# define NA_SE_EV_GOD_LIGHTBALL_2                0x289a
# define NA_SE_EV_RUN_AROUND                     0x289b
# define NA_SE_EV_CONSENTRATION                  0x289c
# define NA_SE_EV_TIMETRIP_LIGHT                 0x289d
# define NA_SE_EV_BUYOSTAND_STOP_A               0x289e
# define NA_SE_EV_BUYOSTAND_STOP_U               0x289f
# define NA_SE_EV_OBJECT_FALL                    0x28a0
# define NA_SE_EV_JUMP_CONC                      0x28a1
# define NA_SE_EV_ICE_MELT                       0x28a2
# define NA_SE_EV_FIRE_PILLAR_S                  0x28a3
# define NA_SE_EV_BLOCK_RISING                   0x28a4
# define NA_SE_EV_NABALL_VANISH                  0x28a5
# define NA_SE_EV_SARIA_MELODY                   0x28a6
# define NA_SE_EV_LINK_WARP_OUT                  0x28a7
# define NA_SE_EV_FIATY_HEAL                     0x28a8
# define NA_SE_EV_CHAIN_KEY_UNLOCK_B             0x28a9
# define NA_SE_EV_WOODBOX_BREAK                  0x28aa
# define NA_SE_EV_PUT_DOWN_WOODBOX               0x28ab
# define NA_SE_EV_LAND_DIRT                      0x28ac
# define NA_SE_EV_FLOOR_ROLLING                  0x28ad
# define NA_SE_EV_DOG_CRY_EVENING                0x28ae
# define NA_SE_EV_JABJAB_HICCUP                  0x28af
# define NA_SE_EV_NALE_MAGIC                     0x28b0
# define NA_SE_EV_FROG_JUMP                      0x28b1
# define NA_SE_EV_ICE_FREEZE                     0x28b2
# define NA_SE_EV_BURNING                        0x28b3
# define NA_SE_EV_WOODPLATE_BOUND                0x28b4
# define NA_SE_EV_GORON_WATER_DROP               0x28b5
# define NA_SE_EV_JABJAB_GROAN                   0x28b6
# define NA_SE_EV_DARUMA_VANISH                  0x28b7
# define NA_SE_EV_BIGBALL_ROLL                   0x28b8
# define NA_SE_EV_ELEVATOR_MOVE3                 0x28b9
# define NA_SE_EV_DIAMOND_SWITCH                 0x28ba
# define NA_SE_EV_FLAME_OF_FIRE                  0x28bb
# define NA_SE_EV_RAINBOW_SHOWER                 0x28bc
# define NA_SE_EV_FLYING_AIR                     0x28bd
# define NA_SE_EV_PASS_AIR                       0x28be
# define NA_SE_EV_COME_UP_DEKU_JR                0x28bf
# define NA_SE_EV_SAND_STORM                     0x28c0
# define NA_SE_EV_TRIFORCE_MARK                  0x28c1
# define NA_SE_EV_GRAVE_EXPLOSION                0x28c2
# define NA_SE_EV_LURE_MOVE_W                    0x28c3
# define NA_SE_EV_POT_MOVE_START                 0x28c4
# define NA_SE_EV_DIVE_INTO_WATER_L              0x28c5
# define NA_SE_EV_OUT_OF_WATER_L                 0x28c6
# define NA_SE_EV_GANON_MANTLE                   0x28c7
# define NA_SE_EV_DIG_UP                         0x28c8
# define NA_SE_EV_WOOD_BOUND                     0x28c9
# define NA_SE_EV_WATER_BUBBLE                   0x28ca
# define NA_SE_EV_ICE_BROKEN                     0x28cb
# define NA_SE_EV_FROG_GROW_UP                   0x28cc
# define NA_SE_EV_WATER_CONVECTION               0x28cd
# define NA_SE_EV_GROUND_GATE_OPEN               0x28ce
# define NA_SE_EV_FACE_BREAKDOWN                 0x28cf
# define NA_SE_EV_FACE_EXPLOSION                 0x28d0
# define NA_SE_EV_FACE_CRUMBLE_SLOW              0x28d1
# define NA_SE_EV_ROUND_TRAP_MOVE                0x28d2
# define NA_SE_EV_HIT_SOUND                      0x28d3
# define NA_SE_EV_ICE_SWING                      0x28d4
# define NA_SE_EV_DOWN_TO_GROUND                 0x28d5
# define NA_SE_EV_KENJA_ENVIROMENT_0             0x28d6
# define NA_SE_EV_KENJA_ENVIROMENT_1             0x28d7
# define NA_SE_EV_SMALL_DOG_BARK                 0x28d8
# define NA_SE_EV_ZELDA_POWER                    0x28d9
# define NA_SE_EV_RAIN                           0x28da
# define NA_SE_EV_IRON_DOOR_OPEN                 0x28db
# define NA_SE_EV_IRON_DOOR_CLOSE                0x28dc
# define NA_SE_EV_WHIRLPOOL                      0x28dd
# define NA_SE_EV_TOWER_PARTS_BROKEN             0x28de
# define NA_SE_EV_COW_CRY                        0x28df
# define NA_SE_EV_METAL_BOX_BOUND                0x28e0
# define NA_SE_EV_ELECTRIC_EXPLOSION             0x28e1
# define NA_SE_EV_HEAVY_THROW                    0x28e2
# define NA_SE_EV_FROG_CRY_0                     0x28e3
# define NA_SE_EV_FROG_CRY_1                     0x28e4
# define NA_SE_EV_COW_CRY_LV                     0x28e5
# define NA_SE_EV_RONRON_DOOR_CLOSE              0x28e6
# define NA_SE_EV_BUTTERFRY_TO_FAIRY             0x28e7
# define NA_SE_EV_FIVE_COUNT_LUPY                0x28e8
# define NA_SE_EV_STONE_GROW_UP                  0x28e9
# define NA_SE_EV_STONE_LAUNCH                   0x28ea
# define NA_SE_EV_STONE_ROLLING                  0x28eb
# define NA_SE_EV_TOGE_STICK_ROLLING             0x28ec
# define NA_SE_EV_TOWER_ENERGY                   0x28ed
# define NA_SE_EV_TOWER_BARRIER                  0x28ee
# define NA_SE_EV_CHIBI_WALK                     0x28ef
# define NA_SE_EV_KNIGHT_WALK                    0x28f0
# define NA_SE_EV_PILLAR_MOVE_STOP               0x28f1
# define NA_SE_EV_ERUPTION_CLOUD                 0x28f2
# define NA_SE_EV_LINK_WARP_OUT_LV               0x28f3
# define NA_SE_EV_LINK_WARP_IN                   0x28f4
# define NA_SE_EV_OCARINA_BMELO_0                0x28f5
# define NA_SE_EV_OCARINA_BMELO_1                0x28f6
# define NA_SE_EV_EXPLOSION_FOR_RENZOKU          0x28f7
#endif

#endif
