import { test, expect } from 'vitest';

import { makeTestSeed } from '../helper';

test("Can make a seed - MQ Extrasanity", async () => {
  const res = await makeTestSeed("MQ Extrasanity", {
    songs: 'anywhere',
    goldSkulltulaTokens: 'all',
    housesSkulltulaTokens: 'all',
    strayFairyChestShuffle: 'anywhere',
    strayFairyOtherShuffle: 'anywhere',
    townFairyShuffle: 'anywhere',
    bossKeyShuffleOot: 'anywhere',
    bossKeyShuffleMm: 'anywhere',
    smallKeyShuffleOot: 'anywhere',
    smallKeyShuffleMm: 'anywhere',
    smallKeyShuffleHideout: 'anywhere',
    cowShuffleOot: true,
    cowShuffleMm: true,
    shopShuffleOot: "full",
    shopShuffleMm: "full",
    eggShuffle: true,
    divingGameRupeeShuffle: true,
    pondFishShuffle: true,
    fairyFountainFairyShuffleOot: true,
    fairyFountainFairyShuffleMm: true,
    scrubShuffleOot: true,
    scrubShuffleMm: true,
    childWallets: true,
    colossalWallets: true,
    tingleShuffle: 'anywhere',
    owlShuffle: 'anywhere',
    shufflePotsOot: 'all',
    shufflePotsMm: 'all',
    shuffleGrassOot: 'all',
    shuffleGrassMm: 'all',
    shuffleTFGrassMm: true,
    shuffleBarrelsMm: 'all',
    shuffleCratesOot: 'all',
    shuffleCratesMm: 'all',
    shuffleFreeRupeesOot: 'all',
    shuffleFreeRupeesMm: 'all',
    shuffleFreeHeartsOot: 'all',
    shuffleFreeHeartsMm: true,
    shuffleHivesOot: true,
    shuffleHivesMm: true,
    shuffleButterfliesOot: true,
    shuffleButterfliesMm: true,
    shuffleWonderItemsOot: 'all',
    shuffleWonderItemsMm: true,
    fairySpotShuffleOot: true,
    dungeon: {
      DT: 'mq',
      DC: 'mq',
      JJ: 'mq',
      Forest: 'mq',
      Fire: 'mq',
      Water: 'mq',
      Spirit: 'mq',
      Shadow: 'mq',
      BotW: 'mq',
      IC: 'mq',
      GTG: 'mq',
      Ganon: 'mq',
    }
  });
  expect(res).toBeDefined();
});
