#ifndef COMBO_DOORS_H
#define COMBO_DOORS_H

enum
{
    DOORID_OOT_TREASURE_CHEST_GAME,
    DOORID_OOT_GUARD_HOUSE,
    DOORID_OOT_HYRULE_CASTLE,
    DOORID_OOT_DOG_LADY_HOUSE,
    DOORID_OOT_BACK_ALLEY_HOUSE,
    DOORID_OOT_BOMBCHU_SHOP,
    DOORID_OOT_MASK_SHOP,
    DOORID_OOT_CHILD_BAZAAR,
    DOORID_OOT_CHILD_POTION_SHOP,
    DOORID_OOT_CHILD_SHOOTING_GALLERY,
    DOORID_OOT_BOMBCHU_BOWLING,
    DOORID_OOT_LABORATORY,
    DOORID_OOT_FISHING_POND,
    DOORID_OOT_SILO,
    DOORID_OOT_RANCH_STABLE,
    DOORID_OOT_RANCH_HOUSE,
    DOORID_OOT_GRAVEYARD,
    DOORID_OOT_WINDMILL,
    DOORID_OOT_IMPA_HOUSE,
    DOORID_OOT_CARPENTER_HOUSE,
    DOORID_OOT_GRANNY_POTION_SHOP,
    DOORID_OOT_ADULT_SHOOTING_GALLERY,
    DOORID_OOT_SKULLTULA_HOUSE,
    DOORID_OOT_ADULT_BAZAAR,
    DOORID_OOT_ADULT_POTION_SHOP,
    DOORID_OOT_ADULT_POTION_SHOP_BACK,
    DOORID_OOT_MAX
};

void Door_DrawRustyLock(PlayState* play);

#endif
