#ifndef COMBO_EQUIPMENT_H
#define COMBO_EQUIPMENT_H

#define EQ_OOT_SWORD_KOKIRI         0x0001
#define EQ_OOT_SWORD_MASTER         0x0002
#define EQ_OOT_SWORD_KNIFE          0x0004
#define EQ_OOT_SWORD_KNIFE_BROKEN   0x0008

#endif
