#ifndef COMBO_ITEMS_H
#define COMBO_ITEMS_H

#define ITEM_OOT_DEKU_STICK             0x00
#define ITEM_OOT_DEKU_NUT               0x01
#define ITEM_OOT_BOMB                   0x02
#define ITEM_OOT_FAIRY_BOW              0x03
#define ITEM_OOT_FIRE_ARROW             0x04
#define ITEM_OOT_DIN_FIRE               0x05
#define ITEM_OOT_FAIRY_SLINGSHOT        0x06
#define ITEM_OOT_FAIRY_OCARINA          0x07
#define ITEM_OOT_OCARINA_OF_TIME        0x08
#define ITEM_OOT_BOMBCHU_10             0x09
#define ITEM_OOT_HOOKSHOT               0x0A
#define ITEM_OOT_LONGSHOT               0x0B
#define ITEM_OOT_ICE_ARROW              0x0C
#define ITEM_OOT_FARORE_WIND            0x0D
#define ITEM_OOT_BOOMERANG              0x0E
#define ITEM_OOT_LENS_OF_TRUTH          0x0F
#define ITEM_OOT_MAGIC_BEAN             0x10
#define ITEM_OOT_MEGATON_HAMMER         0x11
#define ITEM_OOT_LIGHT_ARROW            0x12
#define ITEM_OOT_NAYRU_LOVE             0x13
#define ITEM_OOT_EMPTY_BOTTLE           0x14
#define ITEM_OOT_RED_POTION             0x15
#define ITEM_OOT_GREEN_POTION           0x16
#define ITEM_OOT_BLUE_POTION            0x17
#define ITEM_OOT_BOTTLED_FAIRY          0x18
#define ITEM_OOT_FISH                   0x19
#define ITEM_OOT_LON_LON_MILK_BOTTLE    0x1A
#define ITEM_OOT_RUTO_LETTER            0x1B
#define ITEM_OOT_BLUE_FIRE              0x1C
#define ITEM_OOT_BUG                    0x1D
#define ITEM_OOT_BIG_POE                0x1E
#define ITEM_OOT_LON_LON_MILK_HALF      0x1F
#define ITEM_OOT_POE                    0x20
#define ITEM_OOT_WEIRD_EGG              0x21
#define ITEM_OOT_CHICKEN                0x22
#define ITEM_OOT_ZELDA_LETTER           0x23
#define ITEM_OOT_KEATON_MASK            0x24
#define ITEM_OOT_SKULL_MASK             0x25
#define ITEM_OOT_SPOOKY_MASK            0x26
#define ITEM_OOT_BUNNY_HOOD             0x27
#define ITEM_OOT_GORON_MASK             0x28
#define ITEM_OOT_ZORA_MASK              0x29
#define ITEM_OOT_GERUDO_MASK            0x2A
#define ITEM_OOT_MASK_OF_TRUTH          0x2B
#define ITEM_OOT_SOLD_OUT               0x2C
#define ITEM_OOT_POCKET_EGG             0x2D
#define ITEM_OOT_POCKET_CUCCO           0x2E
#define ITEM_OOT_COJIRO                 0x2F
#define ITEM_OOT_ODD_MUSHROOM           0x30
#define ITEM_OOT_ODD_POTION             0x31
#define ITEM_OOT_POACHER_SAW            0x32
#define ITEM_OOT_GORON_SWORD_BROKEN     0x33
#define ITEM_OOT_PRESCRIPTION           0x34
#define ITEM_OOT_EYEBALL_FROG           0x35
#define ITEM_OOT_EYE_DROPS              0x36
#define ITEM_OOT_CLAIM_CHECK            0x37
#define ITEM_OOT_FAIRY_BOW_FIRE_ARROW   0x38
#define ITEM_OOT_FAIRY_BOW_ICE_ARROW    0x39
#define ITEM_OOT_FAIRY_BOW_LIGHT_ARROW  0x3A
#define ITEM_OOT_KOKIRI_SWORD           0x3B
#define ITEM_OOT_MASTER_SWORD           0x3C
#define ITEM_OOT_GIANT_KNIFE_BS         0x3D
#define ITEM_OOT_DEKU_SHIELD            0x3E
#define ITEM_OOT_HYLIAN_SHIELD          0x3F
#define ITEM_OOT_MIRROR_SHIELD          0x40
#define ITEM_OOT_KOKIRI_TUNIC           0x41
#define ITEM_OOT_GORON_TUNIC            0x42
#define ITEM_OOT_ZORA_TUNIC             0x43
#define ITEM_OOT_KOKIRI_BOOTS           0x44
#define ITEM_OOT_IRON_BOOTS             0x45
#define ITEM_OOT_HOVER_BOOTS            0x46
#define ITEM_OOT_BULLET_BAG             0x47
#define ITEM_OOT_BULLET_BAG2            0x48
#define ITEM_OOT_BULLET_BAG3            0x49
#define ITEM_OOT_QUIVER                 0x4A
#define ITEM_OOT_QUIVER2                0x4B
#define ITEM_OOT_QUIVER3                0x4C
#define ITEM_OOT_BOMB_BAG               0x4D
#define ITEM_OOT_BOMB_BAG2              0x4E
#define ITEM_OOT_BOMB_BAG3              0x4F
#define ITEM_OOT_GORON_BRACELET         0x50
#define ITEM_OOT_SILVER_GAUNTLETS       0x51
#define ITEM_OOT_GOLDEN_GAUNTLETS       0x52
#define ITEM_OOT_SILVER_SCALE           0x53
#define ITEM_OOT_GOLDEN_SCALE           0x54
#define ITEM_OOT_GIANT_KNIFE_BROKEN     0x55
#define ITEM_OOT_WALLET2                0x56
#define ITEM_OOT_WALLET3                0x57
#define ITEM_OOT_DEKU_SEEDS_5           0x58
#define ITEM_OOT_FISHING_POLE           0x59
#define ITEM_OOT_SONG_TP_FOREST         0x5A
#define ITEM_OOT_SONG_TP_FIRE           0x5B
#define ITEM_OOT_SONG_TP_WATER          0x5C
#define ITEM_OOT_SONG_TP_SPIRIT         0x5D
#define ITEM_OOT_SONG_TP_SHADOW         0x5E
#define ITEM_OOT_SONG_TP_LIGHT          0x5F
#define ITEM_OOT_SONG_ZELDA             0x60
#define ITEM_OOT_SONG_EPONA             0x61
#define ITEM_OOT_SONG_SARIA             0x62
#define ITEM_OOT_SONG_SUN               0x63
#define ITEM_OOT_SONG_TIME              0x64
#define ITEM_OOT_SONG_STORMS            0x65
#define ITEM_OOT_MEDALLION_FOREST       0x66
#define ITEM_OOT_MEDALLION_FIRE         0x67
#define ITEM_OOT_MEDALLION_WATER        0x68
#define ITEM_OOT_MEDALLION_SPIRIT       0x69
#define ITEM_OOT_MEDALLION_SHADOW       0x6A
#define ITEM_OOT_MEDALLION_LIGHT        0x6B
#define ITEM_OOT_STONE_EMERALD          0x6C
#define ITEM_OOT_STONE_RUBY             0x6D
#define ITEM_OOT_STONE_SAPPHIRE         0x6E
#define ITEM_OOT_STONE_OF_AGONY         0x6F
#define ITEM_OOT_GERUDO_CARD            0x70
#define ITEM_OOT_GS_TOKEN               0x71
#define ITEM_OOT_HEART_CONTAINER        0x72
#define ITEM_OOT_HEART_PIECE2           0x73
#define ITEM_OOT_BIG_KEY                0x74
#define ITEM_OOT_COMPASS                0x75
#define ITEM_OOT_MAP                    0x76
#define ITEM_OOT_SMALL_KEY              0x77
#define ITEM_OOT_MAGIC_JAR_SMALL        0x78
#define ITEM_OOT_MAGIC_JAR_LARGE        0x79
#define ITEM_OOT_HEART_PIECE            0x7A
#define ITEM_OOT_LON_LON_MILK           0x82
#define ITEM_OOT_RECOVERY_HEART         0x83
#define ITEM_OOT_RUPEE_GREEN            0x84
#define ITEM_OOT_RUPEE_BLUE             0x85
#define ITEM_OOT_RUPEE_RED              0x86
#define ITEM_OOT_RUPEE_PURPLE           0x87
#define ITEM_OOT_RUPEE_HUGE             0x88
#define ITEM_OOT_DEKU_STICKS_5          0x8a
#define ITEM_OOT_DEKU_STICKS_10         0x8b
#define ITEM_OOT_DEKU_NUTS_5            0x8C
#define ITEM_OOT_DEKU_NUTS_10           0x8D
#define ITEM_OOT_BOMBS_5                0x8E
#define ITEM_OOT_BOMBS_10               0x8F
#define ITEM_OOT_BOMBS_20               0x90
#define ITEM_OOT_BOMBS_30               0x91
#define ITEM_OOT_ARROWS_5               0x92
#define ITEM_OOT_ARROWS_10              0x93
#define ITEM_OOT_ARROWS_30              0x94
#define ITEM_OOT_DEKU_SEEDS_30          0x95
#define ITEM_OOT_BOMBCHU_5              0x96
#define ITEM_OOT_BOMBCHU_20             0x97
#define ITEM_OOT_DEKU_STICK_UPGRADE     0x98
#define ITEM_OOT_DEKU_STICK_UPGRADE2    0x99
#define ITEM_OOT_DEKU_NUT_UPGRADE       0x9A
#define ITEM_OOT_DEKU_NUT_UPGRADE2      0x9b

#endif
